// ============================================================
//  MOONKAI — roster part 2 (fighters 20–34)
// ============================================================
fighter({
  id: 'kage', name: 'KAGE', title: 'The Last Ronin', side: 'ANTI-HERO', role: 'Iaido · Counters', color: '#ff5a5a', color2: '#1a0a0a',
  bio: 'A samurai who swore to protect a lord who died four hundred years ago. He never stopped. His blade is cursed with a demon who wants out.',
  quote: 'One cut is enough.', ending: 'Kage finally sheathes his sword and lets the demon go free. It thanks him, bows, and opens a noodle shop.',
  hp: 980, walk: 250, rival: 'nyx',
  model: { skin: '#e0b890', top: '#2a2a3a', topDark: '#1a1a2a', pants: '#3a2a2a', boots: '#222', belt: '#c03030', hair: { type: 'topknot', color: '#1a1a1a' }, weapon: { type: 'katana', color: '#dde', guard: '#ffd35a' }, sleeves: '#3a3a4a', coat: '#2a2a3a' },
  face: { expr: 'cold', eyes: '#8a2020', marks: [{ type: 'scar', color: '#8a4a4a' }] },
  style: { reach: 1.3, weapon: true, power: 1.1, speed: 1.05 },
  passive: ['Iaido', 'Attacks from standing still deal 20% more damage.'],
  passiveDmg(f) { return Math.abs(f.vx) < 30 ? 1.2 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Air Slash', desc: 'A crescent of wind from his blade.', proj: { speed: 1000, r: 14, dmg: 65, kind: 'crescent', color: '#fff', trail: false } }),
    '6S': Mv.rush({ name: 'Quickdraw', desc: 'Instant slash through the enemy.', s: 16, speed: 2000, frames: 8, pass: true, hit: { dmg: 130, kb: [200, -400] } }),
    '2S': Mv.counter({ name: 'Mirror Stance', desc: 'Parry and cut.', window: 26, dmg: 140 }),
    '4S': Mv.rekka({ name: 'Three Cuts', desc: 'Press S again for up to three slashes.', steps: [{ speed: 700, frames: 8, hit: { dmg: 55, kb: [200, 0], launch: false } }, { speed: 700, frames: 8, hit: { dmg: 60, kb: [200, 0], launch: false } }, { speed: 800, frames: 10, hit: { dmg: 80, kb: [600, -500] } }] }),
    'jS': Mv.dive({ name: 'Falling Leaf', desc: 'Diagonal sword dive.', hit: { dmg: 90 } }),
  },
  super: Sup.rush({ name: 'Hundred Cuts', desc: 'A blur of steel.', speed: 1700, frames: 12, pass: true, hit: { dmg: 30, multi: 10, every: 2 } }),
  ult: { act: 'rush', name: 'DEMON SEVERANCE', desc: 'A single draw. On hit: the demon is released.', dmg: 1200, template: 'rush', fx: { el: 'blood', color: '#ff5a5a', sky: ['#0a0000', '#2a0404', '#5a0a0a'], lines: ['One cut.', 'Is enough.'] } },
  form: { name: 'ONI BLADE', desc: 'Permanent. The demon awakens: longer reach, lifesteal.', dmg: 1.15, lifesteal: 0.12, speed: 1.05, model: { aura: '#ff3030', eyes: { glow: '#ff3030' }, horns: { color: '#3a0a0a' }, weapon: { type: 'katana', color: '#faa', glow: '#ff3030' }, mask: { type: 'oni', color: '#8a1010' } } },
  assist: '5S',
  lines: { intro: ['Draw your weapon, {opp}.', '...', 'My lord commands it.'], win: ['One cut.', 'Your stance was weak.', 'Rest in the petals.'], taunt: ['Hmph.', 'Come.'], form: ['Awaken, demon.'], ult: ['Severance.'], ultHit: ['...Sheathe.'] },
});

fighter({
  id: 'arachna', name: 'ARACHNA', title: 'The Web Weaver', side: 'VILLAIN', role: 'Trapper · Webs', color: '#c01060', color2: '#14080e',
  bio: 'A geneticist who spliced herself with a thousand spiders to cure her disease. It worked. She now considers the whole city her web.',
  quote: 'Come into my parlor.', ending: 'Arachna webs the entire city into one enormous cocoon. It is warm and oddly cozy. Crime drops to zero.',
  hp: 950, walk: 280, rival: 'mortis',
  model: { build: 'slim', skin: '#e8d0d8', top: '#1a0a14', pants: '#1a0a14', boots: '#0a0a0a', hair: { type: 'long', color: '#1a0a14' }, spiderLegs: { color: '#2a0a1a' }, emblem: { shape: 'skull', color: '#c01060' }, eyes: { glow: '#c01060' }, weapon: { type: 'claws', color: '#c01060' } },
  face: { expr: 'smirk', eyes: '#c01060', marks: [{ type: 'tear', color: '#c01060' }] },
  passive: ['Venom', 'Hits poison the enemy.'],
  onHit(a, t) { if (Math.random() < 0.35) t.status.poison = Math.max(t.status.poison || 0, 2.5); },
  moves: {
    '5S': Mv.shot({ name: 'Web Shot', desc: 'A web that slows and snares.', proj: { speed: 800, r: 14, dmg: 40, kind: 'web', color: '#eee', status: { slow: 2 }, stun: 0.4, trail: false } }),
    '6S': Mv.shot({ name: 'Web Line', desc: 'A strand that yanks the enemy in.', proj: { speed: 1200, r: 10, dmg: 40, kind: 'hook', color: '#eee', trail: false, life: 0.6, pull: true, hs: 30 } }),
    '2S': Mv.place({ name: 'Web Trap', desc: 'A hidden web on the floor (max 2).', spawn: { kind: 'trap', at: 'front', dx: 200, color: '#eee', stun: 1.1, dmg: 30, limit: 2 }, cd: 3 }),
    '4S': Mv.place({ name: 'Brood', desc: 'A skittering spider minion.', spawn: { kind: 'minion', at: 'front', dx: 40, look: 'skeleton', dmg: 45, hp: 50, speed: 380, color: '#c01060' }, cd: 5 }),
    'jS': Mv.dive({ name: 'Drop From Above', desc: 'Descends on a thread.', vx: 200, vy: 1400, hit: { dmg: 80, status: { poison: 2 } } }),
  },
  super: Sup.place({ name: 'Nest', desc: 'Webs cover the floor.', spawn: { kind: 'trap', at: 'enemy', count: 4, spacing: 120, color: '#eee', stun: 1, dmg: 40 } }),
  ult: { act: 'shot', name: 'WEB OF DOOM', desc: 'A net shot. On hit: wrapped and devoured.', dmg: 1100, template: 'dimension', proj: { kind: 'web', color: '#eee', r: 24 }, fx: { el: 'web', world: 'web', color: '#c01060', sky: ['#050005', '#1a0a14', '#3a0a2a'], lines: ['Caught.', 'Dinner is served.'] } },
  form: { name: 'BROOD QUEEN', desc: 'Permanent. Eight legs, faster, poison twice as strong.', speed: 1.12, dmg: 1.1, scale: 1.1, model: { aura: '#c01060', spiderLegs: { color: '#4a0a2a' }, eyes: { glow: '#ff2080' }, top: '#2a0a1a' } },
  assist: '2S',
  lines: { intro: ['Such a lovely fly, {opp}.', 'Every thread leads to me.', 'Come closer.'], win: ['Wrapped and ready.', 'You struggled beautifully.', 'The web holds.'], taunt: ['Tangled?', 'Skitter skitter.'], form: ['My children!'], ult: ['Caught.'], ultHit: ['Delicious.'] },
});

fighter({
  id: 'hex', name: 'HEX', title: 'The Coven Mother', side: 'VILLAIN', role: 'Curses · Zones', color: '#9a5aff', color2: '#1a0a2a',
  bio: 'The last witch of a coven that was burned in 1692. She has been patient. Very patient. And she has been brewing.',
  quote: 'Double, double, you\'re in trouble.', ending: 'Hex curses the city to only speak in rhyme. The mayor finds it charming. Hex is furious that it worked so well.',
  hp: 950, walk: 240, floaty: true, rival: 'seraph',
  model: { build: 'curvy', skin: '#c0e0b0', top: '#2a1a3a', pants: '#2a1a3a', skirt: '#3a1a5a', boots: '#111', hair: { type: 'long', color: '#1a1a1a' }, hat: { type: 'wizard', color: '#1a0a2a' }, weapon: { type: 'book', color: '#6a3a2a', glow: '#9a5aff' }, emblem: { shape: 'moon', color: '#9a5aff' }, cape: { color: '#1a0a2a' } },
  face: { expr: 'grin', eyes: '#9a5aff', hat: { type: 'wizard', color: '#1a0a2a' } },
  passive: ['Curse', 'Hits have a chance to weaken the enemy (−25% damage).'],
  onHit(a, t) { if (Math.random() < 0.25) t.status.weaken = Math.max(t.status.weaken || 0, 3); },
  moves: {
    '5S': Mv.shot({ name: 'Hex Bolt', desc: 'A cursed bolt that weakens.', proj: { speed: 650, r: 12, dmg: 55, kind: 'poison', color: '#9a5aff', status: { weaken: 3 } } }),
    '6S': Mv.place({ name: 'Cauldron', desc: 'A bubbling poison zone.', spawn: { kind: 'zone', at: 'front', dx: 220, r: 100, life: 4, every: 0.4, dmg: 14, color: '#6aff5a', status: { poison: 1 } }, cd: 6 }),
    '2S': Mv.place({ name: 'Grasping Roots', desc: 'Roots burst up beneath the enemy.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 75, color: '#6a3a2a', fill: '#3a2a1a', status: { slow: 2 } } }),
    '4S': Mv.swap({ name: 'Frog Curse', desc: 'Swaps places and confuses.', confuse: 1.5, dmg: 50, cd: 8 }),
    'jS': Mv.shot({ name: 'Broom Bombs', desc: 'Drops potions.', proj: { speed: 300, angle: 1.2, g: 1000, r: 10, dmg: 50, kind: 'poison', color: '#6aff5a', explode: 70, status: { poison: 2 } } }),
  },
  super: Sup.place({ name: 'Witching Circle', desc: 'A massive curse circle.', spawn: { kind: 'zone', at: 'enemy', r: 180, life: 3, every: 0.25, dmg: 26, color: '#9a5aff', status: { weaken: 2, slow: 1 } } }),
  ult: { act: 'strike', name: 'WITCHING HOUR', desc: 'A curse from the sky. On hit: the coven\'s demon rises.', dmg: 1100, template: 'summon', style: 'light', color: '#9a5aff', fx: { el: 'poison', creature: 'demon', color: '#9a5aff', sky: ['#0a0014', '#1a0a2a', '#3a1a4a'], lines: ['The hour has struck.', 'Sisters, feast.'] } },
  form: { name: 'COVEN MOTHER', desc: 'Permanent. Floats, curses stack harder.', dmg: 1.12, scale: 1.1, flight: true, model: { aura: '#9a5aff', float: true, eyes: { glow: '#9a5aff' }, hair: { type: 'wild', color: '#3a1a5a' } } },
  assist: '6S',
  lines: { intro: ['Eye of newt, toe of {opp}.', 'I have been brewing for centuries.', 'Hehehehe.'], win: ['Into the cauldron with you!', 'Cursed, cursed, cursed!', 'Toil and trouble.'], taunt: ['Ribbit.', 'Hehehe!'], form: ['Sisters, lend me power!'], ult: ['Witching hour!'], ultHit: ['Hexed forever.'] },
});

fighter({
  id: 'maximus', name: 'MAXIMUS', title: 'The Star Paladin', side: 'HERO', role: 'Defender · Shield', color: '#ffd35a', color2: '#1a2a5a',
  bio: 'The last knight of a celestial order that guarded the gates between stars. His shield has never broken. His patience occasionally has.',
  quote: 'Stand behind me.', ending: 'Maximus becomes the city\'s official guardian. He takes the job very seriously. He also takes parking enforcement very seriously.',
  hp: 1150, walk: 230, weight: 0.85, rival: 'judge',
  model: { build: 'athletic', skin: '#e0b890', top: '#c0c8d8', topDark: '#8a94a8', pants: '#3a4a7a', boots: '#c0c8d8', belt: '#ffd35a', hair: { type: 'helmet', color: '#c0c8d8', visor: '#1a2a5a' }, cape: { color: '#1a2a7a', inner: '#ffd35a' }, weapon: { type: 'shield', color: '#1a2a7a', accent: '#ffd35a', sword: '#dde' }, emblem: { shape: 'star', color: '#ffd35a' }, pads: { color: '#ffd35a' } },
  face: { expr: 'calm', eyes: '#3a6ad8', hair: { type: 'short', color: '#d8c080' } },
  style: { heavy: true, weapon: true, speed: 1.1 },
  passive: ['Aegis', 'Blocking fills his meter twice as fast and he takes no chip damage.'],
  passiveArmor(f) { return f.blockstun ? 0.5 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Star Shield Throw', desc: 'Boomerang shield.', proj: { speed: 800, r: 16, dmg: 60, kind: 'star', color: '#ffd35a', boomerang: 0.5, life: 2.5 } }),
    '6S': Mv.rush({ name: 'Shield Bash', desc: 'Armored bash that wall-bounces.', speed: 900, frames: 14, armor: [2, 22], hit: { dmg: 100, kb: [800, -200], wb: true } }),
    '2S': Mv.counter({ name: 'Aegis Guard', desc: 'Reflect stance.', resp: 'reflect', window: 30 }),
    '4S': Mv.place({ name: 'Light Barrier', desc: 'A wall of light that blocks projectiles.', spawn: { kind: 'wall', at: 'front', dx: 70, w: 30, hgt: 180, hp: 400, life: 4, style: 'light', color: '#ffd35a', limit: 1 }, cd: 6 }),
    'jS': Mv.dive({ name: 'Comet Strike', desc: 'Sword-first dive.', hit: { dmg: 95 } }),
  },
  super: Sup.rising({ name: 'Rising Star', desc: 'Invincible starlight uppercut.', hit: { dmg: 40 } }),
  ult: { act: 'beam', name: 'AEGIS OF STARS', desc: 'A beam of starlight. On hit: the constellations answer.', dmg: 1100, template: 'megabeam', beam: { color: '#ffe08a' }, fx: { el: 'star', color: '#ffd35a', sky: ['#02040a', '#0a1a3a', '#2a3a7a'], lines: ['By the oath of the stars...', 'Aegis!'] } },
  form: { name: 'CELESTIAL PALADIN', desc: 'Permanent. Star armor: super armor, radiant sword.', superArmor: true, armor: 0.8, dmg: 1.12, scale: 1.1, model: { aura: '#ffd35a', top: '#fff0c0', wings: { type: 'light', color: '#ffe9a0', scale: 1 }, eyes: { glow: '#ffd35a' } } },
  onHurt(t) { if (t.blockstun) t.side.meter += 6; },
  assist: '4S',
  lines: { intro: ['Stand down, {opp}. I will not ask twice.', 'The stars are watching.', 'For the order!'], win: ['Justice, served with a shield.', 'Yield.', 'The gate holds.'], taunt: ['For honor!', 'Hah!'], form: ['Celestial armor!'], ult: ['Aegis of the stars!'], ultHit: ['The oath is kept.'] },
});

fighter({
  id: 'rex', name: 'REX', title: 'The Tyrant', side: 'VILLAIN', role: 'Bruiser · Giant', color: '#6aba3a', color2: '#1a2a0a',
  bio: 'A dinosaur thawed from Antarctic ice by Dr. Gear, then accidentally given a genius IQ. He is extremely angry about the asteroid.',
  quote: 'EXTINCTION WAS PERSONAL.', ending: 'Rex builds a planetary defense grid so no asteroid can ever hit Earth again. He is still angry. He will always be angry.',
  hp: 1150, walk: 230, weight: 0.8, wide: 1.2, rival: 'leo',
  model: { build: 'heavy', skin: '#6aba3a', top: '#5aa030', pants: '#4a8a2a', boots: '#2a4a1a', animal: { type: 'dino', color: '#6aba3a' }, bigTail: '#5aa030', weapon: { type: 'claws', color: '#eee' } },
  face: { animal: { type: 'dino', color: '#6aba3a', eyeColor: '#ffe040' } },
  style: { power: 1.2, speed: 1.1, heavy: true },
  passive: ['Apex Predator', 'Deals 20% more damage to enemies below half health.'],
  passiveDmg(f, t) { return t && t.hp < t.maxHp / 2 ? 1.2 : 1; },
  moves: {
    '5S': Mv.custom({ name: 'Roar', desc: 'A stunning roar.', pose: 'charge', s: 18, a: 8, r: 24, hit: { dmg: 30, box: [0, -140, 180, 140], stun: 0.8, kb: [200, 0], hs: 10 }, ai: { min: 0, max: 160, use: 'combo' } }),
    '6S': Mv.rush({ name: 'Stampede', desc: 'Armored charge.', speed: 850, frames: 24, armor: [4, 30], hit: { dmg: 120, kb: [700, -300], wb: true } }),
    '2S': Mv.grab({ name: 'Chomp', desc: 'Bite command grab that drains.', range: 70, grabData: { anim: 'drain', dmg: 200, frames: 36 } }),
    '4S': Mv.place({ name: 'Tail Quake', desc: 'Tail slam sends a shockwave.', spawn: { kind: 'wave', at: 'front', dx: 50, dir: 1, dmg: 75, life: 0.9 } }),
    'jS': Mv.dive({ name: 'Belly Flop', desc: 'Crushing dive.', vx: 300, vy: 1500, hit: { dmg: 120, gb: true } }),
  },
  super: Sup.grab({ name: 'Death Roll', desc: 'Bite and spin.', range: 80, grabData: { anim: 'spin', dmg: 400 } }),
  ult: { act: 'rush', name: 'EXTINCTION EVENT', desc: 'A furious charge. On hit: he brings the asteroid.', dmg: 1250, template: 'meteor', fx: { el: 'fire', color: '#ff8a1a', sky: ['#1a0a00', '#5a2000', '#c06020'], lines: ['You want to know how it felt?', 'LIKE THIS.'] } },
  form: { name: 'TYRANT KING', desc: 'TIMED (12s). Colossal size, super armor, huge damage.', timed: 12, cost: 300, scale: 1.9, speed: 0.8, armor: 0.6, dmg: 1.4, superArmor: true, heavyLanding: true, model: { skin: '#3a8a2a', top: '#2a7a1a', animal: { type: 'dino', color: '#3a8a2a' }, bigTail: '#2a6a1a', aura: '#ff8a1a' } },
  assist: '6S',
  lines: { intro: ['SMALL MAMMAL. I REMEMBER YOUR KIND.', 'The asteroid missed ONE of us.', 'ROOOAR. That is "hello" in dinosaur.'], win: ['EXTINCT.', 'Survival of the angriest.', 'ROAR!'], taunt: ['ROAR!', 'Tiny arms, big problems.'], form: ['TYRANT KING!'], ult: ['EXTINCTION!'], ultHit: ['Now you know.'] },
});

fighter({
  id: 'zephyr', name: 'ZEPHYR', title: 'The Wind Monk', side: 'HERO', role: 'Air · Mobility', color: '#aaffdd', color2: '#1a3a3a',
  bio: 'A monk from a temple in the sky who has never touched the ground. Literally. He finds walking vulgar.',
  quote: 'Be the breeze.', ending: 'Zephyr finally touches the ground. He hates it. He goes back up and becomes the city\'s weather.',
  hp: 950, walk: 300, floaty: true, jumps: 4, rival: 'dune',
  model: { build: 'slim', skin: '#e0c0a0', top: '#e8f8f0', topDark: '#b0d0c0', pants: '#8ad0b0', boots: '#e8f8f0', hair: { type: 'bald', color: '#000' }, sleeves: '#e8f8f0', scarf: { color: '#aaffdd' }, emblem: { shape: 'leaf', color: '#3a8a6a' }, weapon: { type: 'fan', color: '#aaffdd' }, float: true },
  face: { expr: 'calm', eyes: '#3a8a6a', hair: { type: 'bald', color: '#000' }, marks: [{ type: 'paint', color: '#3aaa8a' }] },
  style: { speed: 0.85 },
  passive: ['Weightless', 'Four jumps, floaty air control, air dashes twice.'],
  moves: {
    '5S': Mv.shot({ name: 'Gale Palm', desc: 'A gust that pushes away.', proj: { speed: 800, r: 20, dmg: 45, kind: 'ring', color: '#aaffdd', kb: [800, -100], trail: false } }),
    '6S': Mv.rush({ name: 'Tornado Kick', desc: 'Spinning airborne kick.', pose: 'kick', vy: -200, speed: 900, frames: 18, hit: { dmg: 30, multi: 3, every: 5, kb: [300, -400] } }),
    '2S': Mv.place({ name: 'Cyclone', desc: 'A cyclone that lifts the enemy.', spawn: { kind: 'zone', at: 'front', dx: 250, r: 70, life: 1.5, every: 0.2, dmg: 12, color: '#aaffdd', pull: true } }),
    '4S': Mv.teleport({ name: 'Drift', desc: 'Floats backwards out of danger.', to: 'back' }),
    'jS': Mv.shot({ name: 'Falling Wind', desc: 'Wind blades downward.', proj: { speed: 900, r: 14, dmg: 34, count: 3, spread: 0.5, angle: 0.8, kind: 'crescent', color: '#aaffdd', trail: false } }),
  },
  super: Sup.rush({ name: 'Hurricane Kick', desc: 'Whirlwind kick rush.', vy: -100, hit: { dmg: 26 } }),
  ult: { act: 'rush', name: 'EYE OF THE STORM', desc: 'A cyclone kick. On hit: a tornado of a thousand kicks.', dmg: 1100, template: 'rush', fx: { el: 'wind', color: '#aaffdd', sky: ['#0a1a1a', '#2a4a4a', '#6a9a9a'], lines: ['Be still.', 'I am the storm\'s eye.'] } },
  form: { name: 'EYE OF THE STORM', desc: 'Permanent. Flight and faster wind.', flight: true, speed: 1.15, dmg: 1.1, model: { aura: '#aaffdd', eyes: { glow: '#aaffdd' }, scarf: { color: '#fff' } } },
  assist: '5S',
  lines: { intro: ['The ground is so... grounding. Ew.', 'Breathe with me, {opp}.', 'I will not touch the floor.'], win: ['Blown away.', 'Be the breeze.', 'Peace.'], taunt: ['Whoosh.', 'Namaste.'], form: ['I am the eye.'], ult: ['Eye of the storm.'], ultHit: ['Calm.'] },
});

fighter({
  id: 'helios', name: 'HELIOS', title: 'The Sun God', side: 'ANTI-HERO', role: 'Glass cannon · Heat', color: '#ffb020', color2: '#5a2a00',
  bio: 'An ancient sun god who woke up in a museum. He believes he is still worshipped. Nobody has the heart to tell him.',
  quote: 'BASK IN MY RADIANCE.', ending: 'Helios is worshipped again, by one very enthusiastic gift shop employee. It is enough. He glows with pride.',
  hp: 920, walk: 250, rival: 'luna',
  model: { build: 'athletic', skin: '#d8a050', top: '#ffd35a', topDark: '#c09030', pants: '#fff0d0', skirt: '#ffd35a', boots: '#ffd35a', belt: '#c09030', hair: { type: 'long', color: '#fff0a0' }, hat: { type: 'tiara', color: '#ffd35a' }, emblem: { shape: 'sun', color: '#ff8a1a' }, weapon: { type: 'staff', color: '#ffd35a', tip: '#ffb020' }, abs: true },
  face: { expr: 'grin', eyes: '#ffb020', glow: '#ffb020', hat: { type: 'tiara', color: '#ffd35a' } },
  style: { reach: 1.15, weapon: true, power: 1.1 },
  passive: ['Solar Flare', 'Builds heat by attacking. At max heat, his next special deals double damage.'],
  onHit(a) { a.heat = Math.min(100, (a.heat || 0) + 8); },
  passiveDmg(f) { return (f.heat || 0) >= 100 && f.move && f.move.kind === 'special' ? (f.heat = 0, 2) : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Sunball', desc: 'A small sun.', proj: { speed: 600, r: 16, dmg: 75, kind: 'fire', color: '#ffb020', status: { burn: 2 }, prio: 2 } }),
    '6S': Mv.beam({ name: 'Solar Ray', desc: 'A short burning ray.', s: 18, beam: { len: 700, width: 30, dur: 24, dmg: 14, color: '#ffd35a' } }),
    '2S': Mv.rising({ name: 'Sunrise', desc: 'Blazing rising arc.', hit: { dmg: 48, multi: 3, status: { burn: 2 } } }),
    '4S': Mv.place({ name: 'Heat Mirage', desc: 'A zone of scorching heat.', spawn: { kind: 'zone', at: 'self', r: 130, life: 3, every: 0.35, dmg: 14, color: '#ffb020', status: { burn: 1 }, follow: true }, cd: 7 }),
    'jS': Mv.shot({ name: 'Sunspots', desc: 'Falling fire.', proj: { speed: 700, r: 12, dmg: 36, count: 3, spread: 0.6, angle: 1.0, kind: 'fire', color: '#ffb020' } }),
  },
  super: Sup.beam({ name: 'Midday Beam', desc: 'A column of sunlight.', beam: { color: '#ffd35a', dmg: 28, width: 80 } }),
  ult: { act: 'beam', name: 'SOLAR GENESIS', desc: 'A beam of pure sun. On hit: a new star is born.', dmg: 1250, template: 'megabeam', beam: { color: '#ffd35a' }, fx: { el: 'sun', color: '#ffb020', sky: ['#200800', '#8a3a00', '#ffb020'], lines: ['Behold...', 'THE DAWN.'] } },
  form: { name: 'SUPERNOVA GOD', desc: 'TIMED (10s). Blinding power: everything burns, huge damage.', timed: 10, cost: 300, dmg: 1.45, speed: 1.15, scale: 1.2, superArmor: true, model: { aura: '#ffb020', auraSize: 1.6, skin: '#ffe0a0', top: '#fff6c0', hair: { type: 'flame', color: '#ffb020' }, eyes: { glow: '#fff' } },
    tick(f) { const o = f.opp; if (o && Math.abs(o.x - f.x) < 280 && f.st % 20 === 0) o.status.burn = 1; } },
  assist: '5S',
  lines: { intro: ['KNEEL BEFORE THE SUN, {opp}.', 'I have outlived empires.', 'Worship is mandatory.'], win: ['BASK!', 'The sun always rises.', 'Your tribute is accepted.'], taunt: ['BASK!', 'Radiant!'], form: ['SUPERNOVA!'], ult: ['SOLAR GENESIS!'], ultHit: ['Let there be day.'] },
});

fighter({
  id: 'luna', name: 'LUNA', title: 'The Eclipse', side: 'VILLAIN', role: 'Mixup · Crescents', color: '#c0c8ff', color2: '#1a1040',
  bio: "Eric's older sister, also moonborn. Where Eric's power made him a beast, hers made her a queen. Vex promised her the moon. She intends to collect.",
  quote: 'Little brother. You never learned control.', ending: "Luna rules the Moon. She sends Eric a postcard every month. It always says 'You could have been a prince.' He frames them.",
  hp: 980, walk: 270, rival: 'eric',
  model: { build: 'curvy', skin: '#f1c27d', top: '#2a1a5a', topDark: '#1a0a3a', pants: '#2a1a5a', skirt: '#3a2a7a', boots: '#c0c8ff', belt: '#c0c8ff', hair: { type: 'long', color: '#141414' }, hat: { type: 'tiara', color: '#c0c8ff' }, emblem: { shape: 'moon', color: '#c0c8ff' }, cape: { color: '#1a1040', inner: '#c0c8ff' }, weapon: { type: 'fan', color: '#c0c8ff' }, tail: '#6b4226' },
  face: { expr: 'smirk', eyes: '#c0c8ff', hat: { type: 'tiara', color: '#c0c8ff' } },
  passive: ['Moonborn', 'Her crescents curve. Every third hit in a combo restores 1% health.'],
  onHit(a, t) { if (t.comboHits % 3 === 0) a.hp = Math.min(a.maxHp, a.hp + a.maxHp * 0.01); },
  moves: {
    '5S': Mv.shot({ name: 'Crescent', desc: 'A curving moon blade.', proj: { speed: 800, r: 16, dmg: 60, kind: 'crescent', color: '#c0c8ff', angle: -0.2, homing: 1.2, trail: false } }),
    '6S': Mv.teleport({ name: 'Eclipse Step', desc: 'Vanish and strike from behind.', to: 'behind', hit: { dmg: 85 } }),
    '2S': Mv.place({ name: 'Moonbeam', desc: 'Silver light from above.', spawn: { kind: 'strike', at: 'enemy', delay: 0.45, dmg: 80, style: 'light', color: '#c0c8ff' }, ai: { min: 150, max: 1600, use: 'zone' } }),
    '4S': Mv.counter({ name: 'Lunar Reflection', desc: 'Reflecting counter.', resp: 'reflect', window: 24 }),
    'jS': Mv.shot({ name: 'Falling Crescents', desc: 'Two crescents downward.', proj: { speed: 900, r: 14, dmg: 40, count: 2, spread: 0.4, angle: 0.8, kind: 'crescent', color: '#c0c8ff', trail: false } }),
  },
  super: Sup.barrage({ name: 'Phases of the Moon', desc: 'A volley of crescents.', proj: { kind: 'crescent', color: '#c0c8ff', dmg: 28, r: 14 } }),
  ult: { act: 'strike', name: 'BLOOD MOON', desc: 'A lunar strike. On hit: the moon turns red and descends.', dmg: 1150, template: 'summon', style: 'light', color: '#ff4a6a', fx: { el: 'moon', creature: 'moon', color: '#ff4a6a', sky: ['#0a0010', '#2a0020', '#5a0030'], lines: ['Look up, little brother.', 'The moon is mine.'] } },
  form: { name: 'ECLIPSE EMPRESS', desc: 'Permanent. Dark moon aura, faster crescents.', dmg: 1.12, speed: 1.1, projSpeed: 1.25, scale: 1.08, model: { aura: '#6a4aff', top: '#0a0a1a', eyes: { glow: '#ff4a6a' }, cape: { color: '#0a0014', inner: '#ff4a6a' } } },
  assist: '2S',
  lines: { intro: ['Bow to your queen, {opp}.', 'The moon chose me first.', 'Shall we dance?'], win: ['Eclipsed.', 'Moonlight suits you. Lying down.', 'The throne is mine.'], taunt: ['Pathetic.', 'Tsk tsk.'], form: ['Eclipse.'], ult: ['Blood moon!'], ultHit: ['Goodnight.'] },
});
rival('eric', 'luna', [[1, 'Little brother. Still hiding that tail?'], [0, "Luna?! You're working for VEX?"], [1, 'I work for the moon. Vex just... pays.'], [0, 'Mom is going to be SO mad.']], { eric: "I'm telling Mom.", luna: 'Go home, little brother. The moon is mine.' });

fighter({
  id: 'cipher', name: 'CIPHER', title: 'The Ghost in the Machine', side: 'ANTI-HERO', role: 'Hacker · Disruption', color: '#2aff9a', color2: '#0a1a14',
  bio: 'An anonymous hacker who uploaded her mind into the city\'s network. She can be anywhere a screen is. She is mostly in your phone. She has read your messages.',
  quote: 'I\'m already in your system.', ending: 'Cipher deletes every villain\'s bank account, then donates the money anonymously. She keeps one dollar. For the principle.',
  hp: 920, walk: 290, rival: 'gear',
  model: { build: 'slim', skin: '#c8b0a0', top: '#0a1a14', pants: '#14141a', boots: '#2aff9a', hair: { type: 'hood', color: '#0a1a14' }, mask: { type: 'visor', color: '#2aff9a' }, emblem: { shape: 'eye', color: '#2aff9a' }, stripes: '#2aff9a', weapon: { type: 'orb', color: '#2aff9a' } },
  face: { hair: { type: 'hood', color: '#0a1a14' }, mask: { type: 'visor', color: '#2aff9a' }, expr: 'smirk', eyes: '#2aff9a' },
  passive: ['Firewall', 'Her hits drain the enemy\'s meter.'],
  onHit(a, t) { t.side.meter = Math.max(0, t.side.meter - 8); a.side.meter += 4; },
  moves: {
    '5S': Mv.shot({ name: 'Data Spike', desc: 'A fast packet of code.', proj: { speed: 1300, r: 8, dmg: 50, kind: 'pixel', color: '#2aff9a', life: 1.2 } }),
    '6S': Mv.teleport({ name: 'Packet Jump', desc: 'Teleports through the network.', to: 'front', hit: { dmg: 75 } }),
    '2S': Mv.place({ name: 'Drone Ping', desc: 'A hacked drone turret.', spawn: { kind: 'turret', at: 'front', dx: 80, life: 6, hp: 100, shotDmg: 18, color: '#2aff9a', body: '#1a3a2a', limit: 1 }, cd: 6 }),
    '4S': Mv.place({ name: 'Glitch Mine', desc: 'Silences and confuses.', spawn: { kind: 'trap', at: 'front', dx: 160, color: '#2aff9a', stun: 0.8, dmg: 40, limit: 2 }, cd: 3 }),
    'jS': Mv.shot({ name: 'Bit Rain', desc: 'Code drops down.', proj: { speed: 900, r: 8, dmg: 26, count: 4, spread: 0.5, angle: 1.0, kind: 'pixel', color: '#2aff9a' } }),
  },
  super: Sup.place({ name: 'DDoS', desc: 'Floods the area with data spikes.', spawn: { kind: 'strike', at: 'enemy', delay: 0.25, count: 6, spacing: 60, stagger: 0.06, dmg: 50, style: 'light', color: '#2aff9a', wide: 20 } }),
  ult: { act: 'shot', name: 'SYSTEM CRASH', desc: 'A virus shot. On hit: the victim is uploaded and deleted.', dmg: 1100, template: 'dimension', proj: { kind: 'pixel', color: '#2aff9a', r: 20 }, fx: { el: 'code', world: 'cyber', color: '#2aff9a', sky: ['#000', '#001a0a', '#003a1a'], lines: ['Uploading you.', 'Deleting...'] } },
  form: { name: 'ROOT ACCESS', desc: 'Permanent. Every hit drains twice as much meter.', dmg: 1.1, model: { aura: '#2aff9a', mask: { type: 'visor', color: '#fff' }, top: '#0a3a24' }, onStart(f) { f.def._root = true; } },
  assist: '2S',
  lines: { intro: ['I read your texts, {opp}. Yikes.', 'Connecting...', 'Your firewall is adorable.'], win: ['Hacked.', 'rm -rf {opp}', 'Access granted.'], taunt: ['lol', '404: skill not found'], form: ['sudo transform'], ult: ['System crash.'], ultHit: ['Deleted.'] },
});

fighter({
  id: 'fang', name: 'FANG', title: 'The Moon Wolf', side: 'ANTI-HERO', role: 'Rushdown · Bleed', color: '#b0b8c8', color2: '#1a1a2a',
  bio: 'A werewolf who hunts other monsters for bounties. He and Eric have a friendly rivalry over who the moon likes more.',
  quote: 'Awoooo.', ending: 'Fang and Eric howl at the moon together on the roof of the ruined city. The neighbors complain. Neither of them cares.',
  hp: 980, walk: 320, rival: 'eric',
  model: { build: 'athletic', skin: '#8a8a9a', top: '#4a3a2a', pants: '#3a3a4a', boots: '#2a2a2a', animal: { type: 'wolf', color: '#9aa2b0' }, tail: '#9aa2b0', weapon: { type: 'claws', color: '#eee' }, abs: true },
  face: { animal: { type: 'wolf', color: '#9aa2b0', eyeColor: '#ffd35a' } },
  style: { speed: 0.85 },
  passive: ['Bloodhound', 'Hits cause bleeding. Faster against bleeding targets.'],
  onHit(a, t) { if (Math.random() < 0.3) t.status.bleed = Math.max(t.status.bleed || 0, 2); },
  passiveDmg(f, t) { return t && t.status.bleed ? 1.12 : 1; },
  moves: {
    '5S': Mv.rush({ name: 'Lunge', desc: 'Pouncing claw.', speed: 1200, frames: 12, hit: { dmg: 80, status: { bleed: 2 } } }),
    '6S': Mv.flurry({ name: 'Frenzy', desc: 'Savage claw flurry.', hits: 7, every: 3, vel: [[4, 20, 300, null]], hit: { dmg: 16, status: { bleed: 1 } }, finisher: { dmg: 40, kb: [500, -400], launch: true } }),
    '2S': Mv.custom({ name: 'Howl', desc: 'Buffs speed and power.', pose: 'charge', s: 16, a: 1, r: 14, cd: 10, ev: { 16: f => Combat.buff(f, { haste: true, power: true }, 4, 'HOWL') }, ai: { min: 250, max: 2000, use: 'buff' } }),
    '4S': Mv.rising({ name: 'Moon Claw', desc: 'Rising claw anti-air.', hit: { dmg: 40, multi: 3, status: { bleed: 1 } } }),
    'jS': Mv.dive({ name: 'Pounce', desc: 'Diving tackle.', vx: 1000, vy: 800, hit: { dmg: 85 } }),
  },
  super: Sup.flurry({ name: 'Savage Maul', desc: 'Relentless mauling.', vel: [[8, 30, 400, null]], hit: { dmg: 22, status: { bleed: 1 } } }),
  ult: { act: 'rush', name: 'LUNAR FRENZY', desc: 'A moonlit pounce. On hit: a feeding frenzy.', dmg: 1150, template: 'rush', fx: { el: 'blood', color: '#b0b8c8', sky: ['#050510', '#1a1a3a', '#3a3a6a'], lines: ['The moon is full.', 'And so am I... almost.'] } },
  form: { name: 'FULL MOON BEAST', desc: 'Permanent. Bigger, faster, lifesteal.', scale: 1.2, speed: 1.15, dmg: 1.15, lifesteal: 0.1, model: { animal: { type: 'wolf', color: '#d0d8e8', eye: 'rgba(255,60,60,0.9)' }, aura: '#b0b8c8', tail: '#d0d8e8' } },
  assist: '5S',
  lines: { intro: ['I can smell your fear, {opp}.', 'Bounty says dead or alive. I prefer alive. More fun.', 'Awoooo!'], win: ['Good hunt.', 'Bounty collected.', 'AWOOOO!'], taunt: ['Grrr.', 'Here, kitty.'], form: ['The moon is FULL!'], ult: ['Frenzy!'], ultHit: ['Good boy. Me, I mean.'] },
});
rival('eric', 'fang', [[1, 'Moon boy! Ready to see who the moon REALLY likes?'], [0, "Fang, it's a rock in space. It doesn't like anybody."], [1, "That's exactly what a loser would say."]], { fang: 'Moon picked me. Deal with it.', eric: 'Rock. In space. Doesn\'t pick.' });

fighter({
  id: 'hoshi', name: 'MASTER HOSHI', title: 'The Old Fist', side: 'HERO', role: 'Counters · Stance', color: '#ffe0a0', color2: '#3a2a1a',
  bio: 'A 97-year-old kung fu master who has trained every hero in the city. He is slow, he is grumpy, and he has never lost.',
  quote: 'Back in my day, we fought uphill both ways.', ending: 'Master Hoshi opens a dojo in the ruins. He charges nothing. He accepts payment in tea and silence.',
  hp: 950, walk: 220, scale: 0.92, rival: 'kage',
  model: { build: 'slim', skin: '#e0c0a0', top: '#c8a060', topDark: '#a08040', pants: '#6a4a2a', boots: '#2a2a2a', hair: { type: 'topknot', color: '#e8e8e8' }, sleeves: '#c8a060', weapon: { type: 'staff', color: '#6b4a2a', tip: '#ffe0a0' }, belt: '#c03030' },
  face: { expr: 'calm', eyes: '#5a3a1a', hair: { type: 'topknot', color: '#e8e8e8' }, marks: [{ type: 'cracks', color: '#a08070' }] },
  style: { speed: 0.9, reach: 1.1, weapon: true },
  passive: ['Wisdom', 'Counter hits deal double damage.'],
  passiveDmg(f, t) { return t && t.state === 'move' ? 1.5 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Chi Palm', desc: 'A pulse of chi.', proj: { speed: 700, r: 16, dmg: 60, kind: 'ring', color: '#ffe0a0', trail: false } }),
    '6S': Mv.flurry({ name: 'Hundred Palms', desc: 'Rapid palm strikes.', hits: 8, every: 3, hit: { dmg: 14 }, finisher: { dmg: 50, kb: [500, -300], launch: true } }),
    '2S': Mv.counter({ name: 'Drunken Sway', desc: 'Evasive counter.', window: 30, dmg: 150 }),
    '4S': Mv.rising({ name: 'Crane Rising', desc: 'Invincible rising kick.', hit: { dmg: 45, multi: 3 } }),
    'jS': Mv.dive({ name: 'Falling Crane', desc: 'Flying kick.', hit: { dmg: 80 } }),
  },
  super: Sup.flurry({ name: 'Thousand Fists', desc: 'A lifetime of practice.', hit: { dmg: 22 } }),
  ult: { act: 'rush', name: 'HUNDRED PALM HEAVEN', desc: 'One palm. On hit: a hundred more.', dmg: 1150, template: 'barrage', fx: { el: 'palm', color: '#ffe0a0', sky: ['#1a1008', '#4a3018', '#8a6030'], lines: ['Pay attention, young one.', 'This is a lesson.'] } },
  form: { name: 'AWAKENED YOUTH', desc: 'Permanent. He becomes young again: faster and stronger.', speed: 1.3, dmg: 1.15, scale: 1.1, model: { build: 'athletic', hair: { type: 'topknot', color: '#1a1a1a' }, skin: '#e8c8a0', aura: '#ffe0a0', abs: true } },
  assist: '4S',
  lines: { intro: ['Hmph. Another student who skipped the basics.', 'You remind me of my 43rd apprentice, {opp}. He was bad too.', 'My back hurts. Let\'s make this quick.'], win: ['Again. From the beginning.', 'Too much power, not enough posture.', 'Tea time.'], taunt: ['Hmph.', 'Back in my day...'], form: ['Ahh. I remember this body.'], ult: ['Hundred palms!'], ultHit: ['Lesson over.'] },
});

fighter({
  id: 'mortis', name: 'DR. MORTIS', title: 'The Necromancer', side: 'VILLAIN', role: 'Summoner · Drain', color: '#6aff9a', color2: '#0a140a',
  bio: 'A medical examiner who discovered the dead still have a little work left in them. He calls it "recycling". The city calls it "extremely illegal".',
  quote: 'Death is just a staffing solution.', ending: 'Dr. Mortis solves the city\'s labor shortage with an undead workforce. Unions are furious. The skeletons are thrilled.',
  hp: 950, walk: 240, rival: 'grimm',
  model: { build: 'slim', skin: '#b0c0a8', top: '#1a1a1a', pants: '#1a1a1a', boots: '#0a0a0a', coat: '#e8e8e0', hair: { type: 'slick', color: '#2a2a2a' }, mask: { type: 'glasses', color: '#6aff9a' }, weapon: { type: 'book', color: '#2a3a2a', glow: '#6aff9a' }, emblem: { shape: 'skull', color: '#6aff9a' } },
  face: { expr: 'grin', eyes: '#6aff9a', mask: { type: 'glasses', color: '#6aff9a' }, hair: { type: 'slick', color: '#2a2a2a' } },
  passive: ['Recycling', 'Heals when his minions hit.'],
  moves: {
    '5S': Mv.place({ name: 'Raise Dead', desc: 'Summons a skeleton that walks forward.', spawn: { kind: 'minion', at: 'front', dx: 40, look: 'skeleton', dmg: 55, hp: 60, speed: 220 }, cd: 3 }),
    '6S': Mv.shot({ name: 'Soul Siphon', desc: 'A draining beam of ghosts.', proj: { speed: 800, r: 12, dmg: 55, kind: 'skull', color: '#6aff9a' } }),
    '2S': Mv.place({ name: 'Bone Spikes', desc: 'Ribs burst from the ground.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 80, color: '#eee8d8', fill: '#dcd8c8' } }),
    '4S': Mv.grab({ name: 'Life Drain', desc: 'Grab that drains health.', range: 60, grabData: { anim: 'drain', dmg: 180, frames: 40 } }),
    'jS': Mv.shot({ name: 'Skull Drop', desc: 'Falling skulls.', proj: { speed: 700, r: 12, dmg: 34, count: 3, spread: 0.5, angle: 1, kind: 'skull', color: '#6aff9a' } }),
  },
  super: Sup.place({ name: 'Graveyard Shift', desc: 'Four skeletons march.', spawn: { kind: 'minion', at: 'front', dx: 40, count: 4, spacing: 60, look: 'skeleton', dmg: 50, hp: 60, speed: 260 } }),
  ult: { act: 'strike', name: 'ARMY OF THE DEAD', desc: 'A grave-mark. On hit: the dead rise en masse.', dmg: 1100, template: 'summon', style: 'light', color: '#6aff9a', fx: { el: 'soul', creature: 'army', color: '#6aff9a', sky: ['#000', '#0a140a', '#1a2a1a'], lines: ['Rise, my employees.', 'Overtime.'] } },
  form: { name: 'LICH LORD', desc: 'Permanent. Floating lich: stronger drains, bigger army.', flight: true, dmg: 1.12, lifesteal: 0.1, scale: 1.1, model: { animal: { type: 'skull', color: '#eee8d8', eye: 'rgba(100,255,160,1)' }, hat: { type: 'crown', color: '#6aff9a' }, cape: { color: '#0a140a', len: 1.2 }, aura: '#6aff9a', float: true } },
  assist: '5S',
  lines: { intro: ['Ah, a future employee.', 'Your bones look very... usable, {opp}.', 'I work nights.'], win: ['Welcome to the team.', 'Recycled.', 'Clock in, please.'], taunt: ['Rise!', 'Heh heh.'], form: ['Lich form!'], ult: ['Army of the dead!'], ultHit: ['Overtime is mandatory.'] },
});

fighter({
  id: 'chrome', name: 'CHROME', title: 'The Iron Gunslinger', side: 'ANTI-HERO', role: 'Zoner · Guns', color: '#c0c8d0', color2: '#2a1a0a',
  bio: 'A cyborg bounty hunter from a desert future. His arm is a revolver. His other arm is also a revolver. He has never needed a third arm.',
  quote: 'Draw.', ending: 'Chrome rides off into the sunset. On a motorcycle. That is also a revolver.',
  hp: 980, walk: 260, rival: 'kingpin',
  model: { skin: '#b08a6a', top: '#6a4a2a', pants: '#3a2a1a', boots: '#2a1a0a', coat: '#5a3a1a', hat: { type: 'cowboy', color: '#5a3a1a' }, hair: { type: 'short', color: '#2a1a0a' }, mask: { type: 'eyepatch', color: '#222' }, weapon: { type: 'pistols', color: '#c0c8d0' }, emblem: { shape: 'star', color: '#ffd35a' } },
  face: { expr: 'cold', eyes: '#c04040', hat: { type: 'cowboy', color: '#5a3a1a' }, mask: { type: 'eyepatch', color: '#222' }, marks: [{ type: 'scar', color: '#8a6a5a' }] },
  passive: ['Six Shooter', 'Every sixth shot is a crit.'],
  onHit(a) { a.shots = (a.shots || 0) + 1; },
  passiveDmg(f) { return (f.shots || 0) % 6 === 5 ? 1.8 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Quick Shot', desc: 'Two fast bullets.', s: 8, proj: { speed: 1600, r: 6, dmg: 30, count: 2, spread: 0.04, kind: 'bullet', color: '#ffd35a', life: 1 } }),
    '6S': Mv.shot({ name: 'Ricochet', desc: 'Bounces off the ground.', proj: { speed: 1200, r: 7, dmg: 45, angle: 0.3, g: -600, kind: 'bullet', color: '#ffd35a', life: 1.2 } }),
    '2S': Mv.shot({ name: 'Low Blow', desc: 'Low bullet.', proj: { speed: 1500, r: 6, dmg: 40, kind: 'bullet', color: '#ffd35a', offY: 50, guard: 'low' } }),
    '4S': Mv.teleport({ name: 'Roll Out', desc: 'Dodge roll backwards.', to: 'back' }),
    'jS': Mv.shot({ name: 'Air Barrage', desc: 'Bullets downward.', proj: { speed: 1400, r: 6, dmg: 22, count: 4, spread: 0.4, angle: 0.7, kind: 'bullet', color: '#ffd35a' } }),
  },
  super: Sup.barrage({ name: 'Fan the Hammer', desc: 'Emptying both cylinders.', volleys: 12, proj: { kind: 'bullet', color: '#ffd35a', dmg: 22, speed: 1600, r: 6 } }),
  ult: { act: 'shot', name: 'DEAD EYE', desc: 'One perfect bullet. On hit: time slows, every shot lands.', dmg: 1150, template: 'barrage', proj: { kind: 'bullet', color: '#ffd35a', r: 10, speed: 2200 }, fx: { el: 'bullet', color: '#ffd35a', sky: ['#200a00', '#6a3000', '#e08030'], lines: ['High noon.', 'Draw.'] } },
  form: { name: 'OVERCLOCKED CHASSIS', desc: 'Permanent. Rapid fire: faster shots, armor.', armor: 0.85, dmg: 1.12, projSpeed: 1.2, model: { top: '#8a95a4', coat: '#6a7584', eyes: { glow: '#ff3a3a' }, aura: '#ffd35a' } },
  assist: '5S',
  lines: { intro: ["There's a bounty on your head, {opp}.", 'Draw.', 'I only need one bullet.'], win: ['Bounty collected.', 'Should have drawn faster.', 'Adios.'], taunt: ['Draw.', 'Yeehaw.'], form: ['Overclocked.'], ult: ['High noon.'], ultHit: ['Six for six.'] },
});

fighter({
  id: 'titania', name: 'TITANIA', title: 'The Faerie Queen', side: 'HERO', role: 'Tiny · Evasive', color: '#ff9ad8', color2: '#1a3a1a',
  bio: 'Queen of the faeries, six inches tall and furious about it. She has a tiny hitbox, an enormous ego and a very long memory.',
  quote: 'Do NOT call me cute.', ending: 'Titania plants a forest in the middle of downtown. It grows overnight. Nobody asks permission. Nobody dares.',
  hp: 850, walk: 300, scale: 0.72, floaty: true, jumps: 3, rival: 'blossom',
  model: { build: 'slim', skin: '#f8e0e8', top: '#ff9ad8', pants: '#8ad08a', skirt: '#ffc0e8', boots: '#8ad08a', hair: { type: 'long', color: '#ffe0f8' }, wings: { type: 'fairy', color: '#c0f0ff', scale: 1 }, hat: { type: 'tiara', color: '#ffd35a' }, weapon: { type: 'baton', color: '#ffd35a' }, float: true },
  face: { expr: 'angry', eyes: '#ff5ab8', hat: { type: 'tiara', color: '#ffd35a' }, ears: { type: 'elf', color: '#f8e0e8' } },
  style: { speed: 0.85, power: 0.9 },
  passive: ['Tiny', 'Smaller hitbox; many attacks sail over her.'],
  moves: {
    '5S': Mv.shot({ name: 'Pixie Dust', desc: 'Sparkling homing dust.', proj: { speed: 600, r: 10, dmg: 45, kind: 'star', color: '#ff9ad8', homing: 2.5 } }),
    '6S': Mv.rush({ name: 'Dart', desc: 'Zips forward.', speed: 1500, frames: 10, pass: true, hit: { dmg: 60 } }),
    '2S': Mv.place({ name: 'Thorn Ring', desc: 'Thorny vines erupt under the enemy.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 75, color: '#6aba5a', fill: '#3a7a2a', status: { slow: 1 } } }),
    '4S': Mv.heal({ name: 'Glamour', desc: 'Heals 250.', amount: 250, cd: 15 }),
    'jS': Mv.shot({ name: 'Petal Storm', desc: 'Petals downward.', proj: { speed: 700, r: 10, dmg: 28, count: 4, spread: 0.7, angle: 0.8, kind: 'petal', color: '#ff9ad8', trail: false } }),
  },
  super: Sup.barrage({ name: 'Midsummer Swarm', desc: 'A swarm of pixies.', proj: { kind: 'star', color: '#ff9ad8', dmg: 26, homing: 2 } }),
  ult: { act: 'shot', name: 'SUMMER COURT', desc: 'A royal decree. On hit: the whole forest judges them.', dmg: 1050, template: 'summon', proj: { kind: 'star', color: '#ff9ad8', r: 22 }, fx: { el: 'nature', creature: 'tree', color: '#ff9ad8', sky: ['#0a1a0a', '#2a4a2a', '#8ac08a'], lines: ['Court is in session.', 'The forest finds you GUILTY.'] } },
  form: { name: 'OBERON\'S WRATH', desc: 'Permanent. She grows to full size. No longer tiny, much stronger.', scale: 1.5, dmg: 1.3, armor: 0.9, model: { aura: '#ff9ad8', wings: { type: 'fairy', color: '#ffc0f0', scale: 1.4 }, top: '#c05aa8', hat: { type: 'crown', color: '#ffd35a' } } },
  assist: '5S',
  lines: { intro: ['Kneel before the Faerie Queen, {opp}!', 'Say "cute" one more time. I dare you.', 'I am SIX INCHES OF FURY.'], win: ['Who is cute NOW?', 'Bow.', 'Hmph! Pathetic.'], taunt: ['Tee hee. I mean: GRR.', 'Tiny but mighty!'], form: ['BEHOLD MY TRUE SIZE!'], ult: ['Summer Court!'], ultHit: ['GUILTY!'] },
});

fighter({
  id: 'vulcan', name: 'VULCAN', title: 'The Living Volcano', side: 'VILLAIN', role: 'Brute · Lava', color: '#ff5a1a', color2: '#2a0a00',
  bio: 'A mining foreman who fell into a magma chamber. He climbed out. He is still climbing out, emotionally.',
  quote: 'Everything melts eventually.', ending: 'Vulcan turns the city into a hot spring resort. It is surprisingly popular. He is the only lifeguard.',
  hp: 1150, walk: 220, weight: 0.8, wide: 1.15, rival: 'glacia',
  model: { build: 'heavy', skin: '#3a2a2a', top: '#2a1a1a', pants: '#2a1a1a', boots: '#1a0a0a', hair: { type: 'flame', color: '#ff5a1a' }, core: '#ff5a1a', weapon: { type: 'gauntlet', color: '#3a2a2a', glow: '#ff5a1a' }, eyes: { glow: '#ff8a1a' }, abs: true, stripes: '#ff5a1a' },
  face: { skin: '#4a3a3a', expr: 'angry', eyes: '#ff8a1a', glow: '#ff5a1a', marks: [{ type: 'cracks', color: '#ff5a1a' }] },
  style: { power: 1.2, speed: 1.15, heavy: true },
  passive: ['Molten', 'Attacking him in melee burns the attacker.'],
  onHurt(t, a, dmg, h) { if (a && !a.world && Math.abs(a.x - t.x) < 120 && Math.random() < 0.4) a.status.burn = Math.max(a.status.burn || 0, 2); },
  moves: {
    '5S': Mv.shot({ name: 'Magma Glob', desc: 'Arcing lava that leaves a burning puddle.', proj: { speed: 600, angle: -0.5, g: 1100, r: 16, dmg: 70, kind: 'fire', color: '#ff5a1a', explode: 60, status: { burn: 2 } } }),
    '6S': Mv.rush({ name: 'Eruption Charge', desc: 'Armored molten charge.', speed: 800, frames: 20, armor: [4, 26], hit: { dmg: 110, kb: [700, -300], status: { burn: 2 } } }),
    '2S': Mv.place({ name: 'Lava Vent', desc: 'Lava erupts under the enemy.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 85, color: '#ff5a1a', fill: '#3a1a0a', status: { burn: 2 }, height: 200 } }),
    '4S': Mv.place({ name: 'Magma Pool', desc: 'A burning puddle.', spawn: { kind: 'zone', at: 'front', dx: 150, r: 90, life: 4, every: 0.35, dmg: 14, color: '#ff5a1a', status: { burn: 1 } }, cd: 5 }),
    'jS': Mv.dive({ name: 'Magma Slam', desc: 'Molten body slam.', vx: 300, vy: 1500, hit: { dmg: 110, gb: true, status: { burn: 2 } } }),
  },
  super: Sup.place({ name: 'Pyroclastic Flow', desc: 'Vents erupt in a line.', spawn: { kind: 'spike', at: 'front', dx: 80, delay: 0.1, count: 7, spacing: 80, stagger: 0.07, dmg: 60, color: '#ff5a1a', fill: '#3a1a0a', status: { burn: 2 } } }),
  ult: { act: 'burst', name: 'PYROCLASM', desc: 'Molten explosion. On hit: the volcano erupts onto them.', dmg: 1200, template: 'meteor', fx: { el: 'fire', color: '#ff5a1a', sky: ['#1a0000', '#5a1000', '#c04010'], lines: ['Feel that?', 'That is the earth\'s heartbeat.'] } },
  form: { name: 'MOLTEN CORE', desc: 'Permanent. White-hot: super armor, burn aura.', superArmor: true, dmg: 1.15, armor: 0.85, scale: 1.1, model: { skin: '#5a2a1a', hair: { type: 'flame', color: '#ffe05a' }, core: '#ffe05a', aura: '#ff5a1a', auraSize: 1.3 },
    tick(f) { const o = f.opp; if (o && Math.abs(o.x - f.x) < 180 && f.st % 30 === 0) o.status.burn = 1; } },
  assist: '2S',
  lines: { intro: ['You look flammable, {opp}.', 'Hot enough for you?', 'I climbed out of a volcano. You are nothing.'], win: ['Melted.', 'Cool off.', 'Hot stuff.'], taunt: ['Sizzle.', 'Too hot?'], form: ['MOLTEN CORE!'], ult: ['Pyroclasm!'], ultHit: ['Ash.'] },
});
