// ============================================================
//  MOONKAI — roster part 4 (fighters 50–60)
// ============================================================
fighter({
  id: 'roo', name: 'ROO', title: 'The Outback Brawler', side: 'HERO', role: 'Bouncy · Kicks', color: '#e08a4a', color2: '#3a2a1a',
  bio: 'A kangaroo who escaped a zoo, learned boxing from a TV, and became the most dangerous animal in the southern hemisphere. Which is saying a lot.',
  quote: 'G\'day. Now duck.', ending: 'Roo returns to the Outback as a legend. The other kangaroos build a statue. It is mostly sticks, but it is the thought.',
  hp: 1000, walk: 280, jumps: 3, rival: 'ironjaw',
  model: { build: 'athletic', skin: '#e08a4a', top: '#e08a4a', pants: '#c07a3a', boots: '#8a5a2a', animal: { type: 'roo', color: '#e08a4a' }, bigTail: '#c07a3a', weapon: { type: 'gloves', color: '#ff3a3a' }, glove: '#ff3a3a' },
  face: { animal: { type: 'roo', color: '#e08a4a', eyeColor: '#3a2a1a' } },
  style: { poses: { '5M': 'kick', '5H': 'kick' }, reach: 1.1 },
  passive: ['Spring Legs', 'Triple jump; jump-ins deal extra damage.'],
  passiveDmg(f) { return f.airborne ? 1.15 : 1; },
  moves: {
    '5S': Mv.rush({ name: 'Tail Stand Kick', desc: 'Balances on its tail, double kick.', pose: 'kick', speed: 400, frames: 12, hit: { dmg: 45, multi: 2, every: 6, kb: [600, -200] } }),
    '6S': Mv.rush({ name: 'Hop Punch', desc: 'Bounding punch.', vy: -400, speed: 900, frames: 18, hit: { dmg: 85, kb: [400, -400] } }),
    '2S': Mv.rising({ name: 'Outback Uppercut', desc: 'Leaping uppercut.', hit: { dmg: 50, multi: 2 } }),
    '4S': Mv.shot({ name: 'Boomerang', desc: 'Obviously.', proj: { speed: 800, r: 14, dmg: 55, kind: 'crescent', color: '#c07a3a', boomerang: 0.5, life: 2.5, trail: false } }),
    'jS': Mv.dive({ name: 'Double Stomp', desc: 'Two-footed dive.', vx: 700, vy: 1100, hit: { dmg: 90, kb: [100, -700] } }),
  },
  super: Sup.flurry({ name: 'Joey Jab Flurry', desc: 'A blur of boxing gloves.', hit: { dmg: 22 } }),
  ult: { act: 'grab', name: 'OUTBACK SLAM', desc: 'Grab. On connect: bounced across the Outback.', dmg: 1150, range: 70, template: 'grab', fx: { el: 'metal', color: '#e08a4a', sky: ['#3a1a00', '#aa5a1a', '#f0a050'], lines: ['Crikey.', 'Hold on, mate.'] } },
  form: { name: 'MEGA ROO', desc: 'Permanent. Enormous kangaroo: super armor, huge kicks.', scale: 1.4, superArmor: true, dmg: 1.2, armor: 0.85, heavyLanding: true, model: { skin: '#c05a2a', top: '#c05a2a', animal: { type: 'roo', color: '#c05a2a' }, aura: '#ff8a3a' } },
  assist: '4S',
  lines: { intro: ['G\'day, {opp}. Put \'em up.', 'Watch the tail.', 'Crikey, another one.'], win: ['No worries, mate.', 'Hop off.', 'She\'ll be right.'], taunt: ['Oi!', 'Crikey!'], form: ['MEGA ROO!'], ult: ['Hold on, mate!'], ultHit: ['Fair dinkum.'] },
});

fighter({
  id: 'omega', name: 'OMEGA', title: 'The Final Protocol', side: 'VILLAIN', role: 'Boss · Adaptive', color: '#ff2a2a', color2: '#0a0a0a',
  bio: "Dr. Gear's ultimate creation, built to defeat every hero. It learns. It adapts. It has decided humans are the problem. Classic.",
  quote: 'ANALYSIS COMPLETE. YOU LOSE.', ending: 'Omega defeats every hero, calculates the perfect world, and finds no role for itself in it. It powers down. Gear cries.',
  hp: 1100, walk: 250, rival: 'gear',
  model: { build: 'athletic', skin: '#8a8a9a', top: '#2a2a3a', pants: '#1a1a2a', boots: '#0a0a14', animal: { type: 'robot', color: '#aab', eye: 'rgba(255,40,40,1)' }, pads: { color: '#3a3a4a', size: 1.2 }, emblem: { shape: 'circle', color: '#ff2a2a' }, core: '#ff2a2a', weapon: { type: 'cannon', color: '#3a3a4a', glow: '#ff2a2a' }, stripes: '#ff2a2a' },
  face: { animal: { type: 'robot', color: '#aab', eye: 'rgba(255,40,40,1)' } },
  style: { power: 1.1 },
  passive: ['Adaptation', 'Takes 3% less damage from each repeated hit of the same move (max 30%).'],
  passiveArmor(f, a) { if (!a || !a.move) return 1; f.seen = f.seen || {}; const k = a.move.name; f.seen[k] = (f.seen[k] || 0) + 1; return Math.max(0.7, 1 - f.seen[k] * 0.03); },
  moves: {
    '5S': Mv.shot({ name: 'Plasma Shot', desc: 'Red plasma.', proj: { speed: 900, r: 12, dmg: 60, color: '#ff2a2a' } }),
    '6S': Mv.rush({ name: 'Thruster Dash', desc: 'Rocket-powered strike.', speed: 1300, frames: 14, hit: { dmg: 90 } }),
    '2S': Mv.beam({ name: 'Scan Beam', desc: 'A short targeting laser.', s: 14, beam: { len: 800, width: 26, dur: 20, dmg: 16, color: '#ff2a2a' } }),
    '4S': Mv.place({ name: 'Drone Strike', desc: 'A drone marks and fires.', spawn: { kind: 'strike', at: 'enemy', delay: 0.5, dmg: 80, style: 'light', color: '#ff2a2a' } }),
    'jS': Mv.shot({ name: 'Missile Rain', desc: 'Missiles downward.', proj: { speed: 700, r: 8, dmg: 30, count: 3, spread: 0.5, angle: 0.9, kind: 'missile', color: '#ff2a2a', explode: 30 } }),
  },
  super: Sup.beam({ name: 'Annihilator', desc: 'Chest cannon beam.', beam: { color: '#ff2a2a', dmg: 26 } }),
  ult: { act: 'strike', name: 'DELETION', desc: 'A targeting strike. On hit: orbital deletion.', dmg: 1150, template: 'orbital', style: 'light', color: '#ff2a2a', fx: { el: 'tech', color: '#ff2a2a', sky: ['#000', '#1a0000', '#3a0a0a'], lines: ['TARGET ACQUIRED.', 'DELETING.'] } },
  form: { name: 'OMEGA PROTOCOL', desc: 'TIMED (10s). Overclocked: everything faster and stronger.', timed: 10, cost: 300, dmg: 1.4, speed: 1.25, superArmor: true, scale: 1.15, model: { aura: '#ff2a2a', auraSize: 1.5, top: '#3a0a0a', wings: { type: 'mech', color: '#3a3a4a', scale: 1.1 } } },
  assist: '4S',
  lines: { intro: ['TARGET: {opp}. THREAT LEVEL: LOW.', 'ANALYZING...', 'HUMAN DETECTED.'], win: ['TARGET ELIMINATED.', 'AS CALCULATED.', 'ERROR: OPPONENT NOT FOUND.'], taunt: ['BEEP.', 'PREDICTABLE.'], form: ['OMEGA PROTOCOL ENGAGED.'], ult: ['DELETION.'], ultHit: ['DELETED.'] },
});

fighter({
  id: 'tommy', name: 'TOMMY & BOLTZ', title: 'The Boy and His Robot', side: 'HERO', role: 'Puppet · Combine', color: '#5a9aff', color2: '#1a2a4a',
  bio: 'A ten-year-old genius and the giant robot he built out of junkyard parts. Boltz does the fighting. Tommy does the yelling.',
  quote: 'BOLTZ! PUNCH HIM!', ending: 'Tommy and Boltz win the science fair. Then the Nobel prize. Then they build Boltz a little brother.',
  hp: 1000, walk: 250, scale: 0.85, rival: 'omega',
  model: { build: 'small', skin: '#f0c8a0', top: '#ff8a3a', pants: '#3a5a9a', boots: '#fff', hair: { type: 'spiky', color: '#8a4a1a' }, hat: { type: 'cap', color: '#5a9aff' }, mask: { type: 'goggles', color: '#5a3a1a', lens: '#9ff' }, weapon: { type: 'wrench', color: '#aab' } },
  face: { expr: 'shout', eyes: '#5a9aff', hat: { type: 'cap', color: '#5a9aff' } },
  passive: ['Boltz', 'Boltz fights alongside him: 5S, 6S and 2S are robot attacks from a distance.'],
  moves: {
    '5S': Mv.place({ name: 'Boltz Punch!', desc: 'The robot charges in and punches.', spawn: { kind: 'minion', at: 'front', dx: 20, look: 'bot', dmg: 70, hp: 120, speed: 420 }, cd: 2 }),
    '6S': Mv.shot({ name: 'Rocket Fist', desc: 'Boltz fires its fist.', proj: { speed: 900, r: 16, dmg: 70, kind: 'gear', color: '#aab', prio: 2 } }),
    '2S': Mv.place({ name: 'Boltz Stomp', desc: 'Boltz lands on the enemy.', spawn: { kind: 'strike', at: 'enemy', delay: 0.55, dmg: 90, style: 'anvil', color: '#5a9aff' } }),
    '4S': Mv.place({ name: 'Scrap Wall', desc: 'A junk wall.', spawn: { kind: 'wall', at: 'front', dx: 70, w: 44, hgt: 130, hp: 220, life: 4, colors: ['#888', '#555'], color: '#6a6a7a' }, cd: 6 }),
    'jS': Mv.shot({ name: 'Bolt Toss', desc: 'Throws bolts.', proj: { speed: 700, r: 8, dmg: 26, count: 3, spread: 0.5, angle: 0.8, kind: 'gear', color: '#aab' } }),
  },
  super: Sup.place({ name: 'Scrap Army', desc: 'Three little bots.', spawn: { kind: 'minion', at: 'front', dx: 20, count: 3, spacing: 60, look: 'bot', dmg: 55, hp: 80, speed: 380 } }),
  ult: { act: 'shot', name: 'ROCKET PUNCH OMEGA', desc: 'A giant rocket fist. On hit: Boltz goes FULL POWER.', dmg: 1100, template: 'megabeam', proj: { kind: 'gear', color: '#5a9aff', r: 26 }, fx: { el: 'tech', color: '#5a9aff', sky: ['#050a1a', '#1a2a4a', '#3a5a9a'], lines: ['BOLTZ! FULL POWER!', 'ROCKET PUNCH!'] } },
  form: { name: 'COMBINE', desc: 'TIMED (12s). Tommy climbs inside Boltz: a giant mech.', timed: 12, cost: 300, scale: 1.7, speed: 0.85, armor: 0.65, dmg: 1.35, superArmor: true, heavyLanding: true, model: { body: drawMech, metal: '#5a9aff', accent: '#ff8a3a', skin: '#f0c8a0' } },
  assist: '5S',
  lines: { intro: ['BOLTZ, TARGET {opp}!', 'My robot can beat up your robot! Oh, you don\'t have one.', 'Mom said I can be out until nine.'], win: ['WE DID IT, BOLTZ!', 'Science wins!', 'Beep boop! That means "you lose".'], taunt: ['Nyeh!', 'BOLTZ!'], form: ['COMBINE!'], ult: ['ROCKET PUNCH!'], ultHit: ['That\'s going in my science fair!'] },
});

fighter({
  id: 'rose', name: 'MADAME ROSE', title: 'The Crimson Countess', side: 'VILLAIN', role: 'Drain · Mist', color: '#c01030', color2: '#1a0008',
  bio: 'A vampire aristocrat who has hosted the same ball every night for three hundred years. She finds the modern world vulgar and delicious.',
  quote: 'May I have this dance?', ending: 'Madame Rose turns the ruined city into her ballroom. Every night there is dancing. Some guests leave. Most don\'t.',
  hp: 950, walk: 270, floaty: true, rival: 'fang',
  model: { build: 'curvy', skin: '#f0e0e8', top: '#6a0a1a', pants: '#3a0010', skirt: '#8a0a2a', boots: '#1a0008', hair: { type: 'long', color: '#1a0008' }, cape: { color: '#1a0008', inner: '#c01030' }, emblem: { shape: 'drop', color: '#c01030' }, weapon: { type: 'fan', color: '#c01030' }, eyes: { glow: '#ff2040' } },
  face: { expr: 'smirk', eyes: '#ff2040', glow: '#c01030', hair: { type: 'long', color: '#1a0008' } },
  passive: ['Blood Thirst', 'Lifesteal 10% on all hits.'],
  onHit(a, t, dmg) { a.hp = Math.min(a.maxHp, a.hp + dmg * 0.1); },
  moves: {
    '5S': Mv.shot({ name: 'Bat Swarm', desc: 'Homing bats.', proj: { speed: 600, r: 10, dmg: 32, count: 3, spread: 0.4, homing: 2, kind: 'bat', color: '#1a0a14', trail: false } }),
    '6S': Mv.teleport({ name: 'Mist Form', desc: 'Dissolves into mist and strikes behind.', to: 'behind', hit: { dmg: 80 } }),
    '2S': Mv.grab({ name: 'Kiss of Death', desc: 'Draining bite.', range: 56, grabData: { anim: 'drain', dmg: 200, frames: 40 } }),
    '4S': Mv.place({ name: 'Blood Pool', desc: 'A pool of blood that drains.', spawn: { kind: 'zone', at: 'enemy', r: 100, life: 3, every: 0.4, dmg: 14, color: '#c01030', status: { bleed: 1 } }, cd: 6 }),
    'jS': Mv.dive({ name: 'Swoop', desc: 'Bat-wing dive.', vx: 900, vy: 700, hit: { dmg: 80 } }),
  },
  super: Sup.barrage({ name: 'Nocturne', desc: 'A storm of bats.', proj: { kind: 'bat', color: '#1a0a14', dmg: 24, homing: 2, speed: 700 } }),
  ult: { act: 'grab', name: 'CRIMSON BALLROOM', desc: 'A dance. On connect: the eternal ball, and a final bite.', dmg: 1150, range: 70, template: 'dimension', fx: { el: 'blood', world: 'ballroom', color: '#c01030', sky: ['#050000', '#2a0008', '#5a0018'], lines: ['Shall we dance?', 'Forever.'] } },
  form: { name: 'COUNTESS UNBOUND', desc: 'Permanent. Bat wings, flight, lifesteal doubled.', flight: true, lifesteal: 0.1, dmg: 1.12, model: { wings: { type: 'bat', color: '#1a0008', scale: 1.2 }, aura: '#c01030', hair: { type: 'wild', color: '#3a0010' } } },
  assist: '5S',
  lines: { intro: ['Welcome to my ball, {opp}.', 'Your neck is... charming.', 'The night is young. So are you. For now.'], win: ['Delicious.', 'The dance is over.', 'Stay for dinner. As dinner.'], taunt: ['Hmhm.', 'Charming.'], form: ['Unbound!'], ult: ['Dance with me.'], ultHit: ['Exquisite.'] },
});
rival('fang', 'rose', [[1, 'The dog is back. Did you bring your leash?'], [0, 'Countess. You still owe the town six hundred bodies.'], [1, 'Such a boring accountant.']], { fang: 'Bounty collected. Finally.', rose: 'Bad dog.' });

fighter({
  id: 'cosmo', name: 'COSMO', title: 'The Star Voyager', side: 'HERO', role: 'Zero-G · Zoner', color: '#8ac8ff', color2: '#0a0a2a',
  bio: 'An astronaut who drifted past the edge of the solar system and came back with the stars inside her. She floats, she shines and she is very tired of Earth gravity.',
  quote: 'Houston, we have a problem. It\'s you.', ending: 'Cosmo builds the first space station for superheroes. It is mostly a lounge. The view is incredible.',
  hp: 950, walk: 250, floaty: true, jumps: 3, rival: 'onyx',
  model: { skin: '#e0c0a0', top: '#f0f0f8', pants: '#e0e0e8', boots: '#aab', belt: '#ff8a3a', hair: { type: 'ponytail', color: '#3a2a1a' }, hat: { type: 'astronaut', color: '#ddd' }, emblem: { shape: 'star', color: '#ff8a3a' }, pads: { color: '#ff8a3a' } },
  face: { expr: 'smirk', eyes: '#3a6ad8', hat: { type: 'astronaut', color: '#ddd' } },
  passive: ['Zero-G', 'Floaty jumps; air specials cost nothing to recover from.'],
  moves: {
    '5S': Mv.shot({ name: 'Star Shot', desc: 'A spinning star.', proj: { speed: 800, r: 12, dmg: 55, kind: 'star', color: '#ffe08a' } }),
    '6S': Mv.rush({ name: 'Comet Dash', desc: 'Blazing comet tackle.', speed: 1400, frames: 12, hit: { dmg: 85 } }),
    '2S': Mv.place({ name: 'Satellite', desc: 'A satellite that fires down.', spawn: { kind: 'turret', at: 'front', dx: 120, life: 6, hp: 120, shotDmg: 20, color: '#8ac8ff', body: '#ccd', limit: 1 }, cd: 6 }),
    '4S': Mv.place({ name: 'Gravity Anomaly', desc: 'A small black hole.', spawn: { kind: 'blackhole', at: 'front', dx: 250, r: 240, life: 1.6, dmg: 12 }, cd: 5 }),
    'jS': Mv.shot({ name: 'Meteor Shower', desc: 'Small meteors down.', proj: { speed: 900, r: 10, dmg: 30, count: 4, spread: 0.6, angle: 0.9, kind: 'rock', color: '#8a7a6a', trail: false } }),
  },
  super: Sup.beam({ name: 'Nebula Beam', desc: 'A beam of starlight.', beam: { color: '#8ac8ff', dmg: 24 } }),
  ult: { act: 'beam', name: 'BIG BANG', desc: 'A cosmic beam. On hit: the birth of a universe.', dmg: 1150, template: 'megabeam', beam: { color: '#8ac8ff' }, fx: { el: 'star', color: '#8ac8ff', sky: ['#000', '#0a0a2a', '#2a1a5a'], lines: ['In the beginning...', 'BANG.'] } },
  form: { name: 'STAR VOYAGER', desc: 'Permanent. Starlight body: flight and stronger stars.', flight: true, dmg: 1.12, model: { top: '#1a1a4a', pants: '#1a1a3a', aura: '#8ac8ff', eyes: { glow: '#fff' }, hat: null } },
  assist: '2S',
  lines: { intro: ['Ground control to {opp}...', 'I\'ve seen stars die. You\'re nothing.', 'Gravity is so heavy here.'], win: ['One small step for me...', 'Mission complete.', 'Back to orbit.'], taunt: ['Houston?', 'Weee!'], form: ['Star voyager!'], ult: ['Big bang!'], ultHit: ['A new universe.'] },
});

fighter({
  id: 'leo', name: 'LEO', title: 'The Beast King', side: 'HERO', role: 'Rushdown · Roar', color: '#ffb02a', color2: '#3a1a0a',
  bio: 'King of a hidden savanna kingdom of beast-folk. He came to the city to find the poacher who took his cub. He found a lot more than that.',
  quote: 'Hear me ROAR.', ending: 'Leo finds his cub, safe, raised by Seraph. He is furious. Then grateful. Then he knights her.',
  hp: 1050, walk: 300, rival: 'rex',
  model: { build: 'athletic', skin: '#d0a050', top: '#8a2a1a', pants: '#5a3a1a', boots: '#3a2a1a', animal: { type: 'lion', color: '#d0a050', mane: '#8a4a1a' }, tail: '#d0a050', weapon: { type: 'claws', color: '#eee' }, cape: { color: '#8a2a1a', inner: '#ffd35a' }, hat: { type: 'crown', color: '#ffd35a' } },
  face: { animal: { type: 'lion', color: '#d0a050', mane: '#8a4a1a', eyeColor: '#ffd35a' } },
  style: { speed: 0.9, power: 1.05 },
  passive: ['Pride', 'Gains power when above 50% health.'],
  passiveDmg(f) { return f.hp > f.maxHp / 2 ? 1.12 : 1; },
  moves: {
    '5S': Mv.custom({ name: 'Kingly Roar', desc: 'A roar that pushes and stuns.', pose: 'charge', s: 16, a: 10, r: 22, hit: { dmg: 40, box: [0, -150, 200, 150], stun: 0.6, kb: [500, 0], hs: 14 }, ai: { min: 0, max: 180, use: 'combo' } }),
    '6S': Mv.rush({ name: 'Pounce', desc: 'Leaping pounce.', vy: -400, speed: 1100, frames: 18, hit: { dmg: 95, kb: [400, -400] } }),
    '2S': Mv.flurry({ name: 'Maul', desc: 'Claw flurry.', hits: 6, every: 4, hit: { dmg: 18 }, finisher: { dmg: 50, kb: [600, -400], launch: true } }),
    '4S': Mv.place({ name: 'Call the Pride', desc: 'A lioness charges in.', spawn: { kind: 'minion', at: 'front', dx: 30, look: 'lion', dmg: 70, hp: 90, speed: 450 }, cd: 5 }),
    'jS': Mv.dive({ name: 'Lion Dive', desc: 'Diving claw.', hit: { dmg: 85 } }),
  },
  super: Sup.flurry({ name: 'Savage King', desc: 'A royal mauling.', vel: [[8, 30, 300, null]], hit: { dmg: 24 } }),
  ult: { act: 'rush', name: 'KING\'S ROAR', desc: 'A royal charge. On hit: the whole pride answers.', dmg: 1150, template: 'summon', fx: { el: 'lions', creature: 'lions', color: '#ffb02a', sky: ['#2a0a00', '#8a4a10', '#e0a040'], lines: ['My pride...', 'ATTACK!'] } },
  form: { name: 'PRIDE LORD', desc: 'Permanent. Golden mane, more damage and speed.', dmg: 1.15, speed: 1.1, scale: 1.12, model: { animal: { type: 'lion', color: '#e0b060', mane: '#ffd35a' }, aura: '#ffb02a', cape: { color: '#ffd35a', inner: '#8a2a1a' } } },
  assist: '4S',
  lines: { intro: ['Bow to the king, {opp}.', 'Where is my cub?!', 'ROOOAR!'], win: ['The king stands.', 'Long live the king.', 'ROAR!'], taunt: ['Grr!', 'Bow!'], form: ['Pride lord!'], ult: ['My pride!'], ultHit: ['The king has spoken.'] },
});
rival('leo', 'rex', [[1, 'A CAT. I USED TO EAT CATS.'], [0, 'You used to be extinct. Let me help.'], [1, 'ROOOAR!'], [0, 'ROOOAAR!']], { leo: 'Back to the fossil record.', rex: 'SMALL KING. BIG LOSER.' });

fighter({
  id: 'detonator', name: 'DETONATOR', title: 'The Demolition Man', side: 'VILLAIN', role: 'Setup · Bombs', color: '#ffd02a', color2: '#2a1a0a',
  bio: 'A demolition expert fired for "excessive enthusiasm". He places explosives. He waits. He presses the button. He LOVES pressing the button.',
  quote: 'Tick... tick... BOOM.', ending: 'Detonator is hired to demolish the ruined city for rebuilding. He does it in one enormous explosion. He cries tears of joy.',
  hp: 1000, walk: 240, rival: 'blitz',
  model: { build: 'heavy', skin: '#c89a70', top: '#ffd02a', pants: '#3a3a3a', boots: '#2a2a2a', belt: '#1a1a1a', hair: { type: 'mohawk', color: '#ff5a1a' }, hat: { type: 'cap', color: '#ffd02a' }, mask: { type: 'goggles', color: '#1a1a1a', lens: '#ff5a1a' }, emblem: { shape: 'skull', color: '#1a1a1a' }, stripes: '#1a1a1a' },
  face: { expr: 'grin', eyes: '#ff5a1a', hat: { type: 'cap', color: '#ffd02a' }, mask: { type: 'goggles', color: '#1a1a1a', lens: '#ff5a1a' } },
  passive: ['Chain Reaction', 'Explosions near other explosions deal 25% more damage.'],
  moves: {
    '5S': Mv.shot({ name: 'Grenade', desc: 'Bouncing grenade.', proj: { speed: 600, angle: -0.4, g: 1000, r: 10, dmg: 70, kind: 'bomb', color: '#ffd02a', explode: 90 } }),
    '6S': Mv.place({ name: 'Sticky Bomb', desc: 'A mine that waits.', spawn: { kind: 'mine', at: 'front', dx: 180, dmg: 110, radius: 100, color: '#ffd02a', limit: 3 }, cd: 2 }),
    '2S': Mv.place({ name: 'Detonate', desc: 'Blows up every bomb he has placed.', s: 10, spawn: { kind: 'zone', at: 'self', r: 1, life: 0.1 } }),
    '4S': Mv.shot({ name: 'Dynamite Roll', desc: 'Rolling dynamite, low.', proj: { speed: 500, r: 10, dmg: 60, kind: 'bomb', color: '#c01010', offY: 70, guard: 'low', explode: 70 } }),
    'jS': Mv.shot({ name: 'Bomb Drop', desc: 'Drops a bomb.', proj: { speed: 200, angle: 1.4, g: 1400, r: 12, dmg: 70, kind: 'bomb', color: '#ffd02a', explode: 100 } }),
  },
  super: Sup.place({ name: 'Minefield', desc: 'Five mines across the floor.', spawn: { kind: 'mine', at: 'enemy', count: 5, spacing: 90, dmg: 90, radius: 90, color: '#ffd02a' } }),
  ult: { act: 'shot', name: 'CHAIN REACTION', desc: 'A big red button. On hit: everything explodes.', dmg: 1200, template: 'meteor', proj: { kind: 'bomb', color: '#ffd02a', r: 22 }, fx: { el: 'fire', color: '#ffd02a', sky: ['#1a0a00', '#6a2a00', '#ffa020'], lines: ['Three...', 'BOOM.'] } },
  form: { name: 'NUCLEAR', desc: 'Permanent. Radioactive: bigger explosions, burn aura.', dmg: 1.15, armor: 0.9, model: { top: '#8aff3a', aura: '#8aff3a', mask: { type: 'goggles', color: '#1a1a1a', lens: '#8aff3a' } } },
  assist: '5S',
  lines: { intro: ['Hold this, {opp}. Don\'t drop it.', 'I love the smell of C4 in the morning.', 'Tick tock.'], win: ['BOOM! Hahaha!', 'Beautiful explosion.', 'Kaboom.'], taunt: ['Tick tock.', 'Hehehe!'], form: ['NUCLEAR!'], ult: ['Big red button!'], ultHit: ['BOOOOOM!'] },
});
charById('detonator').moves['2S'].ev = { 10: f => { for (const h of Combat.hazards.filter(h => h.owner === f && h.kind === 'mine')) { Combat.explode(h.x, -16, (h.radius || 90) * 1.2, f, (h.dmg || 90) * 1.25, '#ffd02a'); h.life = 0; } Sfx.boom(); } };

fighter({
  id: 'astra', name: 'ASTRA', title: 'The Star Valkyrie', side: 'HERO', role: 'Constellations · Setups', color: '#b0c8ff', color2: '#0a0a2a',
  bio: 'A valkyrie who carries fallen heroes to the stars. She came down to Earth because too many heroes were falling. She intends to stop it personally.',
  quote: 'Not today.', ending: 'Astra carries no heroes to the stars this year. It is the first time in a thousand years. She takes a vacation.',
  hp: 1000, walk: 260, rival: 'grimm',
  model: { build: 'athletic', skin: '#f0d8c0', top: '#b0c8ff', topDark: '#7a90c8', pants: '#3a4a7a', boots: '#b0c8ff', skirt: '#3a4a7a', hair: { type: 'long', color: '#fff0c0' }, hat: { type: 'kabuto', color: '#b0c8ff', accent: '#fff' }, wings: { type: 'feather', color: '#e0e8ff', scale: 0.8 }, weapon: { type: 'spear', color: '#b0c8ff', tip: '#fff' }, emblem: { shape: 'star', color: '#fff' } },
  face: { expr: 'calm', eyes: '#6a8aff', hat: { type: 'kabuto', color: '#b0c8ff', accent: '#fff' } },
  style: { weapon: true, reach: 1.2 },
  passive: ['Constellation', 'Her stars linger; hitting an enemy near one deals bonus damage.'],
  moves: {
    '5S': Mv.shot({ name: 'Star Spear', desc: 'A thrown star-spear.', proj: { speed: 1100, r: 10, dmg: 65, kind: 'spear', color: '#b0c8ff', trail: false } }),
    '6S': Mv.rush({ name: 'Valkyrie Charge', desc: 'Winged spear charge.', speed: 1100, frames: 16, hit: { dmg: 95, kb: [600, -300] } }),
    '2S': Mv.place({ name: 'Star Mine', desc: 'A star that explodes when touched.', spawn: { kind: 'mine', at: 'front', dx: 180, dmg: 90, color: '#b0c8ff', body: '#fff', limit: 3 }, cd: 2 }),
    '4S': Mv.rising({ name: 'Ascension', desc: 'Rising spear arc.', hit: { dmg: 45, multi: 3 } }),
    'jS': Mv.shot({ name: 'Starfall', desc: 'Stars rain down.', proj: { speed: 900, r: 11, dmg: 32, count: 3, spread: 0.5, angle: 0.9, kind: 'star', color: '#b0c8ff' } }),
  },
  super: Sup.place({ name: 'Constellation', desc: 'Five falling stars linked by light.', spawn: { kind: 'strike', at: 'enemy', delay: 0.35, count: 5, spacing: 90, stagger: 0.1, dmg: 65, style: 'meteor', color: '#b0c8ff' } }),
  ult: { act: 'strike', name: 'STARFALL', desc: 'A falling star. On hit: the whole sky falls.', dmg: 1150, template: 'storm', style: 'meteor', color: '#b0c8ff', fx: { el: 'star', color: '#b0c8ff', sky: ['#000', '#0a0a2a', '#1a2a5a'], lines: ['The stars remember...', 'Every hero who fell.'] } },
  form: { name: 'CONSTELLATION ARMOR', desc: 'Permanent. Star armor, full wings, flight.', flight: true, armor: 0.85, dmg: 1.12, model: { wings: { type: 'light', color: '#e0e8ff', scale: 1.3 }, aura: '#b0c8ff', top: '#e0e8ff' } },
  assist: '5S',
  lines: { intro: ['You will not fall today, {opp}. You will LOSE.', 'Not today.', 'The stars are watching.'], win: ['Rest. Not forever.', 'Not today.', 'The sky is quiet.'], taunt: ['Hah!', 'Valhalla awaits.'], form: ['Constellation armor!'], ult: ['Starfall!'], ultHit: ['Not today.'] },
});

fighter({
  id: 'warden', name: 'WARDEN', title: 'The Iron Jailer', side: 'VILLAIN', role: 'Grappler · Chains', color: '#8a8a9a', color2: '#1a1a1a',
  bio: 'The warden of a supervillain prison that no one has ever escaped. Until last week. Everyone escaped. He is VERY upset.',
  quote: 'Back in your cell.', ending: 'Warden recaptures every escaped villain and builds a bigger prison. He locks himself in, just to be sure it works.',
  hp: 1150, walk: 220, weight: 0.8, wide: 1.15, rival: 'titan',
  model: { build: 'giant', skin: '#a08070', top: '#3a3a4a', pants: '#2a2a3a', boots: '#1a1a1a', belt: '#ffd35a', hair: { type: 'helmet', color: '#4a4a5a', visor: '#ff5a1a' }, pads: { color: '#5a5a6a', size: 1.5 }, weapon: { type: 'chain', color: '#999' }, emblem: { shape: 'skull', color: '#ffd35a' } },
  face: { expr: 'angry', eyes: '#ff5a1a', hair: { type: 'helmet', color: '#4a4a5a', visor: '#ff5a1a' } },
  style: { power: 1.2, speed: 1.15, reach: 1.2, heavy: true },
  passive: ['Lockdown', 'Stunned or snared enemies take 25% more damage.'],
  passiveDmg(f, t) { return t && (t.status.stun || t.status.slow) ? 1.25 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Chain Hook', desc: 'Drags the enemy in.', proj: { speed: 1000, r: 12, dmg: 50, kind: 'hook', color: '#999', trail: false, life: 0.8, pull: true, hs: 32 } }),
    '6S': Mv.grab({ name: 'Cell Slam', desc: 'Command grab slam.', range: 70, grabData: { anim: 'slam', dmg: 220 } }),
    '2S': Mv.place({ name: 'Shackles', desc: 'Chains snare the enemy.', spawn: { kind: 'trap', at: 'enemy', color: '#999', stun: 1.3, dmg: 40 }, cd: 5 }),
    '4S': Mv.rush({ name: 'Riot Charge', desc: 'Shield-bash charge.', speed: 800, frames: 20, armor: [4, 28], hit: { dmg: 110, kb: [700, -200], wb: true } }),
    'jS': Mv.dive({ name: 'Iron Drop', desc: 'Crushing drop.', vx: 300, vy: 1500, hit: { dmg: 110, gb: true } }),
  },
  super: Sup.grab({ name: 'Maximum Security', desc: 'Chained spin throw.', range: 90, grabData: { anim: 'spin', dmg: 420 } }),
  ult: { act: 'grab', name: 'SOLITARY', desc: 'A chain grab. On connect: solitary confinement, forever.', dmg: 1200, range: 100, template: 'grab', fx: { el: 'metal', color: '#8a8a9a', sky: ['#050505', '#1a1a1a', '#3a3a3a'], lines: ['You have the right to remain silent.', 'FOREVER.'] } },
  form: { name: 'LOCKDOWN', desc: 'Permanent. Riot armor: super armor, longer grabs.', superArmor: true, armor: 0.8, dmg: 1.12, scale: 1.08, model: { top: '#1a1a2a', pads: { color: '#ffd35a', size: 1.6, spikes: '#999' }, aura: '#ff5a1a' } },
  assist: '2S',
  lines: { intro: ['Inmate {opp}. Back in your cell.', 'Nobody escapes. NOBODY.', 'Lights out.'], win: ['Locked up.', 'Life sentence.', 'Lights out.'], taunt: ['Lockdown.', 'Hmph.'], form: ['LOCKDOWN!'], ult: ['Solitary.'], ultHit: ['Forever.'] },
});

fighter({
  id: 'brulee', name: 'CHEF BRULEE', title: 'The Master Chef', side: 'ANTI-HERO', role: 'Buffs · Food', color: '#ffe0a0', color2: '#3a2a1a',
  bio: 'A world-famous chef who only takes one critic seriously: himself. He fights villains because they keep destroying his restaurants.',
  quote: 'Bon appétit!', ending: 'Chef Brulee opens a restaurant in the ruins. Heroes and villains eat together. The food is so good nobody fights.',
  hp: 1050, walk: 240, rival: 'kingpin',
  model: { build: 'heavy', skin: '#f0c8a0', top: '#fff', topDark: '#ddd', pants: '#1a1a1a', boots: '#1a1a1a', hair: { type: 'short', color: '#3a2a1a' }, hat: { type: 'chef', color: '#fff' }, weapon: { type: 'pan' }, emblem: { shape: 'circle', color: '#c01010' }, scarf: { color: '#c01010' } },
  face: { expr: 'grin', eyes: '#3a2a1a', hat: { type: 'chef', color: '#fff' }, marks: [{ type: 'paint', color: '#3a2a1a' }] },
  style: { power: 1.05 },
  passive: ['Taste Test', 'Heals a little every time he lands a special.'],
  onHit(a, t, dmg, h) { if (a.move && a.move.kind === 'special') a.hp = Math.min(a.maxHp, a.hp + 12); },
  moves: {
    '5S': Mv.shot({ name: 'Knife Toss', desc: 'Three kitchen knives.', proj: { speed: 1000, r: 7, dmg: 28, count: 3, spread: 0.15, kind: 'knife', color: '#aaa', trail: false } }),
    '6S': Mv.counter({ name: 'Frying Pan Parry', desc: 'PANG! Counter.', window: 24, dmg: 130 }),
    '2S': Mv.heal({ name: 'Snack Break', desc: 'Eats a croissant. Heals 220.', amount: 220, cd: 14 }),
    '4S': Mv.shot({ name: 'Hot Sauce', desc: 'Burning sauce blob.', proj: { speed: 600, angle: -0.4, g: 900, r: 12, dmg: 55, kind: 'fire', color: '#ff3a1a', status: { burn: 3 }, explode: 60 } }),
    'jS': Mv.shot({ name: 'Flour Bomb', desc: 'Blinding flour downward.', proj: { speed: 400, angle: 1.2, g: 900, r: 14, dmg: 45, kind: 'food', color: '#fff', explode: 80, stun: 0.4 } }),
  },
  super: Sup.barrage({ name: 'Buffet', desc: 'Throws the whole kitchen.', proj: { kind: 'food', color: '#ffb02a', dmg: 26, g: 400 } }),
  ult: { act: 'rush', name: 'KITCHEN NIGHTMARE', desc: 'A pan to the face. On hit: the full ten-course menu.', dmg: 1100, template: 'barrage', fx: { el: 'food', color: '#ffe0a0', sky: ['#1a0a00', '#5a3a1a', '#c08a4a'], lines: ['Tonight\'s special...', 'IS YOU.'] } },
  form: { name: 'MASTER CHEF', desc: 'Permanent. Tall hat: every hit burns, more healing.', dmg: 1.12, regen: 1, model: { hat: { type: 'chef', color: '#ffd35a' }, aura: '#ffe0a0', top: '#fff8e0' } },
  onHurt() { },
  assist: '4S',
  lines: { intro: ['You call that seasoning, {opp}?', 'Kitchen\'s open!', 'Yes, chef!'], win: ['Magnifique!', 'Bon appétit!', 'Needs salt.'], taunt: ['Delicious!', 'Hmm, bland.'], form: ['MASTER CHEF!'], ult: ['Tonight\'s special!'], ultHit: ['Chef\'s kiss.'] },
});

fighter({
  id: 'beat', name: 'BEAT', title: 'The Bass Drop', side: 'ANTI-HERO', role: 'Rhythm · Tempo', color: '#5affe0', color2: '#0a0a1a',
  bio: 'An underground DJ whose beats are so heavy they have mass. Fight to his rhythm and you win. Fight off-beat and you are dead.',
  quote: 'Feel the drop.', ending: 'Beat throws the biggest party the city has ever seen, in the crater where downtown used to be. The bass is still echoing.',
  hp: 950, walk: 280, rival: 'nova',
  model: { build: 'slim', skin: '#a07a60', top: '#1a1a2a', pants: '#2a2a3a', boots: '#5affe0', hair: { type: 'afro', color: '#1a1a1a' }, mask: { type: 'shades', color: '#111' }, emblem: { shape: 'note', color: '#5affe0' }, stripes: '#5affe0', weapon: { type: 'guitar', color: '#5affe0' } },
  face: { expr: 'grin', eyes: '#5affe0', mask: { type: 'shades', color: '#111' }, hair: { type: 'afro', color: '#1a1a1a' } },
  passive: ['On Beat', 'Attacks timed on the beat (every 0.5s pulse) deal 30% more damage.'],
  passiveDmg(f) { return Game.battle && Game.battle.frame % 30 < 8 ? 1.3 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Bass Wave', desc: 'A thumping sound ring.', proj: { speed: 700, r: 18, dmg: 55, kind: 'ring', color: '#5affe0', kb: [500, -40], trail: false } }),
    '6S': Mv.flurry({ name: 'Breakdance', desc: 'Spinning windmill kicks.', pose: 'sweep', hits: 6, every: 4, vel: [[4, 26, 300, null]], hit: { dmg: 18, guard: 'low' }, finisher: { dmg: 40, kb: [500, -400], launch: true } }),
    '2S': Mv.place({ name: 'Subwoofer', desc: 'A speaker that pulses damage.', spawn: { kind: 'zone', at: 'front', dx: 180, r: 110, life: 4, every: 0.5, dmg: 16, color: '#5affe0' }, cd: 6 }),
    '4S': Mv.buff({ name: 'Tempo Up', desc: 'Faster for 4s.', effects: { haste: true }, dur: 4, cd: 10 }),
    'jS': Mv.shot({ name: 'Drop', desc: 'A bass wave downward.', proj: { speed: 800, r: 18, dmg: 50, angle: 1.0, kind: 'ring', color: '#5affe0', trail: false } }),
  },
  super: Sup.beam({ name: 'Wall of Sound', desc: 'A massive speaker blast.', beam: { color: '#5affe0', dmg: 24, width: 90 } }),
  ult: { act: 'burst', name: 'THE DROP', desc: 'A bass pulse. On hit: the ultimate drop.', dmg: 1100, template: 'barrage', fx: { el: 'note', color: '#5affe0', sky: ['#000', '#0a1a1a', '#1a3a3a'], lines: ['Wait for it...', 'DROP!'] } },
  form: { name: 'DROP THE BASS', desc: 'Permanent. The whole stage pulses: more damage on beat.', dmg: 1.12, speed: 1.08, model: { aura: '#5affe0', top: '#0a3a3a', mask: { type: 'shades', color: '#5affe0' } } },
  assist: '2S',
  lines: { intro: ['You got rhythm, {opp}?', 'One, two, one two three four!', 'Feel the bass.'], win: ['Dropped.', 'That\'s a banger.', 'Off-beat. Tragic.'], taunt: ['Untz untz.', 'Yeah!'], form: ['Drop the bass!'], ult: ['Wait for it...'], ultHit: ['DROP!'] },
});
rival('beat', 'nova', [[0, 'Pop star.'], [1, 'Underground guy.'], [0, 'Your music has no bass.'], [1, 'Your music has no WORDS.']], { beat: 'Now THAT was a remix.', nova: 'Sold out. Unlike you.' });
