// ============================================================
//  MOONKAI — roster part 3 (fighters 35–49)
// ============================================================
fighter({
  id: 'spectre', name: 'SPECTRE', title: 'The Ghost Detective', side: 'HERO', role: 'Phasing · Mixups', color: '#aac0ff', color2: '#141a2a',
  bio: 'A detective murdered on his last case. He refused to pass on until he solved it. That was sixty years ago. He is very close now.',
  quote: 'The case isn\'t closed until I say so.', ending: 'Spectre finally solves his own murder. The culprit was his partner. He haunts him lovingly, forever.',
  hp: 930, walk: 270, floaty: true, rival: 'mortis',
  model: { skin: '#c8d8f0', top: '#6a7a9a', pants: '#4a5a7a', boots: '#3a4a6a', coat: '#7a8aaa', hat: { type: 'cowboy', color: '#4a5a7a' }, hair: { type: 'short', color: '#8a9aba' }, eyes: { glow: '#aac0ff' }, ghost: true, alpha: 0.85 },
  face: { expr: 'cold', eyes: '#aac0ff', glow: '#aac0ff', skin: '#c8d8f0', hat: { type: 'cowboy', color: '#4a5a7a' } },
  passive: ['Intangible', 'Dashing makes him intangible to projectiles.'],
  passiveTick(f) { if (f.state === 'dash') f.pinvul = 2; },
  moves: {
    '5S': Mv.shot({ name: 'Ecto Shot', desc: 'A ghostly bullet that passes through walls.', proj: { speed: 1000, r: 10, dmg: 55, kind: 'skull', color: '#aac0ff', pierce: true } }),
    '6S': Mv.rush({ name: 'Phase Through', desc: 'Passes through the enemy, hitting on the way.', speed: 1200, frames: 14, pass: true, inv: [1, 18], hit: { dmg: 70 } }),
    '2S': Mv.custom({ name: 'Possession', desc: 'Briefly confuses the enemy.', s: 16, a: 6, r: 20, hit: { dmg: 40, box: [0, -120, 90, 120], guard: 'unblock', status: { confuse: 1.5 }, hs: 20, kb: [0, 0] }, ai: { min: 0, max: 80, use: 'combo' } }),
    '4S': Mv.teleport({ name: 'Vanishing Act', desc: 'Fades and reappears above.', to: 'above' }),
    'jS': Mv.dive({ name: 'Haunt', desc: 'Dives through the floor.', vx: 700, vy: 900, hit: { dmg: 80 } }),
  },
  super: Sup.place({ name: 'Poltergeist Storm', desc: 'Furniture flies at the enemy.', spawn: { kind: 'strike', at: 'enemy', delay: 0.3, count: 5, spacing: 70, stagger: 0.08, dmg: 55, style: 'anvil', color: '#aac0ff' } }),
  ult: { act: 'rush', name: 'THE HAUNTING', desc: 'Phasing grab. On hit: dragged into the haunted realm.', dmg: 1100, template: 'dimension', fx: { el: 'soul', world: 'haunt', color: '#aac0ff', sky: ['#000', '#0a0a1a', '#1a1a3a'], lines: ['Case closed...', '...for you.'] } },
  form: { name: 'POLTERGEIST', desc: 'Permanent. Fully ethereal: projectile immune while moving.', dmg: 1.1, speed: 1.1, model: { alpha: 0.6, aura: '#aac0ff', eyes: { glow: '#fff' } }, tick(f) { if (Math.abs(f.vx) > 50) f.pinvul = 2; } },
  assist: '5S',
  lines: { intro: ["You're a suspect, {opp}.", 'I\'ve been dead sixty years. I have time.', 'Nobody leaves the scene.'], win: ['Case closed.', 'Guilty.', 'Boo. I mean: justice.'], taunt: ['Boo.', 'Hmm... suspicious.'], form: ['Poltergeist!'], ult: ['The haunting begins.'], ultHit: ['Case closed.'] },
});

fighter({
  id: 'nova', name: 'NOVA', title: 'The Pop Idol', side: 'HERO', role: 'Rhythm · Charm', color: '#ff5ac8', color2: '#2a0a2a',
  bio: 'The world\'s biggest pop star. Her voice literally moves crowds, and sometimes buildings. She fights between concerts. Her manager is furious.',
  quote: 'This one\'s for my fans!', ending: 'Nova holds a benefit concert in the ruins. Every hero and villain comes. For three hours, nobody fights. It\'s a record.',
  hp: 950, walk: 290, rival: 'beat',
  model: { build: 'curvy', skin: '#f0c8b0', top: '#ff5ac8', pants: '#2a0a2a', skirt: '#ff9ae0', boots: '#fff', hair: { type: 'twintails', color: '#ffe05a' }, weapon: { type: 'mic' }, emblem: { shape: 'star', color: '#fff' }, stripes: '#fff' },
  face: { expr: 'grin', eyes: '#ff5ac8', hair: { type: 'twintails', color: '#ffe05a' }, marks: [{ type: 'star', color: '#ff5ac8' }] },
  passive: ['Encore', 'Her specials charm (confuse) on every third hit.'],
  onHit(a, t) { a.charm = (a.charm || 0) + 1; if (a.charm % 3 === 0) { t.status.confuse = 1; Game.popWorld(t.x, t.y - t.h - 30, '♥ CHARMED', '#ff5ac8', 20); } },
  moves: {
    '5S': Mv.shot({ name: 'High Note', desc: 'A piercing note.', proj: { speed: 900, r: 12, dmg: 55, kind: 'note', color: '#ff5ac8', trail: false } }),
    '6S': Mv.flurry({ name: 'Dance Break', desc: 'Spinning dance combo.', pose: 'kick', hits: 6, every: 4, vel: [[4, 26, 380, null]], hit: { dmg: 18 }, finisher: { dmg: 40, kb: [500, -400], launch: true } }),
    '2S': Mv.place({ name: 'Spotlight', desc: 'A blinding spotlight from above.', spawn: { kind: 'strike', at: 'enemy', delay: 0.4, dmg: 70, style: 'light', color: '#ffe05a', stun: 0.4 } }),
    '4S': Mv.buff({ name: 'Fan Service', desc: 'The crowd heals her (250).', effects: { heal: 250, haste: true }, dur: 3, cd: 15 }),
    'jS': Mv.shot({ name: 'Stage Dive', desc: 'Notes rain down.', proj: { speed: 800, r: 12, dmg: 34, count: 3, spread: 0.5, angle: 0.9, kind: 'note', color: '#ff5ac8', trail: false } }),
  },
  super: Sup.beam({ name: 'Power Ballad', desc: 'A wall of sound.', beam: { color: '#ff5ac8', dmg: 24, width: 90 } }),
  ult: { act: 'shot', name: 'FINAL CONCERT', desc: 'A showstopping note. On hit: the stadium goes wild.', dmg: 1100, template: 'barrage', proj: { kind: 'note', color: '#ff5ac8', r: 22 }, fx: { el: 'note', color: '#ff5ac8', sky: ['#1a001a', '#5a0a4a', '#ff5ac8'], lines: ['Thank you, everybody!', 'This is my last song!'] } },
  form: { name: 'ENCORE', desc: 'Permanent. Stage outfit: faster, notes pierce.', speed: 1.12, dmg: 1.12, model: { top: '#fff', skirt: '#ffe05a', aura: '#ff5ac8', hair: { type: 'twintails', color: '#ff5ac8' } } },
  assist: '2S',
  lines: { intro: ['Hi {opp}! Can I get an autograph? Oh wait, you want one from ME.', 'The show must go on!', 'Mic check! One, two!'], win: ['Thank you, goodnight!', 'Encore? Encore!', 'Love you, fans!'], taunt: ['La la la~', 'Wink!'], form: ['ENCORE!'], ult: ['Final concert!'], ultHit: ['And that\'s a wrap!'] },
});

fighter({
  id: 'ironjaw', name: 'IRON JAW', title: 'The Champ', side: 'HERO', role: 'Boxer · Pressure', color: '#ff3a3a', color2: '#2a0a0a',
  bio: 'Undefeated heavyweight champion. No powers at all, just fists, footwork and a chin that has broken three superhero hands.',
  quote: 'Let\'s go twelve rounds.', ending: 'Iron Jaw retires undefeated. Then un-retires. Then retires again. He is on his fourteenth comeback.',
  hp: 1050, walk: 300, rival: 'roo',
  model: { build: 'athletic', skin: '#6a4a3a', top: '#6a4a3a', pants: '#ff3a3a', boots: '#fff', belt: '#ffd35a', hair: { type: 'buzz', color: '#1a1a1a' }, weapon: { type: 'gloves', color: '#ff3a3a' }, glove: '#ff3a3a', abs: true },
  face: { expr: 'grin', eyes: '#3a2a1a', skin: '#6a4a3a', marks: [{ type: 'scar', color: '#4a2a1a' }], hair: { type: 'buzz', color: '#1a1a1a' } },
  style: { speed: 0.8, power: 1.1, poses: { '5M': 'punch2', '5H': 'heavy' } },
  passive: ['Iron Chin', 'Takes 20% less damage from the first two hits of any combo.'],
  passiveArmor(f) { return f.comboHits < 2 ? 0.8 : 1; },
  moves: {
    '5S': Mv.rush({ name: 'Jab Rush', desc: 'Stepping jab barrage.', speed: 600, frames: 18, hit: { dmg: 20, multi: 4, every: 4, kb: [120, 0], launch: false } }),
    '6S': Mv.rush({ name: 'Haymaker', desc: 'A huge charging hook.', s: 18, speed: 700, frames: 12, armor: [4, 20], hit: { dmg: 140, kb: [800, -200], wb: true } }),
    '2S': Mv.rising({ name: 'Uppercut', desc: 'Invincible uppercut.', hit: { dmg: 60, multi: 2 } }),
    '4S': Mv.counter({ name: 'Peek-a-Boo', desc: 'Guard counter.', window: 24, dmg: 130 }),
    'jS': Mv.dive({ name: 'Overhand', desc: 'Leaping overhand punch.', pose: 'air_heavy', vx: 600, vy: 1000, hit: { dmg: 90 } }),
  },
  super: Sup.flurry({ name: 'Rope-a-Dope', desc: 'Relentless body shots.', vel: [[8, 30, 200, null]], hit: { dmg: 24 } }),
  ult: { act: 'rush', name: 'KNOCKOUT ROUND', desc: 'A championship hook. On hit: the final round.', dmg: 1200, template: 'rush', fx: { el: 'metal', color: '#ff3a3a', sky: ['#1a0000', '#3a0a0a', '#8a1a1a'], lines: ['Round twelve.', 'Ding ding.'] } },
  form: { name: 'HEAVYWEIGHT CHAMP', desc: 'Permanent. Championship belt: armor on specials, more damage.', dmg: 1.18, armor: 0.88, model: { belt: '#ffe05a', aura: '#ff3a3a', pants: '#ffd35a' } },
  assist: '6S',
  lines: { intro: ['Gloves up, {opp}.', 'Twelve rounds. Let\'s go.', 'I don\'t need powers.'], win: ['And STILL undefeated!', 'You hit like a feather.', 'Down for the count.'], taunt: ['Come on!', 'Float like a butterfly...'], form: ['The champ is here!'], ult: ['Knockout round!'], ultHit: ['TEN!'] },
});

fighter({
  id: 'viper', name: 'VIPER', title: 'The Venom Fist', side: 'VILLAIN', role: 'Poison · Stacks', color: '#7aff3a', color2: '#0a1a0a',
  bio: 'A martial artist who trained with snakes until she became one. Her strikes carry venom that grows stronger the longer you stay near her.',
  quote: 'Sssstay close.', ending: 'Viper opens a venom antidote clinic. She charges triple. It\'s the only cure, so people pay.',
  hp: 950, walk: 290, rival: 'arachna',
  model: { build: 'slim', skin: '#b8d8a8', top: '#1a3a1a', pants: '#1a2a1a', boots: '#0a1a0a', hair: { type: 'ponytail', color: '#2a5a1a' }, mask: { type: 'half', color: '#1a3a1a' }, weapon: { type: 'claws', color: '#7aff3a' }, emblem: { shape: 'fang', color: '#7aff3a' }, scarf: { color: '#7aff3a' } },
  face: { expr: 'smirk', eyes: '#7aff3a', marks: [{ type: 'stripes', color: '#3a7a2a' }] },
  style: { speed: 0.85 },
  passive: ['Toxin', 'Every hit poisons. Poisoned enemies take 15% more damage.'],
  onHit(a, t) { t.status.poison = Math.max(t.status.poison || 0, 3); },
  passiveDmg(f, t) { return t && t.status.poison ? 1.15 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Venom Spit', desc: 'Toxic spit.', proj: { speed: 800, r: 10, dmg: 45, kind: 'poison', color: '#7aff3a', status: { poison: 3 } } }),
    '6S': Mv.rekka({ name: 'Snake Fang', desc: 'Three striking fangs (press S again).', steps: [{ speed: 900, frames: 8, hit: { dmg: 45, launch: false, kb: [150, 0] } }, { speed: 900, frames: 8, hit: { dmg: 50, launch: false, kb: [150, 0] } }, { speed: 900, frames: 10, hit: { dmg: 70, kb: [500, -500] } }] }),
    '2S': Mv.place({ name: 'Snake Pit', desc: 'Snakes burst from the ground.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 70, color: '#7aff3a', fill: '#2a5a1a', status: { poison: 3 } } }),
    '4S': Mv.shot({ name: 'Serpent', desc: 'A slithering snake.', proj: { speed: 600, r: 10, dmg: 50, kind: 'snake', color: '#7aff3a', offY: 70, guard: 'low', status: { poison: 3 } } }),
    'jS': Mv.dive({ name: 'Strike', desc: 'Diving fang.', hit: { dmg: 80, status: { poison: 3 } } }),
  },
  super: Sup.rush({ name: 'Nine Fangs', desc: 'Nine venomous strikes.', hit: { dmg: 24, status: { poison: 2 } } }),
  ult: { act: 'rush', name: 'HYDRA', desc: 'A venomous strike. On hit: the nine-headed hydra rises.', dmg: 1100, template: 'summon', fx: { el: 'poison', creature: 'hydra', color: '#7aff3a', sky: ['#000', '#0a1a0a', '#1a3a1a'], lines: ['Sssso close.', 'Meet my family.'] } },
  form: { name: 'HYDRA', desc: 'Permanent. Serpent aura: poison ticks harder.', dmg: 1.15, speed: 1.08, model: { aura: '#7aff3a', hair: { type: 'wild', color: '#3a8a2a' }, tentacles: { color: '#3a8a2a' } } },
  assist: '4S',
  lines: { intro: ['Sssso, {opp}.', 'Your blood will be... interesting.', 'Hold still. The venom does the rest.'], win: ['The venom wins.', 'Ssssweet.', 'Rest. Forever.'], taunt: ['Hsss.', 'Tick... tick...'], form: ['Hydra!'], ult: ['Nine heads!'], ultHit: ['Sssslept.'] },
});

fighter({
  id: 'karma', name: 'KARMA', title: 'The Balanced Monk', side: 'HERO', role: 'Counter · Retaliation', color: '#ffa05a', color2: '#2a1a0a',
  bio: 'A monk who carries the karmic debt of every fight she witnesses. Every hit she takes is recorded. Every debt is repaid.',
  quote: 'What you give, you get back.', ending: 'Karma balances the universe\'s books. It takes seven years. The universe owes her a vacation.',
  hp: 1000, walk: 250, rival: 'razor',
  model: { build: 'athletic', skin: '#c89a70', top: '#ff8a3a', pants: '#8a3a1a', boots: '#3a1a0a', hair: { type: 'bald', color: '#000' }, sleeves: '#ffa05a', emblem: { shape: 'circle', color: '#fff' }, weapon: { type: 'staff', color: '#6a4a2a', tip: '#ffa05a' } },
  face: { expr: 'calm', eyes: '#6a3a1a', hair: { type: 'bald', color: '#000' }, marks: [{ type: 'paint', color: '#ff5a1a' }] },
  style: { weapon: true, reach: 1.1 },
  passive: ['Karmic Debt', 'Stores 30% of damage taken; her next special releases it as bonus damage.'],
  onHurt(t, a, dmg) { t.debt = Math.min(400, (t.debt || 0) + dmg * 0.3); },
  passiveDmg(f) { if (f.move && f.move.kind === 'special' && (f.debt || 0) > 20) { const b = 1 + f.debt / 300; f.debt = 0; return b; } return 1; },
  moves: {
    '5S': Mv.shot({ name: 'Wheel Palm', desc: 'A spinning karmic wheel.', proj: { speed: 700, r: 16, dmg: 60, kind: 'ring', color: '#ffa05a', trail: false } }),
    '6S': Mv.counter({ name: 'Return', desc: 'Counter that repays the blow.', window: 28, dmg: 150 }),
    '2S': Mv.rising({ name: 'Lotus Rise', desc: 'Rising staff spin.', hit: { dmg: 42, multi: 3 } }),
    '4S': Mv.heal({ name: 'Meditate', desc: 'Converts stored debt into health.', amount: 200, cd: 12 }),
    'jS': Mv.dive({ name: 'Descending Wheel', desc: 'Spinning dive.', hit: { dmg: 85 } }),
  },
  super: Sup.rush({ name: 'Wheel of Life', desc: 'Spinning staff rush.', hit: { dmg: 26 } }),
  ult: { act: 'burst', name: 'WHEEL OF KARMA', desc: 'A karmic burst. On hit: every sin repaid at once.', dmg: 1150, template: 'dimension', fx: { el: 'wheel', world: 'wheel', color: '#ffa05a', sky: ['#1a0a00', '#4a2a0a', '#aa6a2a'], lines: ['Every blow you dealt...', 'Returns.'] } },
  form: { name: 'NIRVANA', desc: 'Permanent. Stores twice as much debt, regenerates.', regen: 1, dmg: 1.1, model: { aura: '#ffa05a', halo: { color: '#ffa05a' }, eyes: { glow: '#ffa05a' } } },
  assist: '5S',
  lines: { intro: ['Every action has a reaction, {opp}.', 'I will not strike first.', 'Balance.'], win: ['Balanced.', 'The debt is paid.', 'Namaste.'], taunt: ['Balance.', 'Breathe.'], form: ['Nirvana.'], ult: ['The wheel turns.'], ultHit: ['Paid in full.'] },
});

fighter({
  id: 'dune', name: 'DUNE', title: 'The Sand Pharaoh', side: 'VILLAIN', role: 'Zoner · Sand', color: '#e0b060', color2: '#3a2a0a',
  bio: 'A pharaoh buried alive five thousand years ago. His tomb was opened by tourists. He considers this very rude.',
  quote: 'All empires return to sand.', ending: 'Dune turns the city into a desert and rules it from a pyramid. The tourists come back. He sells them tickets.',
  hp: 1000, walk: 240, rival: 'terra',
  model: { skin: '#b08050', top: '#fff0c0', pants: '#e0c080', skirt: '#fff0c0', boots: '#e0b060', belt: '#3a6ad8', hair: { type: 'short', color: '#1a1a1a' }, hat: { type: 'kabuto', color: '#3a6ad8', accent: '#ffd35a' }, weapon: { type: 'staff', color: '#ffd35a', tip: '#3a6ad8' }, emblem: { shape: 'eye', color: '#3a6ad8' }, pads: { color: '#ffd35a' } },
  face: { expr: 'cold', eyes: '#3a6ad8', marks: [{ type: 'paint', color: '#1a1a1a' }], hat: { type: 'kabuto', color: '#3a6ad8', accent: '#ffd35a' } },
  style: { weapon: true, reach: 1.15 },
  passive: ['Sandstorm', 'His projectiles slow; slowed enemies take chip damage over time.'],
  moves: {
    '5S': Mv.shot({ name: 'Sand Blast', desc: 'A cone of stinging sand.', proj: { speed: 700, r: 16, dmg: 45, count: 3, spread: 0.25, kind: 'sand', color: '#e0b060', status: { slow: 1.5 } } }),
    '6S': Mv.place({ name: 'Quicksand', desc: 'A sinking trap.', spawn: { kind: 'trap', at: 'enemy', color: '#c09040', stun: 1, dmg: 40 }, cd: 4 }),
    '2S': Mv.place({ name: 'Sand Pillar', desc: 'A pillar of sand erupts.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 80, color: '#e0b060', fill: '#c09040', height: 220 } }),
    '4S': Mv.place({ name: 'Mummy', desc: 'A shambling mummy minion.', spawn: { kind: 'minion', at: 'front', dx: 40, look: 'skeleton', dmg: 55, hp: 90, speed: 180 }, cd: 5 }),
    'jS': Mv.shot({ name: 'Scarab Swarm', desc: 'Beetles downward.', proj: { speed: 700, r: 8, dmg: 26, count: 4, spread: 0.6, angle: 0.8, kind: 'sand', color: '#3a6ad8' } }),
  },
  super: Sup.place({ name: 'Desert Wrath', desc: 'A sandstorm around the enemy.', spawn: { kind: 'zone', at: 'enemy', r: 200, life: 3, every: 0.25, dmg: 26, color: '#e0b060', status: { slow: 1 } } }),
  ult: { act: 'strike', name: 'DESERT TOMB', desc: 'Sand from above. On hit: sealed in a pyramid.', dmg: 1100, template: 'quake', style: 'light', color: '#e0b060', fx: { el: 'sand', color: '#e0b060', sky: ['#3a1a00', '#aa6a20', '#f0c080'], lines: ['You disturbed my rest.', 'Now rest with me.'] } },
  form: { name: 'SAND PHARAOH', desc: 'Permanent. Floats on sand, stronger storms.', flight: true, dmg: 1.12, armor: 0.9, model: { aura: '#e0b060', float: true, eyes: { glow: '#3a6ad8' }, cape: { color: '#3a6ad8', inner: '#ffd35a' } } },
  assist: '2S',
  lines: { intro: ['You disturbed my tomb, {opp}.', 'I have waited five thousand years for this.', 'Kneel before the pharaoh.'], win: ['Return to the sand.', 'Entombed.', 'Dust.'], taunt: ['Sand.', 'Kneel.'], form: ['Rise, pharaoh!'], ult: ['Desert tomb.'], ultHit: ['Sealed.'] },
});

fighter({
  id: 'blitz', name: 'BLITZ', title: 'The Rocket Soldier', side: 'ANTI-HERO', role: 'Air · Explosives', color: '#ff8a3a', color2: '#2a2a1a',
  bio: 'A mercenary with a jetpack, a rocket launcher and zero chill. She sells her services to the highest bidder and the loudest explosion.',
  quote: 'Incoming!', ending: 'Blitz blows up the villains\' headquarters for free, just because it looked flammable. She sends Vex the bill anyway.',
  hp: 950, walk: 260, jumps: 3, rival: 'volt',
  model: { build: 'athletic', skin: '#d0a080', top: '#4a5a3a', pants: '#3a4a2a', boots: '#2a2a1a', belt: '#ffd35a', hair: { type: 'ponytail', color: '#ff5a1a' }, hat: { type: 'bandana', color: '#3a4a2a' }, mask: { type: 'shades', color: '#111' }, weapon: { type: 'cannon', color: '#4a5a3a', glow: '#ff8a3a' }, wings: { type: 'mech', color: '#5a6a4a', scale: 0.7 } },
  face: { expr: 'grin', eyes: '#3a8a3a', hair: { type: 'ponytail', color: '#ff5a1a' }, hat: { type: 'bandana', color: '#3a4a2a' } },
  passive: ['Jetpack', 'Triple jump and hovers when holding up.'],
  moves: {
    '5S': Mv.shot({ name: 'Rocket', desc: 'A straight rocket.', proj: { speed: 800, r: 10, dmg: 60, kind: 'missile', color: '#ff8a3a', explode: 60 } }),
    '6S': Mv.rush({ name: 'Jet Ram', desc: 'Jetpack tackle.', speed: 1300, frames: 14, hit: { dmg: 90, kb: [600, -300] } }),
    '2S': Mv.shot({ name: 'Mortar', desc: 'High arcing shell.', proj: { speed: 700, angle: -1.1, g: 1000, r: 12, dmg: 70, kind: 'bomb', color: '#ff8a3a', explode: 90 } }),
    '4S': Mv.place({ name: 'Claymore', desc: 'Directional mine (max 2).', spawn: { kind: 'mine', at: 'front', dx: 120, dmg: 90, limit: 2 }, cd: 3 }),
    'jS': Mv.shot({ name: 'Air Strike', desc: 'Rockets downward.', proj: { speed: 900, r: 10, dmg: 40, count: 2, spread: 0.3, angle: 0.9, kind: 'missile', color: '#ff8a3a', explode: 40 } }),
  },
  super: Sup.barrage({ name: 'Rocket Barrage', desc: 'Ten rockets.', volleys: 10, proj: { kind: 'missile', color: '#ff8a3a', dmg: 26, explode: 30, speed: 900 } }),
  ult: { act: 'strike', name: 'CARPET BOMB', desc: 'A marked target. On hit: bombers blanket the area.', dmg: 1100, template: 'storm', style: 'meteor', color: '#ff8a3a', fx: { el: 'bomb', color: '#ff8a3a', sky: ['#1a1000', '#5a3a10', '#c08040'], lines: ['Target painted.', 'Bombs away!'] } },
  form: { name: 'FULL ORDNANCE', desc: 'Permanent. Rockets home and explode bigger.', flight: true, dmg: 1.12, model: { wings: { type: 'mech', color: '#6a7a5a', scale: 1 }, aura: '#ff8a3a' } },
  assist: '2S',
  lines: { intro: ['Duck, {opp}!', 'I get paid by the explosion.', 'Lock and load!'], win: ['Boom. Invoice sent.', 'Kaboom!', 'Mission accomplished.'], taunt: ['Boom!', 'Heh.'], form: ['Full ordnance!'], ult: ['Bombs away!'], ultHit: ['Beautiful fireworks.'] },
});

fighter({
  id: 'morph', name: 'MORPH', title: 'The Mimic', side: 'VILLAIN', role: 'Copycat · Adaptive', color: '#aaaaaa', color2: '#1a1a1a',
  bio: 'A shapeshifting blob from a crashed alien ship. It copies whatever it sees. Right now it is copying you. It is very good at it.',
  quote: 'I am you. But better.', ending: 'Morph copies every hero at once and becomes the greatest hero of all. Then it gets bored and copies a houseplant.',
  hp: 950, walk: 270, rival: 'jinx',
  model: { skin: '#b8b8b8', top: '#8a8a8a', pants: '#6a6a6a', boots: '#4a4a4a', hair: { type: 'bald', color: '#000' }, eyes: { glow: '#ffffff' }, emblem: { shape: 'circle', color: '#fff' } },
  face: { skin: '#b8b8b8', expr: 'smirk', eyes: '#ffffff', glow: '#fff', hair: { type: 'bald', color: '#000' } },
  passive: ['Mimicry', 'Its 5S becomes a copy of the opponent\'s 5S after the first exchange.'],
  passiveTick(f) { const o = f.opp; if (o && f.st === 60) { f.def.mimic = o.def.moves['5S']; } },
  moves: {
    '5S': Mv.custom({ name: 'Copy Shot', desc: 'Uses the opponent\'s neutral special.', s: 12, a: 1, r: 18, ev: { 12: f => { const m = f.opp && f.opp.def.moves['5S']; if (m && m.ev) { for (const k of Object.keys(m.ev)) { const fr = Number(k); Game.later(Math.max(0, fr - 12) / FPS, () => { try { m.ev[k](f, m); } catch (e) { } }); } } else Combat.fireShots(f, { speed: 700, r: 12, dmg: 55, color: '#aaa', life: 2, hs: 20, kb: [180, -40] }); } }, ai: { min: 150, max: 1400, use: 'zone' } }),
    '6S': Mv.rush({ name: 'Blob Lunge', desc: 'Stretching lunge.', speed: 1000, frames: 16, hit: { dmg: 80 } }),
    '2S': Mv.counter({ name: 'Absorb', desc: 'Absorbs a hit and fires it back.', resp: 'reflect', window: 26 }),
    '4S': Mv.place({ name: 'Decoy', desc: 'A copy of itself that attacks.', spawn: { kind: 'clone', at: 'front', dx: 60 }, cd: 6 }),
    'jS': Mv.dive({ name: 'Splat', desc: 'Blob dive.', hit: { dmg: 80, gb: true } }),
  },
  super: Sup.rush({ name: 'Mirror Rush', desc: 'Copies a flurry.', hit: { dmg: 26 } }),
  ult: { act: 'rush', name: 'MIRROR MATCH', desc: 'A copying grab. On hit: trapped among a thousand copies.', dmg: 1100, template: 'dimension', fx: { el: 'mirror', world: 'mirror', color: '#ffffff', sky: ['#000', '#1a1a1a', '#3a3a3a'], lines: ['I am you.', 'All of you.'] } },
  form: { name: 'PERFECT MIMIC', desc: 'Permanent. Becomes a silver copy of the opponent\'s power.', dmg: 1.15, speed: 1.1, model: { top: '#dde', skin: '#e8e8f0', aura: '#fff', eyes: { glow: '#9cf' } } },
  assist: '4S',
  lines: { intro: ['Hello, {opp}. Hello, {opp}.', 'I like your face. Can I have it?', 'Blorp.'], win: ['I win. You win? No. I win.', 'Copied. Improved.', 'Blorp!'], taunt: ['Me too.', 'Blorp.'], form: ['Perfect copy.'], ult: ['Mirror match!'], ultHit: ['Which one is real?'] },
});

fighter({
  id: 'kingpin', name: 'KINGPIN', title: 'The Don', side: 'VILLAIN', role: 'Summoner · Money', color: '#5aba5a', color2: '#1a1a1a',
  bio: 'The man who owns the city\'s underworld. He does not have powers. He has goons, lawyers and a cane with a gun in it.',
  quote: 'Everybody has a price.', ending: 'Kingpin buys the ruined city for one dollar. He rebuilds it with his name on every building. It is somehow nicer than before.',
  hp: 1050, walk: 220, rival: 'chrome',
  model: { build: 'heavy', skin: '#e0b890', top: '#1a1a1a', pants: '#1a1a1a', boots: '#0a0a0a', coat: '#2a2a2a', hair: { type: 'slick', color: '#1a1a1a' }, hat: { type: 'tophat', color: '#1a1a1a', band: '#5aba5a' }, weapon: { type: 'cane', color: '#3a2a1a' }, emblem: { shape: 'dollar', color: '#5aba5a' } },
  face: { expr: 'grin', eyes: '#3a3a3a', hat: { type: 'tophat', color: '#1a1a1a', band: '#5aba5a' }, marks: [{ type: 'scar', color: '#9a6a5a' }] },
  style: { power: 1.1, speed: 1.1, heavy: true },
  passive: ['Bribe', 'His hits steal meter from the enemy.'],
  onHit(a, t) { const s = Math.min(t.side.meter, 10); t.side.meter -= s; a.side.meter += s; },
  moves: {
    '5S': Mv.shot({ name: 'Cane Shot', desc: 'The cane is a gun.', proj: { speed: 1400, r: 7, dmg: 50, kind: 'bullet', color: '#5aba5a' } }),
    '6S': Mv.place({ name: 'Call the Boys', desc: 'A goon charges in.', spawn: { kind: 'minion', at: 'front', dx: 30, look: 'goon', dmg: 60, hp: 80, speed: 320 }, cd: 4 }),
    '2S': Mv.shot({ name: 'Make It Rain', desc: 'Money that stuns greedy enemies.', proj: { speed: 600, r: 10, dmg: 30, count: 5, spread: 0.6, angle: -0.3, kind: 'money', color: '#5aba5a', stun: 0.2 } }),
    '4S': Mv.grab({ name: 'An Offer', desc: 'A grab they can\'t refuse.', range: 60, grabData: { anim: 'toss', dmg: 190, frames: 30 } }),
    'jS': Mv.dive({ name: 'Heavy Landing', desc: 'Crushing belly drop.', vx: 300, vy: 1400, hit: { dmg: 100, gb: true } }),
  },
  super: Sup.place({ name: 'Hit Squad', desc: 'Three goons.', spawn: { kind: 'minion', at: 'front', dx: 30, count: 3, spacing: 60, look: 'goon', dmg: 55, hp: 80, speed: 320 } }),
  ult: { act: 'grab', name: 'HOSTILE TAKEOVER', desc: 'A handshake. On connect: the whole organization arrives.', dmg: 1150, range: 70, template: 'summon', fx: { el: 'money', creature: 'goons', color: '#5aba5a', sky: ['#050505', '#1a1a1a', '#2a3a2a'], lines: ["It's just business.", 'Boys?'] } },
  form: { name: 'DON OF THE CITY', desc: 'Permanent. Gold suit: armor, stronger goons.', armor: 0.8, dmg: 1.12, model: { coat: '#ffd35a', top: '#3a2a0a', hat: { type: 'tophat', color: '#ffd35a', band: '#1a1a1a' }, aura: '#5aba5a' } },
  assist: '6S',
  lines: { intro: ['Everybody has a price, {opp}. What\'s yours?', 'My lawyers will handle the paperwork.', 'Take a seat.'], win: ['Business is business.', 'Paid in full.', 'Nothing personal.'], taunt: ['Cha-ching.', 'Heh heh.'], form: ['The Don is here.'], ult: ['Hostile takeover.'], ultHit: ['Sign here.'] },
});

fighter({
  id: 'quanta', name: 'PROF. QUANTA', title: 'The Quantum Physicist', side: 'HERO', role: 'Portals · Probability', color: '#6ad8ff', color2: '#0a1a3a',
  bio: 'Vex\'s former lab partner. She saw the same collapsing star and came away with the opposite conclusion: everything is possible, all at once.',
  quote: 'I am here. I am also there.', ending: 'Quanta proves Vex wrong in a peer-reviewed paper. He reads it. He cries. They get coffee.',
  hp: 950, walk: 260, rival: 'vex',
  model: { build: 'slim', skin: '#d8b8a0', top: '#e8f0ff', pants: '#2a3a5a', boots: '#1a1a2a', coat: '#f0f4ff', hair: { type: 'bob', color: '#3a2a1a' }, mask: { type: 'glasses', color: '#6ad8ff' }, emblem: { shape: 'atom', color: '#6ad8ff' }, weapon: { type: 'orb', color: '#6ad8ff' } },
  face: { expr: 'smirk', eyes: '#6ad8ff', mask: { type: 'glasses', color: '#6ad8ff' }, hair: { type: 'bob', color: '#3a2a1a' } },
  passive: ['Superposition', 'Her projectiles sometimes split into two.'],
  onHit() { },
  moves: {
    '5S': Mv.shot({ name: 'Quantum Orb', desc: 'An orb that splits in two.', proj: { speed: 700, r: 12, dmg: 42, count: 2, spread: 0.3, color: '#6ad8ff' } }),
    '6S': Mv.teleport({ name: 'Tunnel', desc: 'Quantum tunnels in front of the enemy.', to: 'front', hit: { dmg: 70 } }),
    '2S': Mv.place({ name: 'Portal', desc: 'Opens a portal that pulls.', spawn: { kind: 'blackhole', at: 'front', dx: 220, r: 240, life: 1.5, dmg: 12 }, cd: 5 }),
    '4S': Mv.custom({ name: 'Uncertainty', desc: 'Teleports to a random nearby spot.', s: 8, a: 1, r: 10, ev: { 8: f => { Combat.teleport(f, pick(['behind', 'above', 'back'])); } }, ai: { min: 0, max: 200, use: 'counter' } }),
    'jS': Mv.shot({ name: 'Particle Rain', desc: 'Particles downward.', proj: { speed: 900, r: 8, dmg: 26, count: 4, spread: 0.6, angle: 0.9, color: '#6ad8ff' } }),
  },
  super: Sup.beam({ name: 'Wave Function', desc: 'A beam of probability.', beam: { color: '#6ad8ff', dmg: 24 } }),
  ult: { act: 'shot', name: 'WAVEFUNCTION COLLAPSE', desc: 'An observed particle. On hit: every possibility collapses on them.', dmg: 1100, template: 'dimension', proj: { color: '#6ad8ff', r: 22 }, fx: { el: 'atom', world: 'quantum', color: '#6ad8ff', sky: ['#000', '#0a1a3a', '#1a3a6a'], lines: ['Observe.', 'Collapse.'] } },
  form: { name: 'SUPERPOSITION', desc: 'TIMED (10s). Exists twice: a shadow copy mirrors every attack.', timed: 10, cost: 300, clones: true, dmg: 1.25, speed: 1.1, model: { aura: '#6ad8ff', eyes: { glow: '#6ad8ff' } } },
  assist: '2S',
  lines: { intro: ['Statistically, {opp}, you already lost.', 'I am here and there. Mostly here.', 'Let\'s run an experiment.'], win: ['Hypothesis confirmed.', 'Probability: 100%.', 'Peer reviewed.'], taunt: ['Fascinating.', 'Hmm!'], form: ['Superposition!'], ult: ['Collapse!'], ultHit: ['Observed.'] },
});
rival('vex', 'quanta', [[1, 'Vex. We saw the same star. You chose nothing.'], [0, 'And you chose everything, Quanta. Everything is exhausting.'], [1, 'Then let me wake you up.']], { quanta: 'Coffee after this?', vex: 'Everything... returns to nothing.' });

fighter({
  id: 'blossom', name: 'BLOSSOM', title: 'The Garden Guardian', side: 'HERO', role: 'Healer · Nature', color: '#8aff6a', color2: '#1a3a1a',
  bio: 'A botanist who grew a garden on a rooftop in the worst neighborhood in the city. It grew into a forest. It grew into her.',
  quote: 'Everything grows back.', ending: 'Blossom turns the ruined city into a garden. It is the most beautiful place on Earth. Titania is jealous.',
  hp: 1000, walk: 250, rival: 'titania',
  model: { build: 'curvy', skin: '#e0c0a0', top: '#6aba5a', pants: '#3a7a2a', skirt: '#8aff6a', boots: '#3a2a1a', hair: { type: 'long', color: '#ff8ac8' }, emblem: { shape: 'leaf', color: '#fff' }, weapon: { type: 'staff', color: '#6a4a2a', tip: '#ff8ac8' } },
  face: { expr: 'smirk', eyes: '#5aba3a', hair: { type: 'long', color: '#ff8ac8' } },
  style: { weapon: true, reach: 1.15 },
  passive: ['Photosynthesis', 'Regenerates 4 HP per second while not being hit.'],
  passiveTick(f) { if (f.state !== 'hit' && f.st % 15 === 0) f.hp = Math.min(f.maxHp, f.hp + 1); },
  moves: {
    '5S': Mv.shot({ name: 'Seed Shot', desc: 'Seeds that sprout on impact.', proj: { speed: 700, r: 10, dmg: 50, kind: 'leaf', color: '#8aff6a', explode: 40 } }),
    '6S': Mv.shot({ name: 'Vine Whip', desc: 'A vine that pulls.', proj: { speed: 1100, r: 10, dmg: 45, kind: 'hook', color: '#3a8a2a', trail: false, life: 0.6, pull: true, hs: 30 } }),
    '2S': Mv.place({ name: 'Thorn Bed', desc: 'Thorns erupt beneath the enemy.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 75, color: '#3a8a2a', fill: '#2a5a1a' } }),
    '4S': Mv.place({ name: 'Healing Garden', desc: 'A flower patch that heals (≈400).', spawn: { kind: 'zone', at: 'self', r: 110, heal: 50, every: 0.5, life: 4, color: '#8aff6a' }, cd: 14, ai: { min: 0, max: 3000, use: 'heal' } }),
    'jS': Mv.shot({ name: 'Pollen Drift', desc: 'Sleepy pollen downward.', proj: { speed: 500, r: 12, dmg: 30, count: 3, spread: 0.6, angle: 0.8, kind: 'petal', color: '#ffe05a', stun: 0.3 } }),
  },
  super: Sup.place({ name: 'Overgrowth', desc: 'A line of thorny trees.', spawn: { kind: 'spike', at: 'front', dx: 90, delay: 0.1, count: 6, spacing: 90, stagger: 0.08, dmg: 60, color: '#3a8a2a', fill: '#2a5a1a', height: 200 } }),
  ult: { act: 'strike', name: 'BLOOM OF AGES', desc: 'Roots burst up. On hit: the World Tree rises through them.', dmg: 1100, template: 'summon', style: 'light', color: '#8aff6a', fx: { el: 'nature', creature: 'tree', color: '#8aff6a', sky: ['#0a1a0a', '#1a4a1a', '#6aba5a'], lines: ['Everything grows back.', 'Even stronger.'] } },
  form: { name: 'WORLD TREE', desc: 'Permanent. Bark armor, faster regeneration.', armor: 0.8, regen: 1, dmg: 1.1, scale: 1.1, model: { top: '#5a3a1a', skin: '#8a6a4a', hair: { type: 'wild', color: '#6aba5a' }, aura: '#8aff6a' } },
  assist: '4S',
  lines: { intro: ['Please don\'t step on the flowers, {opp}.', 'Let\'s grow through this together.', 'Nature always wins.'], win: ['Bloom where you\'re planted.', 'Photosynthesized.', 'Take care of yourself!'], taunt: ['Bloom!', 'Grow!'], form: ['World Tree!'], ult: ['Bloom!'], ultHit: ['Everything grows back.'] },
});

fighter({
  id: 'neon', name: 'NEON', title: 'The Street Skater', side: 'ANTI-HERO', role: 'Momentum · Graffiti', color: '#ff2aff', color2: '#0a0a2a',
  bio: 'A graffiti artist who painted a mural so good it came alive. Now her paint does whatever she wants. She mostly wants to skate.',
  quote: 'Catch me if you can!', ending: 'Neon paints the entire ruined city in neon murals. It becomes the most visited place on Earth. She never charges admission.',
  hp: 900, walk: 330, rival: 'volt',
  model: { build: 'slim', skin: '#c89a80', top: '#1a1a3a', pants: '#2a2a4a', boots: '#ff2aff', hair: { type: 'bob', color: '#2af0ff' }, hat: { type: 'beanie', color: '#ff2aff', accent: '#2af0ff' }, stripes: '#2af0ff', emblem: { shape: 'star', color: '#ff2aff' }, scarf: { color: '#2af0ff' } },
  face: { expr: 'grin', eyes: '#ff2aff', hair: { type: 'bob', color: '#2af0ff' }, hat: { type: 'beanie', color: '#ff2aff', accent: '#2af0ff' }, marks: [{ type: 'paint', color: '#2af0ff' }] },
  style: { speed: 0.8 },
  passive: ['Momentum', 'Deals more damage the faster she\'s moving.'],
  passiveDmg(f) { return 1 + Math.min(0.3, Math.abs(f.vx) / 1500); },
  moves: {
    '5S': Mv.shot({ name: 'Spray Can', desc: 'A blob of glowing paint that slows.', proj: { speed: 800, r: 12, dmg: 45, kind: 'poison', color: '#ff2aff', status: { slow: 1.5 } } }),
    '6S': Mv.rush({ name: 'Grind', desc: 'Skate grind dash.', pose: 'sweep', speed: 1300, frames: 18, hit: { dmg: 80, guard: 'low', kb: [300, -500], box: [-10, -50, 70, 50] } }),
    '2S': Mv.place({ name: 'Graffiti Trap', desc: 'A painted trap.', spawn: { kind: 'trap', at: 'front', dx: 180, color: '#2af0ff', stun: 0.9, dmg: 35, limit: 2 }, cd: 3 }),
    '4S': Mv.rising({ name: 'Kickflip', desc: 'Kickflip anti-air.', pose: 'kick', hit: { dmg: 42, multi: 3 } }),
    'jS': Mv.dive({ name: 'Board Slam', desc: 'Skateboard dive.', vx: 900, vy: 900, hit: { dmg: 85 } }),
  },
  super: Sup.rush({ name: 'Rainbow Rail', desc: 'A neon grind rush.', speed: 1500, frames: 16, pass: true, hit: { dmg: 26 } }),
  ult: { act: 'rush', name: 'NEON NIGHTS', desc: 'A blazing grind. On hit: the city lights up for her.', dmg: 1100, template: 'rush', fx: { el: 'neon', color: '#ff2aff', sky: ['#0a001a', '#2a0a4a', '#ff2aff'], lines: ['Lights up!', 'This city is my canvas.'] } },
  form: { name: 'OVERDRIVE', desc: 'Permanent. Rocket skates: much faster, paint trails.', speed: 1.25, dmg: 1.1, model: { aura: '#2af0ff', boots: '#2af0ff', eyes: { glow: '#ff2aff' } } },
  assist: '6S',
  lines: { intro: ['Nice wall. Mind if I tag it?', 'Keep up, {opp}!', 'Board\'s waxed. Let\'s go.'], win: ['Tagged you!', 'Sick!', 'Too slow, too boring.'], taunt: ['Ollie!', 'Rad!'], form: ['Overdrive!'], ult: ['Neon nights!'], ultHit: ['Masterpiece.'] },
});

fighter({
  id: 'abyss', name: 'ABYSS', title: 'The Deep One', side: 'VILLAIN', role: 'Grappler · Tentacles', color: '#3affc8', color2: '#021a1a',
  bio: 'Something that lived at the bottom of the ocean before there was an ocean. Dr. Gear\'s submarine woke it up. It is hungry and it has many arms.',
  quote: 'Ph\'nglui... hello.', ending: 'Abyss drags the whole city beneath the waves. It is quiet down there. The fish seem happier.',
  hp: 1100, walk: 210, weight: 0.85, wide: 1.1, rival: 'mira',
  model: { build: 'heavy', skin: '#2a6a6a', top: '#1a4a5a', pants: '#0a3a4a', boots: '#0a2a3a', animal: { type: 'squid', color: '#3a8a8a' }, tentacles: { color: '#2a6a6a' }, weapon: { type: 'claws', color: '#3affc8' } },
  face: { animal: { type: 'squid', color: '#3a8a8a' } },
  style: { reach: 1.3, power: 1.1, speed: 1.1 },
  passive: ['Many Arms', 'Normals have extra reach; grabs have more range.'],
  moves: {
    '5S': Mv.shot({ name: 'Ink Cloud', desc: 'Blinding ink.', proj: { speed: 600, r: 18, dmg: 40, kind: 'ink', color: '#140a20', status: { slow: 1.5 }, stun: 0.3 } }),
    '6S': Mv.grab({ name: 'Tentacle Grab', desc: 'Long-range tentacle grab.', range: 120, grabData: { anim: 'slam', dmg: 180 } }),
    '2S': Mv.place({ name: 'Tentacle Burst', desc: 'A tentacle bursts under the enemy.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 80, color: '#3a8a8a', fill: '#2a6a6a', height: 220 } }),
    '4S': Mv.shot({ name: 'Undertow Lash', desc: 'A tentacle that pulls.', proj: { speed: 1100, r: 12, dmg: 45, kind: 'hook', color: '#3a8a8a', trail: false, life: 0.7, pull: true, hs: 30 } }),
    'jS': Mv.dive({ name: 'Depth Charge', desc: 'Crushing plunge.', vx: 300, vy: 1500, hit: { dmg: 110, gb: true } }),
  },
  super: Sup.grab({ name: 'Drown', desc: 'Drags the enemy down.', range: 110, grabData: { anim: 'drain', dmg: 380 } }),
  ult: { act: 'grab', name: 'CALL OF THE DEEP', desc: 'A tentacle grab. On connect: the Kraken rises.', dmg: 1200, range: 120, template: 'summon', fx: { el: 'water', creature: 'kraken', color: '#3affc8', sky: ['#000', '#021a1a', '#0a3a3a'], lines: ['Come... deeper...', 'Join us.'] } },
  form: { name: 'KRAKEN', desc: 'Permanent. Enormous, super armor, longer tentacles.', scale: 1.3, superArmor: true, armor: 0.8, dmg: 1.15, speed: 0.9, model: { animal: { type: 'squid', color: '#1a6a6a' }, tentacles: { color: '#0a4a4a' }, aura: '#3affc8' } },
  assist: '2S',
  lines: { intro: ['...hungry...', 'Ph\'nglui mglw\'nafh {opp}.', 'The deep remembers.'], win: ['...full...', 'Down you go.', 'The deep takes all.'], taunt: ['Blub.', '...'], form: ['KRAKEN!'], ult: ['Deeper...'], ultHit: ['...mine.'] },
});

fighter({
  id: 'judge', name: 'THE JUDGE', title: 'Cosmic Law', side: 'ANTI-HERO', role: 'Verdicts · Punisher', color: '#e0e0ff', color2: '#1a1a2a',
  bio: 'An enforcer of cosmic law who judges heroes and villains by the same rules. Most of them are guilty of property damage. All of them, actually.',
  quote: 'Order in the court.', ending: 'The Judge sentences every hero AND villain to community service rebuilding the city. Nobody argues. The gavel is very large.',
  hp: 1050, walk: 230, rival: 'maximus',
  model: { build: 'athletic', skin: '#c8c8d8', top: '#1a1a2a', pants: '#1a1a2a', boots: '#0a0a14', coat: '#1a1a2a', hat: { type: 'wig', color: '#f0f0f0' }, weapon: { type: 'gavel', color: '#6b4a2a' }, emblem: { shape: 'scale', color: '#ffd35a' }, eyes: { glow: '#e0e0ff' } },
  face: { expr: 'cold', eyes: '#e0e0ff', glow: '#e0e0ff', hat: { type: 'wig', color: '#f0f0f0' } },
  style: { power: 1.15, speed: 1.1, heavy: true },
  passive: ['Guilty', 'Marks the enemy after 5 hits: the marked take 20% more damage.'],
  onHit(a, t) { a.guilty = (a.guilty || 0) + 1; if (a.guilty >= 5) { a.guilty = 0; t.status.mark = 5; Game.popWorld(t.x, t.y - t.h - 30, 'GUILTY!', '#ffd35a', 22); } },
  passiveDmg(f, t) { return t && t.status.mark ? 1.2 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Summons', desc: 'A spinning gavel.', proj: { speed: 700, r: 16, dmg: 60, kind: 'hammer', color: '#e0e0ff', boomerang: 0.5, life: 2.5 } }),
    '6S': Mv.rush({ name: 'Objection!', desc: 'Charging gavel strike.', speed: 900, frames: 16, armor: [4, 20], hit: { dmg: 110, kb: [700, -300], wb: true } }),
    '2S': Mv.place({ name: 'Sentence', desc: 'A gavel falls from above.', spawn: { kind: 'strike', at: 'enemy', delay: 0.45, dmg: 90, style: 'anvil', color: '#e0e0ff', stun: 0.3 } }),
    '4S': Mv.place({ name: 'Jail Cell', desc: 'Bars trap the enemy.', spawn: { kind: 'trap', at: 'enemy', color: '#aaa', stun: 1.2, dmg: 30 }, cd: 6 }),
    'jS': Mv.dive({ name: 'Gavel Drop', desc: 'Falling gavel slam.', vx: 300, vy: 1400, hit: { dmg: 100, gb: true } }),
  },
  super: Sup.place({ name: 'Class Action', desc: 'Five gavels fall.', spawn: { kind: 'strike', at: 'enemy', delay: 0.3, count: 5, spacing: 80, stagger: 0.08, dmg: 60, style: 'anvil', color: '#e0e0ff' } }),
  ult: { act: 'strike', name: 'FINAL VERDICT', desc: 'A falling gavel. On hit: the cosmic court convenes.', dmg: 1150, template: 'storm', style: 'anvil', color: '#e0e0ff', fx: { el: 'anvil', color: '#e0e0ff', sky: ['#050510', '#1a1a3a', '#4a4a7a'], lines: ['The court finds you...', 'GUILTY.'] } },
  form: { name: 'SUPREME COURT', desc: 'Permanent. Every hit counts double toward GUILTY.', dmg: 1.12, armor: 0.88, scale: 1.1, model: { coat: '#ffd35a', hat: { type: 'wig', color: '#ffd35a' }, aura: '#e0e0ff' } },
  assist: '2S',
  lines: { intro: ['You are charged with property damage, {opp}.', 'Order in the court!', 'How do you plead?'], win: ['Guilty as charged.', 'Case dismissed.', 'Court adjourned.'], taunt: ['Order!', 'Objection!'], form: ['Supreme court!'], ult: ['Final verdict!'], ultHit: ['GUILTY.'] },
});
