// ============================================================
//  MOONKAI — roster part 1 (fighters 5–19)
// ============================================================
fighter({
  id: 'volt', name: 'VOLT', title: 'The Living Current', side: 'HERO', role: 'Rushdown · Speed', color: '#ffe95a', color2: '#1a1a4e',
  bio: 'A courier struck by lightning eleven times. The twelfth time, the lightning lost. Now he IS the storm, and he is always in a hurry.',
  quote: 'You blinked. That was your whole turn.', ending: 'Volt delivers every package in the city in 0.8 seconds. Then he gets bored and runs to the moon to check on Eric.',
  hp: 920, walk: 340, rival: 'blitz',
  model: { build: 'slim', skin: '#e6b98c', top: '#1a1a2e', pants: '#1a1a2e', boots: '#ffe000', belt: '#ffe000', glove: '#ffe000', hair: { type: 'spiky', color: '#ffe95a' }, mask: { type: 'visor', color: '#ffe000' }, emblem: { shape: 'bolt', color: '#ffe000' }, stripes: '#ffe000', scarf: { color: '#ffe000' } },
  face: { expr: 'grin', eyes: '#ffe95a' },
  style: { speed: 0.8, power: 0.9 },
  passive: ['Static', 'Dashes are faster and leave a spark that shocks.'],
  moves: {
    '5S': Mv.shot({ name: 'Chain Lightning', desc: 'Near-instant bolt that stuns briefly.', s: 9, proj: { speed: 1900, r: 9, dmg: 60, kind: 'bolt', color: '#bff4ff', life: 0.35, stun: 0.3 } }),
    '6S': Mv.rush({ name: 'Flash Step', desc: 'Invulnerable dash straight through.', s: 5, speed: 1600, frames: 12, pass: true, inv: [1, 16], hit: { dmg: 70, kb: [100, -300] } }),
    '2S': Mv.rising({ name: 'Thunder Rise', desc: 'Spiraling anti-air.', hit: { dmg: 36, multi: 4, every: 3, stun: 0.2 } }),
    '4S': Mv.place({ name: 'Storm Call', desc: 'Bolt strikes the enemy.', spawn: { kind: 'strike', at: 'enemy', delay: 0.4, dmg: 70, style: 'bolt', color: '#bff4ff', stun: 0.3 }, ai: { min: 200, max: 1600, use: 'zone' } }),
    'jS': Mv.dive({ name: 'Lightning Kick', desc: 'Electric dive kick.', vx: 1100, vy: 700, hit: { dmg: 80, stun: 0.2 } }),
  },
  super: Sup.flurry({ name: 'Million Volt Rush', desc: 'Blinding multi-hit rush.', vel: [[8, 26, 700, null]], hit: { dmg: 22, stun: 0.1 } }),
  ult: { act: 'rush', name: "THUNDER GOD'S VERDICT", desc: 'Lightning-speed tackle. On hit: 12 strikes from the sky.', dmg: 1100, template: 'storm', fx: { el: 'bolt', color: '#bff4ff', sky: ['#05060f', '#1a1a3a', '#3a3a6a'], lines: ['Twelve times it struck me.', "Now it's your turn."] } },
  form: { name: 'STORM AVATAR', desc: 'Permanent. Faster, hits chain extra lightning.', speed: 1.2, dmg: 1.1, scale: 1.08, model: { aura: '#9fe8ff', hair: { type: 'spiky', color: '#e8fbff' }, eyes: { glow: '#9fe8ff' }, emblem: { shape: 'bolt', color: '#fff' }, stripes: '#9fe8ff' },
    moves: { '4S': Mv.place({ name: 'Thunderstorm', desc: 'Three bolts in a row.', spawn: { kind: 'strike', at: 'enemy', delay: 0.35, count: 3, spacing: 90, stagger: 0.12, dmg: 55, style: 'bolt', color: '#bff4ff' } }) } },
  onHit(a, t) { if (a.form && Math.random() < 0.25) t.status.stun = Math.max(t.status.stun || 0, 0.15); },
  assist: '4S',
  lines: { intro: ["Let's make this fast. I've got deliveries.", 'Blink and miss it, {opp}.', 'Charged and ready!'], win: ['Too slow! Way too slow!', 'Signed, sealed, delivered.', 'Zap. Done. Next?'], taunt: ['Come on, keep up!', 'Bzzt!'], form: ['I AM the storm!'], ult: ['JUDGMENT BOLT!'], ultHit: ['That was twelve.'], assist: ['Zap!'] },
});

fighter({
  id: 'glacia', name: 'GLACIA', title: 'The Frozen Throne', side: 'VILLAIN', role: 'Control · Walls & slows', color: '#9ff', color2: '#1a4a7a',
  bio: 'Queen of a kingdom that froze solid three centuries ago. She woke up last Tuesday and has decided the rest of the world should match.',
  quote: 'Be still. It will hurt less if you are still.', ending: 'The planet freezes over. Glacia sits on a throne of glaciers, finally at home. She is lonely. She will not admit it.',
  hp: 1050, walk: 240, rival: 'kira',
  model: { build: 'curvy', skin: '#d8e8f4', top: '#5aa0d8', topDark: '#2a6090', pants: '#e8f6ff', boots: '#9cd', skirt: '#bfe6ff', hair: { type: 'long', color: '#f4fbff' }, cape: { color: '#bfe6ff', inner: '#e8fbff' }, emblem: { shape: 'snow', color: '#fff' }, hat: { type: 'tiara', color: '#9ff' }, weapon: { type: 'staff', color: '#dff', tip: '#9ff' } },
  face: { expr: 'cold', eyes: '#39c', hair: { type: 'long', color: '#f4fbff' }, hat: { type: 'tiara', color: '#9ff' } },
  style: { reach: 1.15, weapon: true },
  passive: ['Frostbite', 'Slowed or frozen enemies take 15% more damage from her.'],
  passiveDmg(f, t) { return t && (t.status.slow || t.status.freeze) ? 1.15 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Frost Shards', desc: 'Three shards that slow.', proj: { speed: 760, r: 9, dmg: 34, count: 3, spread: 0.3, kind: 'shard', color: '#bff', status: { slow: 1.5 } } }),
    '6S': Mv.place({ name: 'Ice Wall', desc: 'Wall that blocks projectiles and launches.', spawn: { kind: 'wall', at: 'front', dx: 90, w: 40, hgt: 160, hp: 300, life: 5, dmg: 70, style: 'ice', colors: ['#dff', '#9cf'], limit: 1 }, cd: 5, ai: { min: 200, max: 1200, use: 'trap' } }),
    '2S': Mv.place({ name: 'Permafrost', desc: 'Ice spikes under the enemy that slow.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 70, color: '#9ff', fill: '#dff', status: { slow: 2 } }, ai: { min: 150, max: 1400, use: 'zone' } }),
    '4S': Mv.counter({ name: 'Mirror of Ice', desc: 'Freezing counter: reflects the attacker.', resp: 'reflect', window: 22 }),
    'jS': Mv.shot({ name: 'Hailstorm', desc: 'Shards rain diagonally.', proj: { speed: 800, r: 9, dmg: 28, count: 4, spread: 0.5, angle: 0.7, kind: 'shard', color: '#bff', status: { slow: 1 } } }),
  },
  super: Sup.place({ name: 'Glacier Rise', desc: 'A wall of ice spikes rolls forward.', spawn: { kind: 'spike', at: 'front', dx: 100, delay: 0.1, count: 8, spacing: 80, stagger: 0.07, dmg: 60, color: '#9ff', fill: '#dff', status: { slow: 2 } } }),
  ult: { act: 'shot', name: 'ETERNAL WINTER', desc: 'A freezing lance. On hit: encased in a glacier and shattered.', dmg: 1100, template: 'freeze', proj: { kind: 'shard', color: '#bff', r: 22 }, fx: { el: 'ice', color: '#bff', sky: ['#020a1e', '#0a2a4a', '#4a8aba'], lines: ['Winter does not end.', 'It waits.'] } },
  form: { name: 'ABSOLUTE ZERO', desc: 'Permanent. A freezing aura slows anyone nearby.', scale: 1.12, armor: 0.85, dmg: 1.12, model: { aura: '#9ff', auraSize: 1.3, eyes: { glow: '#9ff' }, cape: { color: '#e8fbff', len: 1.1 }, top: '#8ad0ff' },
    tick(f) { const o = f.opp; if (o && Math.abs(o.x - f.x) < 240) o.status.slow = Math.max(o.status.slow || 0, 0.3); } },
  assist: '2S',
  lines: { intro: ['Kneel, {opp}. The ice is patient.', 'Another warm-blooded pest.', 'Let us make this... cool.'], win: ['Frozen, as all things should be.', 'Shh. Rest now.', 'I told you to be still.'], taunt: ['Chilly?', 'Shiver.'], form: ['Absolute zero.'], ult: ['Eternal winter.'], ultHit: ['Shatter.'] },
});

fighter({
  id: 'titan', name: 'TITAN', title: 'The Unbreakable', side: 'HERO', role: 'Grappler · Heavy', color: '#e0a020', color2: '#3a4a5a',
  bio: 'A former pro wrestler whose body was rebuilt with alloy after he held up a collapsing bridge for nine hours. He has never lost a match. He has never been thrown.',
  quote: 'Come here. I just want a hug.', ending: 'Titan opens a wrestling school for kids with powers. Tuition is free. Suplexes are mandatory.',
  hp: 1180, walk: 220, weight: 0.75, wide: 1.2, rival: 'warden',
  model: { build: 'heavy', skin: '#c68a5a', top: '#3a4a5a', pants: '#2a2a2a', boots: '#111', belt: '#e0a020', glove: '#e0a020', hair: { type: 'buzz', color: '#222' }, pads: { color: '#e0a020', size: 1.3 }, emblem: { shape: 'star', color: '#e0a020' }, weapon: { type: 'gauntlet', color: '#e0a020' }, abs: true },
  face: { expr: 'grin', eyes: '#5a3a1a', marks: [{ type: 'scar', color: '#9a5a3a' }] },
  style: { power: 1.2, speed: 1.15, heavy: true },
  passive: ['Unbreakable', 'Armor on heavy attacks. Takes 25% less knockback.'],
  moves: {
    '5S': Mv.grab({ name: 'Titan Grip', desc: 'Command grab slam (unblockable).', range: 62, grabData: { anim: 'slam', dmg: 210 } }),
    '6S': Mv.rush({ name: 'Shoulder Charge', desc: 'Armored charge that knocks far.', speed: 850, frames: 20, armor: [4, 30], hit: { dmg: 110, kb: [800, -200], wb: true } }),
    '2S': Mv.grab({ name: 'Giant Swing', desc: 'Spins the foe and hurls them to the wall.', range: 60, grabData: { anim: 'spin', dmg: 190, frames: 44 } }),
    '4S': Mv.buff({ name: 'Flex', desc: 'Super armor for 3s.', effects: { armor: true }, dur: 3, cd: 10 }),
    'jS': Mv.dive({ name: 'Flying Elbow', desc: 'Body-slam from above.', vx: 400, vy: 1300, hit: { dmg: 110, gb: true } }),
  },
  super: Sup.grab({ name: 'Piledriver', desc: 'Command grab super.', range: 70, grabData: { anim: 'suplex', dmg: 420 } }),
  ult: { act: 'grab', name: 'METEOR SUPLEX', desc: 'Grab. On connect: to orbit and back.', dmg: 1350, range: 80, template: 'grab', fx: { el: 'metal', color: '#e0a020', sky: ['#0a0a1a', '#1a2a4a', '#4a6a9a'], lines: ['Hold on tight.', "We're going UP."] } },
  form: { name: 'IRON COLOSSUS', desc: 'Permanent. Giant metal body, super armor, bigger grabs.', scale: 1.35, speed: 0.85, armor: 0.7, dmg: 1.25, superArmor: true, heavyLanding: true,
    model: { top: '#8a95a4', skin: '#9aa4b0', pads: { color: '#6a7584', size: 1.5, spikes: '#e0a020' }, eyes: { glow: '#ff5a1a' }, aura: '#ffb040' } },
  assist: '6S',
  lines: { intro: ["Let's get you in a headlock.", "Don't worry, {opp}. I'll put you back together after.", 'Ding ding ding!'], win: ['Pin. One. Two. Three.', "That's how you hug.", 'Nobody throws Titan.'], taunt: ['Come on, try to lift me!', 'Flex!'], form: ['IRON!'], ult: ['Hold on tight!'], ultHit: ['Welcome back to Earth.'] },
});

fighter({
  id: 'nyx', name: 'NYX', title: 'The Quiet Blade', side: 'VILLAIN', role: 'Assassin · Stealth', color: '#ff2a6a', color2: '#1a0a20',
  bio: 'The last of an order of assassins who took contracts on gods. She has been hired to kill every hero on this list. She is ahead of schedule.',
  quote: "You won't hear me. That's the point.", ending: 'Nyx collects on every contract, then burns the payment. Nobody knows who hired her. Nobody ever will.',
  hp: 900, walk: 320, rival: 'kage',
  model: { build: 'slim', skin: '#c9a88a', top: '#15121c', pants: '#15121c', boots: '#0a0a0a', belt: '#c01040', hair: { type: 'ponytail', color: '#1a0a20' }, mask: { type: 'half', color: '#101014' }, scarf: { color: '#c01040' }, weapon: { type: 'dual', color: '#ccd' }, eyes: { color: '#c01040' } },
  face: { expr: 'cold', eyes: '#c01040', hair: { type: 'ponytail', color: '#1a0a20' } },
  style: { speed: 0.8, power: 0.95, weapon: true },
  passive: ['Backstab', 'Hits from behind deal 35% more damage.'],
  passiveDmg(f, t) { return t && t.facing === (t.x >= f.x ? 1 : -1) ? 1.35 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Kunai Fan', desc: 'Two kunai that mark (+30% next hit).', s: 9, proj: { speed: 1050, r: 7, dmg: 36, count: 2, spread: 0.1, kind: 'kunai', color: '#c01040', trail: false, status: { mark: 3 } } }),
    '6S': Mv.teleport({ name: 'Shadow Swap', desc: 'Teleport behind and strike.', to: 'behind', hit: { dmg: 85 } }),
    '2S': Mv.buff({ name: 'Veil', desc: 'Invisible for 2.5s; next hit crits.', effects: { invis: true, power: true }, dur: 2.5, cd: 8 }),
    '4S': Mv.counter({ name: 'Blade Parry', desc: 'Counter stance.', window: 20, dmg: 110 }),
    'jS': Mv.shot({ name: 'Rain of Steel', desc: 'Kunai straight down.', proj: { speed: 1000, r: 7, dmg: 26, count: 4, spread: 0.6, angle: 1.1, kind: 'kunai', color: '#c01040', trail: false } }),
  },
  super: Sup.rush({ name: 'Silent Requiem', desc: 'Invisible blade rush.', speed: 1500, frames: 14, pass: true, hit: { dmg: 30, multi: 9, every: 2 } }),
  ult: { act: 'rush', name: 'DEATH LOTUS', desc: 'A blur of steel. On hit: sixteen slashes.', dmg: 1150, template: 'rush', fx: { el: 'shadow', color: '#ff2a6a', sky: ['#050008', '#1a0414', '#3a0a2a'], lines: ['Close your eyes.', 'It is already over.'] } },
  form: { name: 'THOUSAND SHADOWS', desc: 'Permanent. Two shadow clones copy every strike.', clones: true, speed: 1.1, dmg: 1.05, model: { aura: '#5a0a3a', eyes: { glow: '#ff2a6a' }, weapon: { type: 'dual', color: '#ccd', glow: '#ff2a6a' } } },
  onHit(a, t, dmg, h) { if (a.form && h.dmg > 20 && Math.random() < 0.5) Game.later(0.1, () => { if (t.hp > 0) { t.hp = Math.max(1, t.hp - Math.round(dmg * 0.3)); Game.fx.burst(t.x, t.y - 60, 6, { color: ['#ff2a6a', '#fff'], size: 5, speed: 200, glow: true, life: 0.3 }); } }); },
  assist: '5S',
  lines: { intro: ['Your name was on my list, {opp}.', '...', 'I was paid in advance.'], win: ['Contract fulfilled.', 'You never saw me.', 'Next name.'], taunt: ['Behind you.', 'Tsk.'], form: ['There are more of me than you think.'], ult: ['Death Lotus.'], ultHit: ['Petals fall.'] },
});

fighter({
  id: 'gear', name: 'DR. GEAR', title: 'The Mad Mechanic', side: 'VILLAIN', role: 'Summoner · Setup', color: '#ffb020', color2: '#3a3a3a',
  bio: 'A genius inventor fired from every lab on Earth for "ethical concerns". He builds robots. Then he builds bigger robots. Then he gets inside one.',
  quote: "Science isn't about WHY. It's about WHY NOT.", ending: 'Dr. Gear conquers the city with an army of turrets, then gets distracted building a better toaster. The city is still waiting.',
  hp: 1050, walk: 240, rival: 'cipher',
  model: { skin: '#e0b090', top: '#e8e2d0', topDark: '#b8b2a0', pants: '#3a3a3a', boots: '#5a3a1a', belt: '#ffb020', coat: '#d8d2c0', hair: { type: 'wild', color: '#e8e8e8' }, mask: { type: 'goggles', color: '#5a3a1a', lens: '#9ff' }, weapon: { type: 'wrench', color: '#aab' }, emblem: { shape: 'gear', color: '#ffb020' } },
  face: { expr: 'grin', eyes: '#3a8a3a', hair: { type: 'wild', color: '#e8e8e8' } },
  passive: ['Overclock', 'Turrets and missiles get stronger each round he survives.'],
  moves: {
    '5S': Mv.shot({ name: 'Rocket Salvo', desc: 'Three homing mini-missiles.', proj: { speed: 560, angle: -0.5, spread: 0.5, count: 3, homing: 3, r: 7, dmg: 34, kind: 'missile', color: '#ffb020', life: 2.4, explode: 30 } }),
    '6S': Mv.place({ name: 'Drone Turret', desc: 'Deploys a turret (max 2).', spawn: { kind: 'turret', at: 'front', dx: 70, life: 8, hp: 160, shotDmg: 22, limit: 2 }, cd: 5 }),
    '2S': Mv.place({ name: 'Proximity Mine', desc: 'Buried mine (max 2).', spawn: { kind: 'mine', at: 'front', dx: 160, dmg: 100, limit: 2 }, cd: 3 }),
    '4S': Mv.place({ name: 'Bot Swarm', desc: 'Sends a walking robot minion.', spawn: { kind: 'minion', at: 'front', dx: 40, look: 'bot', dmg: 60, hp: 80, speed: 280 }, cd: 5 }),
    'jS': Mv.shot({ name: 'Grenade Drop', desc: 'Lobbed bomb.', proj: { speed: 400, angle: 0.3, g: 1200, r: 10, dmg: 70, kind: 'bomb', color: '#ffb020', explode: 90 } }),
  },
  super: Sup.barrage({ name: 'Missile Storm', desc: 'Ten homing missiles.', volleys: 10, proj: { kind: 'missile', color: '#ffb020', dmg: 26, homing: 3, speed: 600, explode: 30, angle: -0.8 } }),
  ult: { act: 'strike', name: 'ORBITAL LASER', desc: 'Targeted strike from orbit. On hit: satellite cinematic.', dmg: 1100, template: 'orbital', style: 'light', color: '#9ff', fx: { el: 'tech', color: '#9ff', sky: ['#02020a', '#0a1020', '#1a2a3a'], lines: ['Satellite online.', 'Say cheese.'] } },
  form: { name: 'MECH SUIT', desc: 'Permanent. Pilots a battle mech: cannon, armor.', scale: 1.35, speed: 0.9, armor: 0.7, dmg: 1.25, superArmor: true, heavyLanding: true, model: { body: drawMech, metal: '#8a95a4', accent: '#ffb020', skin: '#e0b090' },
    moves: { '5S': Mv.shot({ name: 'Mech Cannon', desc: 'Huge explosive shell.', proj: { speed: 780, r: 20, dmg: 100, explode: 90, color: '#9ff', prio: 2 } }) } },
  assist: '6S',
  lines: { intro: ['Ah, a test subject!', 'Hold still, {opp}, I need measurements.', 'My robots have been SO bored.'], win: ['Data collected. Mwahaha!', 'Another successful experiment!', 'Note to self: more missiles.'], taunt: ['Eureka!', 'Science!'], form: ['Activate MECH MODE!'], ult: ['Satellite online!'], ultHit: ['Peer review THAT.'], assist: ['Deploying!'] },
});

fighter({
  id: 'seraph', name: 'SERAPH', title: 'The Last Light', side: 'HERO', role: 'Sustain · Area', color: '#ffe08a', color2: '#6a5aa8',
  bio: 'An angel sent to judge humanity who decided, after a week of watching people, to defend it instead. Heaven is not pleased.',
  quote: 'I was sent to judge you. I choose to protect you.', ending: 'Seraph is recalled to Heaven for disobedience. She does not go. There is a very confused angel posted outside her apartment.',
  hp: 1000, walk: 250, rival: 'grimm',
  model: { build: 'curvy', skin: '#f0d0b0', top: '#f4f0ff', topDark: '#c8c0e8', pants: '#e8e0ff', skirt: '#fffbe8', boots: '#ffd35a', belt: '#ffd35a', hair: { type: 'long', color: '#ffe9a0' }, halo: { color: '#ffe08a' }, weapon: { type: 'spear', color: '#ffd35a', tip: '#fff' }, emblem: { shape: 'cross', color: '#ffd35a' }, wings: { type: 'feather', color: '#fff8e8', scale: 0.7 } },
  face: { expr: 'calm', eyes: '#58a', halo: { color: '#ffe08a' } },
  style: { reach: 1.2, weapon: true },
  passive: ['Grace', 'Regenerates 3 HP per second.'],
  passiveTick(f) { if (f.st % 20 === 0) f.hp = Math.min(f.maxHp, f.hp + 1); },
  moves: {
    '5S': Mv.shot({ name: 'Light Spear', desc: 'Piercing spear of light.', proj: { speed: 1100, r: 10, dmg: 72, kind: 'spear', pierce: true, color: '#ffe08a', trail: false } }),
    '6S': Mv.rush({ name: 'Wing Lunge', desc: 'Swooping spear thrust.', speed: 1000, frames: 16, hit: { dmg: 95, kb: [500, -300] } }),
    '2S': Mv.place({ name: 'Sanctuary', desc: 'Healing circle (≈400 HP).', spawn: { kind: 'zone', at: 'self', r: 110, heal: 50, every: 0.5, life: 4, color: '#ffe08a' }, cd: 14, ai: { min: 0, max: 3000, use: 'heal' } }),
    '4S': Mv.place({ name: 'Radiant Pillar', desc: 'Light pillars on the enemy.', spawn: { kind: 'strike', at: 'enemy', delay: 0.45, dmg: 80, style: 'light', color: '#ffe08a' }, ai: { min: 200, max: 1600, use: 'zone' } }),
    'jS': Mv.shot({ name: 'Judgment Rain', desc: 'Three spears downward.', proj: { speed: 1000, r: 9, dmg: 34, count: 3, spread: 0.4, angle: 1.0, kind: 'spear', color: '#ffe08a', trail: false } }),
  },
  super: Sup.place({ name: 'Heaven\'s Gate', desc: 'A row of radiant pillars.', spawn: { kind: 'strike', at: 'enemy', delay: 0.3, count: 5, spacing: 90, stagger: 0.08, dmg: 70, style: 'light', color: '#ffe08a', wide: 40 } }),
  ult: { act: 'strike', name: 'JUDGMENT HALO', desc: 'A pillar of judgment. On hit: heavens open. Heals 300.', dmg: 1050, template: 'storm', style: 'light', color: '#ffe08a', fx: { el: 'light', color: '#ffe08a', sky: ['#2a2050', '#8a70c0', '#ffe0b0'], lines: ['By the authority I abandoned...', '...be judged.'] }, after: a => Combat.healSelf(a, 300) },
  form: { name: 'ARCHANGEL', desc: 'Permanent. Six wings: flight and stronger light.', flight: true, regen: 1, dmg: 1.12, speed: 1.08, scale: 1.1, model: { wings: { type: 'light', color: '#ffe9a0', scale: 1.3 }, aura: '#fff0b0', eyes: { glow: '#ffe08a' }, top: '#fffbe8' } },
  assist: '4S',
  lines: { intro: ['I will not let you harm them, {opp}.', 'Lay down your weapon. Please.', 'Heaven is watching. So am I.'], win: ['Be at peace.', 'Mercy is a choice. I chose it.', 'Rise when you are ready.'], taunt: ['Repent.', 'Hmm.'], form: ['Let there be light.'], ult: ['Judgment Halo!'], ultHit: ['Forgiven.'] },
});

fighter({
  id: 'razor', name: 'RAZOR', title: 'The Red Berserker', side: 'ANTI-HERO', role: 'Berserker · Comeback', color: '#ff2020', color2: '#3a0808',
  bio: 'A gladiator from an alien arena who crash-landed here. He fights heroes and villains alike. He does not care who wins, only that it was close.',
  quote: 'Bleed a little. It makes it honest.', ending: 'Razor builds an arena in the ruins of the city. Every weekend, heroes and villains fight there, and for once, nobody else gets hurt.',
  hp: 1020, walk: 280, rival: 'kael',
  model: { build: 'athletic', skin: '#b08060', top: '#4a1010', topDark: '#2a0808', pants: '#222', boots: '#111', belt: '#888', hair: { type: 'mohawk', color: '#c01818' }, pads: { color: '#555', spikes: '#aaa' }, weapon: { type: 'greatsword', color: '#9aa' }, emblem: { shape: 'fang', color: '#c01818' }, scarf: { color: '#7a0a0a' }, abs: true },
  face: { expr: 'grin', eyes: '#ff2020', marks: [{ type: 'scar', color: '#8a2020' }, { type: 'paint', color: '#c01818' }] },
  style: { reach: 1.25, power: 1.1, speed: 1.1, weapon: true },
  passive: ['Rage', 'Deals up to +40% damage as his health drops.'],
  passiveDmg(f) { return 1 + (1 - f.hp / f.maxHp) * 0.4; },
  moves: {
    '5S': Mv.place({ name: 'Blood Wave', desc: 'A crimson ground wave.', spawn: { kind: 'wave', at: 'front', dx: 60, dir: 1, dmg: 70, life: 0.9, colors: ['#c01818', '#600'] }, ai: { min: 100, max: 800, use: 'zone' } }),
    '6S': Mv.rush({ name: 'Blood Rush', desc: 'Dash slash that bleeds.', speed: 1300, frames: 12, pass: true, hit: { dmg: 80, status: { bleed: 2 } } }),
    '2S': Mv.rising({ name: 'Reaper Rise', desc: 'Rising greatsword arc.', hit: { dmg: 50, multi: 3 } }),
    '4S': Mv.custom({ name: 'Rending Cleave', desc: 'Slow, huge overhead chop.', pose: 'slam', s: 24, a: 6, r: 22, armor: [6, 24], hit: { dmg: 160, guard: 'high', box: [0, -130, 110, 130], kb: [400, -400], launch: true, sfx: 'h' }, ai: { min: 0, max: 100, use: 'combo' } }),
    'jS': Mv.dive({ name: 'Skullsplitter', desc: 'Plunging greatsword.', vx: 300, vy: 1300, hit: { dmg: 110, gb: true } }),
  },
  super: Sup.flurry({ name: 'Red Whirlwind', desc: 'Spinning blade vortex.', pose: 'dash', vel: [[8, 44, 360, null]], hit: { dmg: 24, status: { bleed: 1 } } }),
  ult: { act: 'rush', name: 'CRIMSON TEMPEST', desc: 'A berserker charge. On hit: a storm of blood and steel.', dmg: 1150, template: 'rush', fx: { el: 'blood', color: '#ff2020', sky: ['#0a0000', '#3a0000', '#7a0a0a'], lines: ['Finally.', 'A worthy fight.'] } },
  form: { name: 'BLOODRAGE', desc: 'Permanent. Lifesteal 20%, faster, but takes 10% more damage.', lifesteal: 0.2, speed: 1.15, armor: 1.1, dmg: 1.15, scale: 1.08, model: { aura: '#ff1a1a', eyes: { glow: '#ff2020' }, weapon: { type: 'greatsword', color: '#c33', glow: '#ff2020' }, skin: '#a05050' } },
  assist: '6S',
  lines: { intro: ['Make it close, {opp}. I hate easy wins.', 'RRRAAAH! Let us dance!', 'The crowd wants blood.'], win: ['Good fight. Again tomorrow?', 'You bled well.', 'The arena remembers you.'], taunt: ['MORE!', 'Is that all?!'], form: ['BLOODRAGE!'], ult: ['CRIMSON TEMPEST!'], ultHit: ['Beautiful.'] },
});

fighter({
  id: 'terra', name: 'TERRA', title: 'The Mountain Speaker', side: 'HERO', role: 'Defensive · Terrain', color: '#7dff6a', color2: '#3a2a1a',
  bio: 'A shepherd from a mountain village who can hear the stones talk. They have been complaining about the cities for a long time.',
  quote: 'The mountain is patient. I am the mountain.', ending: 'Terra raises new mountains where the ruined towers stood. People move in. They say the rocks hum lullabies at night.',
  hp: 1150, walk: 230, weight: 0.85, rival: 'dune',
  model: { skin: '#8a5a3a', top: '#4a6a3a', topDark: '#2a4a24', pants: '#5a4a3a', boots: '#3a2a1a', belt: '#c8a050', hair: { type: 'twintails', color: '#2a1a0a' }, emblem: { shape: 'rock', color: '#c8a050' }, weapon: { type: 'staff', color: '#6b4a2a', tip: '#8f8' }, pads: { color: '#7a6a5a' } },
  face: { expr: 'calm', eyes: '#3a8a2a' },
  style: { reach: 1.15, weapon: true, heavy: true },
  passive: ['Bedrock', 'Takes 15% less damage while standing still or blocking.'],
  passiveArmor(f) { return Math.abs(f.vx) < 20 ? 0.85 : 1; },
  moves: {
    '5S': Mv.shot({ name: 'Boulder Toss', desc: 'Arcing boulder that explodes.', s: 16, proj: { speed: 680, angle: -0.45, g: 1200, r: 18, dmg: 80, kind: 'rock', color: '#7a6a5a', explode: 60, trail: false, prio: 2 } }),
    '6S': Mv.place({ name: 'Stone Pillar', desc: 'Pillar erupts under the enemy and stays as a wall.', spawn: { kind: 'wall', at: 'enemy', w: 46, hgt: 140, hp: 260, life: 4, dmg: 90, colors: ['#7a6a5a', '#554'] }, cd: 4, ai: { min: 150, max: 1300, use: 'zone' } }),
    '2S': Mv.place({ name: 'Quake Stomp', desc: 'Ground wave both directions.', spawn: { kind: 'wave', at: 'self', dir: 1, dmg: 60, life: 0.8, colors: ['#7dff6a', '#6b5a48'] } }),
    '4S': Mv.buff({ name: 'Stone Skin', desc: 'Damage resistance for 4s.', effects: { fortify: true }, dur: 4, cd: 10 }),
    'jS': Mv.shot({ name: 'Rockfall', desc: 'Drops a boulder.', proj: { speed: 300, angle: 1.3, g: 1400, r: 18, dmg: 70, kind: 'rock', color: '#7a6a5a', explode: 50, trail: false } }),
  },
  super: Sup.place({ name: 'Mountain Range', desc: 'Stone spikes erupt in a line.', spawn: { kind: 'spike', at: 'front', dx: 90, delay: 0.1, count: 7, spacing: 85, stagger: 0.07, dmg: 65, color: '#7dff6a', fill: '#6b5a48', height: 190 } }),
  ult: { act: 'burst', name: 'TECTONIC COLLAPSE', desc: 'Earth-splitting stomp. On hit: the ground swallows them.', dmg: 1150, template: 'quake', fx: { el: 'rock', color: '#7dff6a', sky: ['#1a1410', '#4a3a2a', '#8a6a4a'], lines: ['The mountain has been patient.', 'It is done being patient.'] } },
  form: { name: 'MOUNTAIN GOLEM', desc: 'Permanent. A walking mountain: armor, super armor.', scale: 1.4, speed: 0.8, armor: 0.62, dmg: 1.22, superArmor: true, heavyLanding: true, model: { body: drawGolem, rock: '#6b5a48', glowColor: '#7dff6a' } },
  assist: '6S',
  lines: { intro: ['The stones say you talk too much, {opp}.', 'Breathe. Feel the ground.', 'Please take your shoes off. The mountain is listening.'], win: ['Rest. The earth will hold you.', 'Patience wins.', 'The mountain thanks you.'], taunt: ['Unmoved.', '...'], form: ['Mountain, rise!'], ult: ['Tectonic collapse!'], ultHit: ['Returned to the earth.'] },
});
charById('terra').moves['2S'].ev = { 14: f => { for (const d of [-1, 1]) Combat.addHazard({ kind: 'wave', x: f.x + d * 60, dir: d, owner: f, side: f.side, dmg: 60, life: 0.8, colors: ['#7dff6a', '#6b5a48'], hits: new Map(), move: f.move }); Cam.shake = 10; Sfx.rock(); } };

fighter({
  id: 'jinx', name: 'JINX', title: 'The Cosmic Joker', side: 'VILLAIN', role: 'Chaos · Random', color: '#d05aff', color2: '#2a0a3a',
  bio: 'A stage magician who made a deal with an entity from outside reality. The entity found him funny. Now reality is his punchline.',
  quote: 'Pick a card! Any card! ...Oops.', ending: 'Jinx replaces the moon with a giant rubber chicken. Scientists are baffled. Eric is furious. Jinx is delighted.',
  hp: 950, walk: 290, rival: 'morph',
  model: { build: 'slim', skin: '#f0c8a0', top: '#7a2a9a', topDark: '#4a1a6a', pants: '#222', boots: '#7a2a9a', belt: '#ffd35a', hair: { type: 'jester', color: '#7a2a9a', accent: '#1a1a1a' }, mask: { type: 'band', color: '#fff' }, weapon: { type: 'cards' }, emblem: { shape: 'spade', color: '#ffd35a' }, stripes: '#ffd35a', cape: { color: '#2a0a3a', len: 0.8 } },
  face: { expr: 'grin', eyes: '#d05aff', hair: { type: 'short', color: '#7a2a9a' }, hat: { type: 'tophat', color: '#2a0a3a', band: '#d05aff' }, marks: [{ type: 'star', color: '#d05aff' }] },
  passive: ['Lucky', 'Every hit has a 12% chance to deal double damage.'],
  passiveDmg() { if (Math.random() < 0.12) { Game.announceSmall && Game.announceSmall('LUCKY!'); return 2; } return 1; },
  moves: {
    '5S': Mv.custom({ name: 'Wild Card', desc: 'A card with a random effect.', s: 12, a: 1, r: 18, ev: { 12: f => { const e = pick([['#ff7a1a', { burn: 2.5 }], ['#9ff', { slow: 2 }], ['#ffd35a', null, 0.5], ['#ff3b3b', null, 0, 80], ['#b36bff', { weaken: 3 }]]); Combat.fireShots(f, { speed: 820, r: 9, dmg: randi(50, 85), kind: 'card', color: e[0], status: e[1], stun: e[2] || 0, explode: e[3] || 0, trail: false, life: 2, hs: 20, kb: [180, -40] }); } }, ai: { min: 120, max: 1400, use: 'zone' } }),
    '6S': Mv.swap({ name: 'Switcheroo', desc: 'Swap places with the enemy and confuse them.', confuse: 1.6, dmg: 40, cd: 7 }),
    '2S': Mv.place({ name: 'Trap Door', desc: 'A hidden trap that snares.', spawn: { kind: 'trap', at: 'front', dx: 180, color: '#d05aff', stun: 1, dmg: 40, limit: 1 }, cd: 4 }),
    '4S': Mv.place({ name: 'Jack-in-the-Box', desc: 'A spring-loaded surprise under the enemy.', spawn: { kind: 'spike', at: 'enemy', delay: 0.6, dmg: 90, color: '#d05aff', fill: '#ffd35a' } }),
    'jS': Mv.shot({ name: 'Card Shower', desc: 'Five cards fanning down.', proj: { speed: 850, r: 8, dmg: 24, count: 5, spread: 0.8, angle: 0.8, kind: 'card', color: '#d05aff', trail: false } }),
  },
  super: Sup.barrage({ name: 'Full Deck', desc: 'Fifty-two cards. Some explode.', volleys: 13, proj: { kind: 'card', color: '#d05aff', dmg: 22, explode: 20 } }),
  ult: { act: 'strike', name: 'COSMIC PUNCHLINE', desc: 'A slot machine decides. Then anvils fall.', dmg: 1100, template: 'storm', style: 'anvil', color: '#d05aff', fx: { el: 'anvil', color: '#d05aff', sky: ['#1a0a2a', '#4a1a6a', '#d05aff'], lines: ['Knock knock.', "Who's there? ANVIL."] } },
  form: { name: 'JACKPOT', desc: 'Permanent. A random buff every 5 seconds.', dmg: 1.08, speed: 1.08, model: { aura: '#ffd35a', top: '#d02a8a', eyes: { glow: '#ffd35a' } },
    tick(f) { if (f.st % 300 === 0) { const b = pick([['HASTE', 'haste'], ['POWER', 'power'], ['FORTIFY', 'fortify'], ['REGEN', 'regen']]); f.status[b[1]] = 4; Game.popWorld(f.x, f.y - f.h - 30, '🎰 ' + b[0], '#ffd35a', 22); Sfx.card(); } } },
  assist: '5S',
  lines: { intro: ["Pick a card, {opp}! Not that one.", 'Ladies and gentlemen, the main event!', "Why so serious? Oh wait, that's someone else's line."], win: ['And for my next trick...!', 'Ta-daaa!', 'The house always wins!'], taunt: ['Honk honk!', 'Hehehe!'], form: ['JACKPOT!'], ult: ['Knock knock!'], ultHit: ["Who's there? GRAVITY."] },
});

fighter({
  id: 'echo', name: 'ECHO', title: 'The Second Chance', side: 'HERO', role: 'Tactician · Time', color: '#88f0e0', color2: '#0a2a3a',
  bio: 'A sound engineer who recorded the frequency of time itself. She can rewind a few seconds, slow the world, and, once in a while, stop it completely.',
  quote: "Let's try that again.", ending: 'Echo rewinds the whole fight, just once, and this time nobody gets hurt. Only she remembers. She thinks that is fair.',
  hp: 980, walk: 270, rival: 'oracle',
  model: { build: 'slim', skin: '#d0a888', top: '#1a3a4a', topDark: '#0a2a3a', pants: '#2a2a3a', boots: '#88f0e0', belt: '#88f0e0', hair: { type: 'bob', color: '#e0e0f0' }, mask: { type: 'visor', color: '#88f0e0' }, emblem: { shape: 'note', color: '#88f0e0' }, scarf: { color: '#88f0e0' }, weapon: { type: 'mic' } },
  face: { expr: 'smirk', eyes: '#88f0e0', hair: { type: 'bob', color: '#e0e0f0' }, mask: null },
  passive: ['Resonance', 'Blocking builds extra meter.'],
  onHurt() { },
  moves: {
    '5S': Mv.shot({ name: 'Sonic Boom', desc: 'Sound ring that pushes far.', proj: { speed: 720, r: 18, dmg: 60, kb: [700, -60], kind: 'ring', color: '#88f0e0', trail: false } }),
    '6S': Mv.rush({ name: 'Fast Forward', desc: 'Time-skip dash strike.', speed: 1500, frames: 10, pass: true, inv: [1, 14], hit: { dmg: 80 } }),
    '2S': Mv.custom({ name: 'Rewind', desc: 'Return to 3 seconds ago, with that health.', s: 16, a: 1, r: 14, cd: 14, ev: { 16: f => { const s = f.history[0]; if (!s) return; Game.fx.burst(f.x, f.y - 60, 30, { color: ['#88f0e0', '#fff'], size: 8, speed: 220, glow: true }); f.x = s.x; f.y = s.y; if (s.hp > f.hp) Combat.healSelf(f, s.hp - f.hp); Game.popWorld(f.x, f.y - f.h - 40, 'REWIND', '#88f0e0', 26); Sfx.bell(); } }, ai: { min: 0, max: 3000, use: 'heal' } }),
    '4S': Mv.place({ name: 'Time Bubble', desc: 'A bubble that slows everything inside.', spawn: { kind: 'zone', at: 'front', dx: 200, r: 120, life: 3, every: 0.3, dmg: 6, color: '#88f0e0', status: { slow: 1 } }, cd: 6 }),
    'jS': Mv.shot({ name: 'Echo Drop', desc: 'Sound ring angled down.', proj: { speed: 700, r: 16, dmg: 50, angle: 0.6, kb: [500, 200], kind: 'ring', color: '#88f0e0', trail: false } }),
  },
  super: Sup.barrage({ name: 'Feedback Loop', desc: 'Rapid sound rings.', volleys: 8, proj: { kind: 'ring', color: '#88f0e0', dmg: 30, r: 16, speed: 800, kb: [300, -40] } }),
  ult: { act: 'rush', name: 'TIME STOP', desc: 'Stops time on contact. Twelve strikes, then play.', dmg: 1100, template: 'freeze', fx: { el: 'time', color: '#88f0e0', sky: ['#050a10', '#1a2a3a', '#3a5a6a'], lines: ['Let me stop you right there.', '...and play.'] } },
  form: { name: 'CHRONO SHIFT', desc: 'TIMED (10s). The enemy moves at 2/3 speed.', timed: 10, timeSlowOpp: true, dmg: 1.1, cost: 200, model: { aura: '#88f0e0', eyes: { glow: '#88f0e0' }, cape: { color: '#1a5a6a' } } },
  assist: '5S',
  lines: { intro: ["I've seen this fight before, {opp}. You lose.", 'Take two!', "Let's run it back."], win: ['That was take one. You get no take two.', 'Rewind that in your head.', 'Encore? No.'], taunt: ['Tick tock.', 'Again!'], form: ['Slow down.'], ult: ['Time... STOP.'], ultHit: ['...and play.'] },
});
ROSTER.find(d => d.id === 'echo').onHurt = null;

// ---------------- new fighters ----------------
fighter({
  id: 'mira', name: 'MIRA TIDE', title: 'Queen of the Deep', side: 'HERO', role: 'Zoner · Water', color: '#3ac8ff', color2: '#0a3a5a',
  bio: 'The heir of a drowned kingdom beneath the harbor. She surfaced to stop the villains poisoning her ocean, and she brought the ocean with her.',
  quote: 'The tide always comes back.', ending: 'Mira opens the ocean kingdom to surface-dwellers. Tourism booms. The fish are unimpressed.',
  hp: 1000, walk: 260, rival: 'abyss',
  model: { build: 'curvy', skin: '#c8e0e8', top: '#1a6a9a', topDark: '#0a4a6a', pants: '#1a5a7a', boots: '#3ac8ff', belt: '#ffd35a', hair: { type: 'long', color: '#3a9ad8' }, weapon: { type: 'trident', color: '#ffd35a', tip: '#ffd35a', shaft: '#e0c060' }, emblem: { shape: 'drop', color: '#9ff' }, hat: { type: 'tiara', color: '#ffd35a' } },
  face: { expr: 'smirk', eyes: '#3ac8ff', hat: { type: 'tiara', color: '#ffd35a' } },
  style: { reach: 1.2, weapon: true },
  passive: ['High Tide', 'Her water attacks push enemies further and slow them briefly.'],
  onHit(a, t) { if (Math.random() < 0.3) t.status.slow = Math.max(t.status.slow || 0, 0.8); },
  moves: {
    '5S': Mv.shot({ name: 'Bubble Prison', desc: 'Slow bubble that traps briefly.', proj: { speed: 420, r: 18, dmg: 50, kind: 'bubble', color: '#9ff', stun: 0.6, life: 3 } }),
    '6S': Mv.rush({ name: 'Riptide', desc: 'Surging water dash.', speed: 1100, frames: 16, hit: { dmg: 90, kb: [650, -200] } }),
    '2S': Mv.place({ name: 'Geyser', desc: 'Water erupts beneath the enemy.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 85, color: '#3ac8ff', fill: '#9ff', height: 220 }, ai: { min: 150, max: 1500, use: 'zone' } }),
    '4S': Mv.shot({ name: 'Undertow', desc: 'A whip of water that pulls.', proj: { speed: 1000, r: 12, dmg: 50, kind: 'hook', color: '#3ac8ff', trail: false, life: 0.6, pull: true, hs: 30 } }),
    'jS': Mv.shot({ name: 'Rain Lance', desc: 'Water lance downward.', proj: { speed: 1100, r: 10, dmg: 60, angle: 0.9, kind: 'spear', color: '#3ac8ff', trail: false } }),
  },
  super: Sup.beam({ name: 'Tidal Cannon', desc: 'A pressurized water beam.', beam: { color: '#3ac8ff', dmg: 24 } }),
  ult: { act: 'shot', name: 'LEVIATHAN\'S CALL', desc: 'A wave shot. On hit: the sea serpent rises.', dmg: 1100, template: 'summon', proj: { kind: 'bubble', color: '#3ac8ff', r: 26 }, fx: { el: 'water', creature: 'serpent', color: '#3ac8ff', sky: ['#021020', '#0a3050', '#1a6090'], lines: ['Old friend...', 'Rise.'] } },
  form: { name: 'LEVIATHAN QUEEN', desc: 'Permanent. Water armor, stronger geysers.', armor: 0.85, dmg: 1.12, scale: 1.08, model: { aura: '#3ac8ff', top: '#0a8ac8', hair: { type: 'long', color: '#6ad8ff' }, eyes: { glow: '#9ff' }, cape: { color: '#1a6a9a', inner: '#9ff' } },
    moves: { '2S': Mv.place({ name: 'Twin Geysers', desc: 'Two geysers.', spawn: { kind: 'spike', at: 'enemy', delay: 0.45, count: 2, spacing: 100, stagger: 0.1, dmg: 75, color: '#3ac8ff', fill: '#9ff', height: 240 } }) } },
  assist: '2S',
  lines: { intro: ['You poisoned my sea, {opp}.', 'The tide is turning.', 'Hold your breath.'], win: ['Washed away.', 'The sea is patient. I am not.', 'Back to the depths with you.'], taunt: ['Splash!', 'Drown.'], form: ['The ocean answers!'], ult: ['Rise, Leviathan!'], ultHit: ['Returned to the deep.'] },
});

fighter({
  id: 'grimm', name: 'GRIMM', title: 'The Soul Reaper', side: 'VILLAIN', role: 'Stacker · Scythe', color: '#9aff9a', color2: '#0a1a0a',
  bio: 'Death took a vacation. Grimm was the temp. He has decided he likes the job too much to give it back.',
  quote: 'Everyone has an appointment.', ending: 'Grimm refuses to give the scythe back. Death, returning from vacation, files a complaint. It is still pending.',
  hp: 980, walk: 250, floaty: true, rival: 'seraph',
  model: { skin: '#dcd8d0', top: '#141414', topDark: '#0a0a0a', pants: '#141414', boots: '#0a0a0a', hair: { type: 'hood', color: '#0a0a0a' }, animal: { type: 'skull', color: '#eee8d8', eye: 'rgba(120,255,160,0.9)' }, cape: { color: '#0a0a0a', len: 1.1 }, weapon: { type: 'scythe', color: '#555', tip: '#ccd', glow: '#9aff9a' }, float: true },
  face: { animal: { type: 'skull', color: '#eee8d8', eye: 'rgba(120,255,160,1)' }, hair: { type: 'hood', color: '#0a0a0a' } },
  style: { reach: 1.35, weapon: true, speed: 1.05 },
  passive: ['Soul Harvest', 'Each hit steals a soul (max 10). Each soul gives +3% damage.'],
  onHit(a) { a.souls = Math.min(10, (a.souls || 0) + 1); },
  passiveDmg(f) { return 1 + (f.souls || 0) * 0.03; },
  moves: {
    '5S': Mv.shot({ name: 'Soul Wisp', desc: 'A homing lost soul.', proj: { speed: 480, homing: 2.5, r: 12, dmg: 55, kind: 'skull', color: '#9aff9a', life: 3 } }),
    '6S': Mv.rush({ name: 'Reap', desc: 'Scythe dash that pulls the enemy close.', speed: 1000, frames: 14, hit: { dmg: 90, kb: [-300, -200], pull: true } }),
    '2S': Mv.place({ name: 'Grave Hands', desc: 'Hands burst from the ground.', spawn: { kind: 'spike', at: 'enemy', delay: 0.5, dmg: 80, color: '#9aff9a', fill: '#2a3a2a', status: { slow: 1 } } }),
    '4S': Mv.teleport({ name: 'Phase', desc: 'Fade and reappear behind.', to: 'behind' }),
    'jS': Mv.dive({ name: 'Death\'s Descent', desc: 'Plunging scythe.', vx: 600, vy: 1000, hit: { dmg: 90 } }),
  },
  super: Sup.rush({ name: 'Harvest Moon', desc: 'A crescent of scythe cuts.', hit: { dmg: 28 } }),
  ult: { act: 'rush', name: 'FINAL APPOINTMENT', desc: 'A reaping strike. On hit: a trip to the other side.', dmg: 1150, template: 'dimension', fx: { el: 'soul', world: 'underworld', color: '#9aff9a', sky: ['#000', '#0a1a0a', '#1a3a1a'], lines: ['Your time is up.', 'No refunds.'] } },
  form: { name: 'DEATH INCARNATE', desc: 'Permanent. Starts with 10 souls, lifesteal 15%.', lifesteal: 0.15, dmg: 1.08, scale: 1.12, onStart(f) { f.souls = 10; }, model: { aura: '#9aff9a', cape: { color: '#0a1a0a', len: 1.3 }, wings: { type: 'bat', color: '#0a0a0a', scale: 1 } } },
  assist: '2S',
  lines: { intro: ['Your appointment is today, {opp}.', 'I brought a scythe. You brought a pulse.', 'Sign here.'], win: ['Another soul for the collection.', 'Next!', 'The paperwork is done.'], taunt: ['Tick tock.', 'Boo.'], form: ['Behold death.'], ult: ['Time to go.'], ultHit: ['No refunds.'] },
});

fighter({
  id: 'onyx', name: 'ONYX', title: 'The Gravity Knight', side: 'VILLAIN', role: 'Control · Gravity', color: '#8a7aff', color2: '#0a0a1a',
  bio: 'A knight whose armor was forged in the heart of a neutron star. Every step he takes weighs a thousand tons. He works for Vex, but only because Vex pays in stars.',
  quote: 'Kneel. Gravity insists.', ending: 'Onyx collapses the moon into a paperweight and gives it to Vex as a retirement gift. Vex does not retire.',
  hp: 1120, walk: 210, weight: 0.8, rival: 'cosmo',
  model: { build: 'heavy', skin: '#3a3a4a', top: '#1a1a2a', pants: '#14141e', boots: '#0a0a14', hair: { type: 'helmet', color: '#2a2a3a', visor: '#8a7aff' }, pads: { color: '#2a2a3a', size: 1.4, spikes: '#8a7aff' }, emblem: { shape: 'atom', color: '#8a7aff' }, weapon: { type: 'hammer', color: '#2a2a3a', shaft: '#444', glow: '#8a7aff' }, cape: { color: '#14141e' } },
  face: { hair: { type: 'helmet', color: '#2a2a3a', visor: '#8a7aff' }, expr: 'cold', eyes: '#8a7aff' },
  style: { power: 1.15, speed: 1.15, heavy: true, weapon: true },
  passive: ['Heavy Presence', 'Nearby enemies jump lower and fall faster.'],
  passiveTick(f) { const o = f.opp; if (o && Math.abs(o.x - f.x) < 350 && o.airborne && o.state !== 'hit') o.vy += 12; },
  moves: {
    '5S': Mv.place({ name: 'Gravity Well', desc: 'A pulling singularity.', spawn: { kind: 'blackhole', at: 'front', dx: 300, r: 320, life: 2, dmg: 18 }, cd: 5 }),
    '6S': Mv.rush({ name: 'Collapse Charge', desc: 'Crushing armored charge.', speed: 800, frames: 20, armor: [4, 28], hit: { dmg: 120, kb: [700, -200], wb: true } }),
    '2S': Mv.custom({ name: 'Crush', desc: 'Slams gravity down on the enemy.', s: 16, a: 1, r: 20, ev: { 16: f => { const o = f.opp; if (o) { o.vy = 1600; Combat.place(f, { kind: 'spike', at: 'enemy', delay: 0.15, dmg: 80, color: '#8a7aff', fill: '#1a1a2a', height: 100 }); } } }, ai: { min: 100, max: 900, use: 'zone' } }),
    '4S': Mv.shot({ name: 'Orbit Stone', desc: 'A stone that orbits out and returns.', proj: { speed: 700, r: 16, dmg: 60, kind: 'rock', color: '#4a4a5a', boomerang: 0.6, life: 2.5, trail: false } }),
    'jS': Mv.dive({ name: 'Meteor Fall', desc: 'Heavy downward slam.', vx: 200, vy: 1600, hit: { dmg: 120, gb: true } }),
  },
  super: Sup.place({ name: 'Event Collapse', desc: 'A huge gravity well.', spawn: { kind: 'blackhole', at: 'enemy', r: 500, life: 2.5, dmg: 30 } }),
  ult: { act: 'strike', name: 'PLANET CRUSHER', desc: 'A falling star. On hit: a planet comes down.', dmg: 1200, template: 'meteor', style: 'meteor', color: '#8a7aff', fx: { el: 'void', color: '#8a7aff', sky: ['#02000a', '#0a0a2a', '#2a1a5a'], lines: ['I asked you to kneel.', 'Now the sky will insist.'] } },
  form: { name: 'SINGULARITY KNIGHT', desc: 'Permanent. Super armor, gravity aura.', superArmor: true, armor: 0.8, dmg: 1.15, scale: 1.12, model: { aura: '#8a7aff', auraSize: 1.3, eyes: { glow: '#8a7aff' } } },
  assist: '5S',
  lines: { intro: ['Kneel, {opp}.', 'Every step I take shakes the earth.', 'Vex sends his regards. Heavily.'], win: ['Crushed.', 'Gravity always wins.', 'Stay down. Literally.'], taunt: ['Heavy.', 'Kneel.'], form: ['Singularity.'], ult: ['Planet crusher.'], ultHit: ['Flattened.'] },
});

fighter({
  id: 'pixel', name: 'PIXEL', title: 'The Glitched Gamer', side: 'HERO', role: 'Trickster · Respawn', color: '#5aff8a', color2: '#1a1a3a',
  bio: 'A girl who fell into a cursed 8-bit console and came out made of pixels. She respawns, collects power-ups and treats every fight like a speedrun.',
  quote: 'Player 2 has entered the game!', ending: 'Pixel beats the final boss, the credits roll, and she realizes she is still in the game. She hits NEW GAME+ and grins.',
  hp: 900, walk: 300, scale: 0.9, rival: 'cipher',
  model: { build: 'small', skin: '#f0c8a0', top: '#2a8a4a', pants: '#1a1a3a', boots: '#fff', hair: { type: 'twintails', color: '#ff5aaa' }, hat: { type: 'cap', color: '#5aff8a' }, emblem: { shape: 'star', color: '#ffd35a' }, weapon: { type: 'orb', color: '#5aff8a' } },
  face: { expr: 'grin', eyes: '#5aff8a', hair: { type: 'twintails', color: '#ff5aaa' }, hat: { type: 'cap', color: '#5aff8a' } },
  style: { speed: 0.85, power: 0.9 },
  passive: ['Extra Life', 'Once per round, a lethal hit leaves her at 1 HP with 2s of invincibility.'],
  onHurt(t) { if (t.hp <= 0 && !t.oneUp) { t.oneUp = true; t.hp = 1; t.invul = 120; Game.popWorld(t.x, t.y - t.h - 40, '1-UP!', '#5aff8a', 30); Sfx.confirm(); } },
  moves: {
    '5S': Mv.shot({ name: 'Pixel Shot', desc: 'Bouncing 8-bit block.', proj: { speed: 700, r: 10, dmg: 55, kind: 'pixel', color: '#5aff8a', g: 800, angle: -0.3, life: 2.5 } }),
    '6S': Mv.rush({ name: 'Speedrun', desc: 'Frame-perfect dash.', speed: 1500, frames: 10, pass: true, hit: { dmg: 70 } }),
    '2S': Mv.buff({ name: 'Power-Up', desc: 'Grabs a random power-up.', effects: { power: true, haste: true }, dur: 4, cd: 12 }),
    '4S': Mv.teleport({ name: 'Warp Pipe', desc: 'Warps above the enemy.', to: 'above' }),
    'jS': Mv.dive({ name: 'Stomp', desc: 'Jump-on-their-head stomp. Bounces.', vx: 300, vy: 1200, hit: { dmg: 70, kb: [100, -800] } }),
  },
  super: Sup.barrage({ name: 'Bullet Hell', desc: 'A screen full of pixels.', volleys: 12, proj: { kind: 'pixel', color: '#5aff8a', dmg: 22 } }),
  ult: { act: 'rush', name: 'GAME OVER', desc: 'A glitch tackle. On hit: trapped in the console.', dmg: 1100, template: 'dimension', fx: { el: 'pixel', world: 'console', color: '#5aff8a', sky: ['#000', '#0a1a0a', '#1a3a1a'], lines: ['Loading final boss...', 'GAME OVER.'] } },
  form: { name: 'FINAL BOSS MODE', desc: 'Permanent. Glitch aura, bigger shots, 1-UP restored.', dmg: 1.15, scale: 1.1, onStart(f) { f.oneUp = false; }, model: { aura: '#5aff8a', eyes: { glow: '#5aff8a' }, top: '#1a1a3a', hair: { type: 'twintails', color: '#5aff8a' } } },
  assist: '5S',
  lines: { intro: ['New challenger, {opp}!', "Let's speedrun this.", 'Press START to lose!'], win: ['GG EZ!', 'New high score!', 'Achievement unlocked: beat {opp}.'], taunt: ['Lag!', 'Noob!'], form: ['Boss mode unlocked!'], ult: ['GAME OVER!'], ultHit: ['Insert coin to continue.'] },
});

fighter({
  id: 'striker', name: 'STRIKER', title: 'The Golden Boot', side: 'HERO', role: 'Zoner · Kicks', color: '#ffd35a', color2: '#1a5a2a',
  bio: 'The greatest footballer who ever lived, until a meteor turned his boots gold. Now every kick lands with the force of a stadium.',
  quote: 'Goal!', ending: 'Striker scores the winning goal of the World Cup from the Moon. FIFA rules it offside.',
  hp: 1000, walk: 290, rival: 'roo',
  model: { build: 'athletic', skin: '#a07050', top: '#1a8a3a', pants: '#fff', boots: '#ffd35a', hair: { type: 'short', color: '#1a1a1a' }, emblem: { shape: 'ball', color: '#fff' }, stripes: '#fff', kneepads: '#eee', weapon: { type: 'ball' } },
  face: { expr: 'grin', eyes: '#5a3a1a', hair: { type: 'short', color: '#1a1a1a' } },
  style: { reach: 1.1, poses: { '5L': 'kick', '5M': 'kick', '2M': 'sweep' } },
  passive: ['Playmaker', 'Projectiles hit harder at long range.'],
  moves: {
    '5S': Mv.shot({ name: 'Power Shot', desc: 'A rocket of a kick.', pose: 'kick', proj: { speed: 950, r: 12, dmg: 70, kind: 'ball', color: '#fff', trail: false } }),
    '6S': Mv.rush({ name: 'Slide Tackle', desc: 'Low sliding tackle.', pose: 'sweep', speed: 1100, frames: 16, hit: { dmg: 90, guard: 'low', kb: [300, -500], box: [0, -40, 70, 40] } }),
    '2S': Mv.shot({ name: 'Lob', desc: 'High arcing ball.', pose: 'kick', proj: { speed: 700, angle: -0.8, g: 1200, r: 12, dmg: 60, kind: 'ball', color: '#fff', trail: false } }),
    '4S': Mv.rising({ name: 'Bicycle Kick', desc: 'Overhead bicycle kick anti-air.', pose: 'air_mid', hit: { dmg: 44, multi: 3 } }),
    'jS': Mv.shot({ name: 'Volley', desc: 'Kicks the ball down at an angle.', pose: 'air_mid', proj: { speed: 1000, r: 12, dmg: 65, angle: 0.5, kind: 'ball', color: '#fff', trail: false } }),
  },
  super: Sup.barrage({ name: 'Penalty Shootout', desc: 'Eight golden shots.', proj: { kind: 'ball', color: '#ffd35a', dmg: 30, r: 13 } }),
  ult: { act: 'shot', name: 'GOLDEN GOAL', desc: 'The perfect shot. On hit: a stadium of pain.', dmg: 1100, template: 'barrage', proj: { kind: 'ball', color: '#ffd35a', r: 22 }, fx: { el: 'ball', color: '#ffd35a', sky: ['#0a1a0a', '#1a4a1a', '#4a8a3a'], lines: ['Stadium lights on.', 'GOOOOOOAL!'] } },
  form: { name: 'HALL OF FAME', desc: 'Permanent. Golden boots: faster, stronger kicks.', dmg: 1.15, speed: 1.1, projSpeed: 1.2, model: { top: '#ffd35a', boots: '#fff6c0', aura: '#ffd35a', stripes: '#1a8a3a' } },
  passiveDmg(f, t) { return t && Math.abs(t.x - f.x) > 400 ? 1.15 : 1; },
  assist: '5S',
  lines: { intro: ["Kick-off, {opp}!", "I've never missed a penalty.", 'Referee, start the clock.'], win: ['GOOOAL!', 'Top corner!', 'Man of the match!'], taunt: ['Offside!', 'Nutmeg!'], form: ['Hall of Fame!'], ult: ['Golden goal!'], ultHit: ['And the crowd goes wild!'] },
});
