// ============================================================
//  MOONKAI — VIPER, the Venom Fist. Pixel remake + a real kit.
//
//  ENVENOM (mark on the foe, max 5)  every special lands a dose. At 5 the foe is ENVENOMED for 4s: they take 25% more from everything,
//                                    cannot heal, and a final dose bursts for 70.
//  TOXIN (passive)   every hit poisons; poisoned enemies take 15% more damage (as before).
//  HYDRA   HYDRA SPIT (5S) three heads spit at once, NINE FANGS LUNGE (6S) a leaping strike, SERPENT NEST (2S) a pit and the snakes in it,
//          CONSTRICT (4S) a coil that holds, DIVING FANG (jS).   MOTHER OF HEADS (form ult).
// ============================================================
(() => {
  const sfx = PxKit.sfx, def = charById('viper');
  Object.assign(Sfx, {
    vpHiss(d = 0, dur = .9) { this.nsweep({ f0: 7000, f1: 2500, dur, vol: .16, type: 'highpass', delay: d, wet: .4 }); this.voice({ f: 150, to: 90, dur, vol: .08, type: 'sawtooth', lp: 400, delay: d }); },
    vpBite(d = 0) { this.nsweep({ f0: 3000, f1: 400, dur: .12, vol: .22, type: 'bandpass', q: 2, delay: d }); this.fm({ f: 260, ratio: 3, index: 150, dur: .18, vol: .1, delay: d }); },
    vpSpit(d = 0) { this.nsweep({ f0: 1200, f1: 3600, dur: .16, vol: .16, q: 1.5, delay: d, wet: .3 }); this.voice({ f: 300, to: 700, dur: .12, vol: .06, delay: d }); },
    vpRattle(d = 0, dur = 1) { this.crackle({ dur, vol: .12, delay: d, lo: 3000, hi: 9000 }); },
    vpRoar(d = 0, dur = 1.6) { this.voice({ f: 110, to: 70, dur, vol: .3, type: 'sawtooth', lp: 700, n: 5, det: 50, delay: d, wet: .5 }); this.vpHiss(d, dur); this.sub({ f: 60, to: 30, dur: dur * .7, vol: .35, delay: d }); },
  });
  PxModel.install(def, { post(c, v, P, s, m) { if (v.transformed) { const t = v.anim || 0; c.save(); for (let i = 0; i < 3; i++) { const a = -2.2 + i * .9 + Math.sin(t * 3 + i) * .15; c.strokeStyle = '#2a7a1a'; c.lineWidth = 5; c.lineCap = 'round'; c.beginPath(); c.moveTo(P.sh[0], P.sh[1] + 4); c.quadraticCurveTo(P.sh[0] + Math.cos(a) * 24, P.sh[1] + Math.sin(a) * 30, P.sh[0] + Math.cos(a + .3) * 40, P.sh[1] + Math.sin(a + .3) * 50); c.stroke(); c.fillStyle = '#7aff3a'; c.beginPath(); c.arc(P.sh[0] + Math.cos(a + .3) * 40, P.sh[1] + Math.sin(a + .3) * 50, 5, 0, 7); c.fill(); } c.restore(); } } });
  const dose = (a, t, n = 1) => { if (!t || t.state === 'ko') return; t.status.poison = Math.max(t.status.poison || 0, 3); Combat.mark(t, a, 'envenom', n, { max: 5, dur: 9, color: '#7aff3a', label: 'VENOM', onMax: tt => { delete tt.marks.envenom; tt.status.weaken = Math.max(tt.status.weaken || 0, 4); tt.status.poison = 6; Combat.resolveHit(tt, a, H_({ dmg: 70, guard: 'mid', hs: 18, kb: [0, -240], launch: true, sfx: 'h' }), { proj: true, fromX: tt.x }); Game.popWorld(tt.x, tt.y - tt.h - 40, 'ENVENOMED', '#7aff3a', 26); sfx('vpHiss', 0, 1.4); Cam.shake = 8; } }); };
  Rw2.merge(def, { passive: ['Toxin', 'Every hit poisons; poisoned enemies take 15% more. Every special lands a dose (max 5): at 5 the foe is ENVENOMED: weakened, poisoned hard, and bursts for 70.'], onHit: (a, t) => { if (a.move && a.move.kind === 'special') dose(a, t); } });
  Combat.hz.vpNest = function (h) { const f = h.owner; if (!f) return false; if (h.t % 20 === 10) for (const e of Combat.targets(f.side)) if (Math.abs(e.x - h.x) < h.r && e.y > -50) { Combat.resolveHit(e, f, H_({ dmg: 22, guard: 'low', hs: 8, kb: [0, -60], sfx: 'l', status: { slow: .5 } }), { proj: true, fromX: h.x }); dose(f, e); sfx('vpBite'); } return h.t < h.life; };
  Combat.drawHz.vpNest = (c, h) => { const k = Math.min(1, h.t / 10, (h.life - h.t) / 16); c.save(); c.globalAlpha = k; c.fillStyle = 'rgba(20,50,12,.7)'; c.beginPath(); c.ellipse(h.x, -3, h.r, 10, 0, 0, 7); c.fill(); for (let i = 0; i < 5; i++) { const x = h.x + (i - 2) * h.r / 2.4, w = Math.sin(h.t * .25 + i * 1.3); c.strokeStyle = i % 2 ? '#2a7a1a' : '#5aba2a'; c.lineWidth = 6; c.lineCap = 'round'; c.beginPath(); c.moveTo(x, 0); c.quadraticCurveTo(x + w * 14, -24, x + w * 6, -46 - (i % 2) * 10); c.stroke(); c.fillStyle = '#7aff3a'; c.beginPath(); c.arc(x + w * 6, -48 - (i % 2) * 10, 5, 0, 7); c.fill(); c.fillStyle = '#ff2a2a'; c.fillRect(x + w * 6 - 1, -50 - (i % 2) * 10, 2, 2); } c.restore(); };
  Combat.hz.vpCoil = function (h) { const f = h.owner; if (!f) return false; const t = h.tgt; if (!t || t.state === 'ko') return false; t.x = h.x; t.status.stun = Math.max(t.status.stun || 0, .12); if (h.t % 20 === 10) { Combat.resolveHit(t, f, H_({ dmg: 30, guard: 'mid', hs: 6, kb: [0, 0], sfx: 'm' }), { proj: true, fromX: h.x }); dose(f, t); sfx('vpBite'); } return h.t < h.life; };
  Combat.drawHz.vpCoil = (c, h) => { const t = h.tgt; if (!t) return; c.save(); c.strokeStyle = '#3a8a1a'; c.lineWidth = 7; c.lineCap = 'round'; for (let i = 0; i < 4; i++) { const y = t.y - 20 - i * 20; c.beginPath(); c.ellipse(t.x, y, t.w * .85, 7, Math.sin(h.t * .2 + i) * .2, 0, 6.28); c.stroke(); } c.fillStyle = '#7aff3a'; c.beginPath(); c.arc(t.x + 18, t.y - t.h - 12, 8, 0, 7); c.fill(); c.restore(); };

  const F5 = Mv.shot({ name: 'Hydra Spit', desc: 'Hydra: three heads spit at once in a fan, each landing a dose.', proj: { speed: 880, r: 12, dmg: 40, count: 3, spread: .5, kind: 'poison', color: '#7aff3a', core: '#eaffd0', status: { poison: 3 }, onHit: (t, p) => dose(p.owner, t), life: 1.4 }, ev: { 3: () => sfx('vpHiss', 0, .5), 12: () => sfx('vpSpit') } });
  const F6 = mk({ name: 'Nine Fangs Lunge', desc: 'Hydra: a leaping lunge and nine fangs in a second. Each is a dose.', pose: 'dash', s: 8, a: 27, r: 22, vel: [[8, 17, 900, -300]], ai: { min: 100, max: 700, use: 'approach' }, hit: { dmg: 12, multi: 9, every: 3, box: [0, -100, 100, 90], kb: [60, -40], hs: 8, status: { poison: 2 } }, ev: { 1: () => sfx('vpHiss', 0, .5), 8: () => sfx('vpBite'), 14: () => sfx('vpBite'), 20: () => sfx('vpBite'), 26: () => sfx('vpBite') }, onHit: (a, t) => dose(a, t, .4) });
  const F2 = mk({ name: 'Serpent Nest', desc: 'Hydra: a pit of snakes under the foe for 5s; they bite whoever stands in it.', pose: 'cast_up', s: 16, a: 1, r: 24, cd: 7, ai: { min: 100, max: 1000, use: 'zone' }, ev: { 16: f => { const t = f.opp; if (!t) return; Combat.addHazard({ kind: 'vpNest', owner: f, side: f.side, x: clamp(t.x, 100, Arena.stage.width - 100), r: 160, life: 300 }); sfx('vpRattle'); sfx('vpHiss'); } } });
  const F4 = mk({ name: 'Constrict', desc: 'Hydra: a coil that seizes the foe and holds them in place for 1.2s while it squeezes. A dose per squeeze.', pose: 'cast', s: 14, a: 1, r: 26, cd: 8, ai: { min: 100, max: 500, use: 'zone' }, ev: { 14: f => { const t = f.opp; if (!t || Math.abs(t.x - f.x) > 480 || t.y < -120) return; Combat.addHazard({ kind: 'vpCoil', owner: f, side: f.side, x: t.x, tgt: t, life: 72 }); sfx('vpHiss'); } } });
  const FJ = Mv.dive({ name: 'Diving Fang', desc: 'Hydra: a dive with three heads; each bites.', vx: 600, vy: 1400, hit: { dmg: 92, gb: true, status: { poison: 3 } }, ev: { 1: () => sfx('vpHiss', 0, .4) }, onHit: (a, t) => { dose(a, t, 2); sfx('vpBite'); } });
  const FU = PxKit.ult({ id: 'viper_fult', name: 'MOTHER OF HEADS', desc: 'Hydra: nine heads rise from the ground, each with a different poison. Blockable. Must connect.', pose: 'cast_up', s: 50, dmg: 1280, color: '#7aff3a',
    cutscene: (a, t) => PxKit.cineUlt(a, t, { name: 'MOTHER OF HEADS', dur: 8.6, tc: [1.0, 4.6], tf: 5.4, c1: '#7aff3a', c2: '#eaffd0', c3: '#061a04', motif: 'pillar', pose: ['idle', 'cast_up', 'cast_up', 'victory'], actorForm: true, cap1: 'Cut one off.', cap2: 'Nine more.', title: 'MOTHER OF HEADS', sub: 'NINE POISONS', size: 98,
      cues: [[0, () => sfx('vpRattle', 0, 2)], [1.4, () => sfx('vpRoar')], [5.4, () => { sfx('vpBite'); sfx('vpBite', .1); sfx('vpHiss', .2, 1.4); sfx('boom'); }]],
      bg: (x, t, k) => PxKit.sky(x, t, { top: '#041004', bot: '#1c4a10', moon: { x: .5, y: .22, r: 70, col: '#d0ff90' }, mount: '#0a2a08', fog: 'rgba(122,255,58,0.12)', stars: '#b0ff7a' }, k) }) });
  FU.ev = PxKit.zoneEv(FU, { at: 50, w: 900, h: 340, back: 400, start: f => { f.say('SSSS.', 90); sfx('vpRoar'); }, fire: f => { Rw2.row(f, 9, 100, { from: 'foe', r: 40, life: 6, stagger: 3, color: '#7aff3a', dmg: 0, shake: 3 }); const t = f.opp; if (t) dose(f, t, 5); Cam.shake = 18; sfx('vpBite'); sfx('boom'); } });
  PxKit.formKit(def, { moves: { '5S': F5, '6S': F6, '2S': F2, '4S': F4, 'jS': FJ }, ult: FU, desc: 'Permanent. Serpent aura: poison ticks harder. New moveset: Hydra Spit, Nine Fangs Lunge, Serpent Nest, Constrict, Diving Fang, and the ultimate MOTHER OF HEADS.' });

  def.ult.ult.cutscene = (a, t) => PxKit.cineUlt(a, t, { name: 'HYDRA', dur: 8.0, tc: [1.0, 4.0], tf: 4.8, c1: '#7aff3a', c2: '#eaffd0', c3: '#061a04', motif: 'rush', pose: ['idle', 'cast', 'dash', 'victory'], cap1: 'One bite.', cap2: 'Then nine heads.', title: 'HYDRA', sub: 'SSSS', size: 112,
    cues: [[0, () => sfx('vpHiss', 0, 1.4)], [1.4, () => sfx('vpRattle', 0, 1.6)], [4.8, () => { sfx('vpBite'); sfx('vpRoar'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#041004', bot: '#1c4a10', moon: { x: .7, y: .22, r: 60, col: '#d0ff90' }, mount: '#0a2a08', fog: 'rgba(122,255,58,0.1)' }, k) });
  def.transformCutscene = f => PxKit.cineForm(f, { name: 'HYDRA', dur: 6.4, tc: [1.0, 3.4], tf: 3.7, c1: '#7aff3a', c2: '#eaffd0', c3: '#061a04', motif: 'rise', pose: ['idle', 'cast_up', 'victory'], lift: 24, cap1: 'One head thinks.', cap2: 'Nine decide.', title: 'HYDRA', sub: 'VIPER', size: 116,
    cues: [[0, () => sfx('vpHiss', 0, 1.4)], [1.4, () => sfx('vpRattle', 0, 1.6)], [3.7, () => { sfx('vpRoar'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#041004', bot: '#1c4a10', mount: '#0a2a08', fog: 'rgba(122,255,58,0.12)', stars: '#b0ff7a' }, k) });
})();
