// ============================================================
//  MOONKAI — HEX, the Hedge Witch. Pixel remake + a real kit.
//
//  HEXES (mark on the foe, max 3)  every special she lands adds a hex. At 3 the hexes BIND: the foe is weakened (−25%), confused and
//                                  burns with green fire for 3s.
//  CURSE (passive)   hits have a chance to weaken (as before).
//  COVEN MOTHER      TRIPLE HEX (5S) three witches' bolts from behind her, CAULDRON SURGE (6S) a boiling wave of poison,
//                    THORN PRISON (2S) a ring of roots around the foe, POLYMORPH (4S) swaps and turns the foe into a frog,
//                    BROOM BARRAGE (jS) potions from above.   COVEN'S TRIBUNAL (form ult)  three witches pass sentence.
// ============================================================
(() => {
  const sfx = PxKit.sfx, def = charById('hex');
  Object.assign(Sfx, {
    hxCast(d = 0) { this.fm({ f: 330, ratio: 1.5, index: 180, dur: .5, vol: .12, delay: d, wet: .8 }); this.nsweep({ f0: 600, f1: 3000, dur: .3, vol: .12, delay: d, wet: .6 }); },
    hxCackle(d = 0) { for (let i = 0; i < 5; i++) this.voice({ f: 520 + (i % 2) * 140, to: 380, dur: .12, vol: .1, type: 'sawtooth', lp: 2200, delay: d + i * .13, wet: .5 }); },
    hxBubble(d = 0, n = 6) { for (let i = 0; i < n; i++) this.voice({ f: 200 + Math.random() * 300, to: 600, dur: .1, vol: .08, delay: d + i * .09, wet: .3 }); },
    hxBind(d = 0) { this.chord({ notes: [147, 175, 233], dur: 1.2, vol: .2, type: 'sawtooth', lp: 900, delay: d, wet: .8, det: 12 }); this.crackle({ dur: .4, vol: .1, delay: d, lo: 400, hi: 5000 }); },
    hxToad(d = 0) { this.voice({ f: 180, to: 90, dur: .2, vol: .2, type: 'square', lp: 700, delay: d }); this.voice({ f: 200, to: 100, dur: .2, vol: .2, type: 'square', lp: 700, delay: d + .25 }); },
    hxTribunal(d = 0) { this.chord({ notes: [98, 147, 185, 233], dur: 3, vol: .22, type: 'sawtooth', lp: 800, delay: d, wet: .9, det: 16 }); this.hxCackle(d + .2); this.impact(.8, d + 1.2); },
  });
  PxModel.install(def, { post(c, v, P, s, m) { const t = v.anim || 0; if (v.transformed) { c.save(); c.globalCompositeOperation = 'lighter'; for (let i = 0; i < 5; i++) { c.fillStyle = i % 2 ? 'rgba(154,90,255,.8)' : 'rgba(150,255,120,.8)'; c.fillRect(Math.round(P.hip[0] - 24 + Math.sin(t * 2 + i) * 22), Math.round(P.hip[1] - 20 - ((t * 40 + i * 25) % 90)), 4, 4); } c.restore(); } } });
  const hexIt = (a, t, n = 1) => { if (!t || t.state === 'ko') return; Combat.mark(t, a, 'hex', n, { max: 3, dur: 9, color: '#9a5aff', label: 'HEX', onMax: tt => { delete tt.marks.hex; tt.status.weaken = Math.max(tt.status.weaken || 0, 3); tt.status.confuse = Math.max(tt.status.confuse || 0, 1.5); tt.status.burn = Math.max(tt.status.burn || 0, 3); Game.popWorld(tt.x, tt.y - tt.h - 40, 'BOUND', '#9a5aff', 26); sfx('hxBind'); Cam.shake = 6; } }); };
  Rw2.merge(def, { passive: ['Curse', 'Hits can weaken. Every special adds a HEX to the foe (max 3): at 3 they are BOUND: weakened, confused, and burning green for 3s.'], onHit: (a, t) => { if (a.move && a.move.kind === 'special') hexIt(a, t); } });
  Combat.hz.hxSurge = function (h) { const f = h.owner; if (!f) return false; h.x += h.dir * 9; for (const e of Combat.targets(f.side)) if (Math.abs(e.x - h.x) < 60 && e.y > -140 && !h.hit.has(e)) { h.hit.add(e); Combat.resolveHit(e, f, H_({ dmg: 72, guard: 'low', hs: 20, kb: [200 * h.dir, -520], launch: true, status: { poison: 3 }, sfx: 'h' }), { proj: true, fromX: h.x, move: h.move }); hexIt(f, e); } return h.t < h.life && h.x > 0 && h.x < Arena.stage.width; };
  Combat.drawHz.hxSurge = (c, h) => { c.save(); c.globalCompositeOperation = 'lighter'; for (let i = 0; i < 16; i++) { const x = h.x - h.dir * (i * 10), y = -(Math.sin(h.t * .4 + i) * 10 + 20 + i * 2); c.fillStyle = i % 3 ? 'rgba(150,255,120,.8)' : 'rgba(154,90,255,.8)'; c.beginPath(); c.arc(x, y, 12 - i * .5, 0, 7); c.fill(); } c.restore(); };
  Combat.hz.hxThorns = function (h) { const f = h.owner; if (!f) return false; const t = h.tgt; if (t && t.state !== 'ko') { for (const s of [-1, 1]) { const wallx = h.x + s * 110; if ((t.x - wallx) * s > 0) { t.x = wallx; } } if (h.t % 26 === 13 && Math.abs(t.x - h.x) < 120) { Combat.resolveHit(t, f, H_({ dmg: 22, guard: 'low', hs: 8, kb: [0, 0], sfx: 'l', status: { poison: 1 } }), { proj: true, fromX: h.x }); hexIt(f, t); } } return h.t < h.life; };
  Combat.drawHz.hxThorns = (c, h) => { const k = Math.min(1, h.t / 10, (h.life - h.t) / 12); c.save(); c.globalAlpha = k; for (const s of [-1, 1]) for (let j = 0; j < 4; j++) { const x = h.x + s * (100 + j * 6); c.strokeStyle = '#2a5a1a'; c.lineWidth = 5 - j; c.beginPath(); c.moveTo(x, 0); c.quadraticCurveTo(x - s * 14, -50, x + s * 6 * (j - 1.5), -130 + j * 10); c.stroke(); c.fillStyle = '#9a5aff'; c.fillRect(x + s * 6 * (j - 1.5) - 3, -134 + j * 10, 6, 6); } c.restore(); };

  const F5 = mk({ name: 'Triple Hex', desc: 'Coven Mother: her two sisters appear behind her and all three cast: three bolts, each adding a HEX.', pose: 'cast', s: 14, a: 1, r: 24, cd: 3, ai: { min: 150, max: 1400, use: 'zone' }, ev: { 3: () => sfx('hxCackle'), 14: f => { for (let i = 0; i < 3; i++) Game.later(i * .12, () => { Combat.fireShots(f, { speed: 900, r: 13, dmg: 44, kind: 'orb', color: i === 1 ? '#9a5aff' : '#7aff6a', core: '#fff', status: { weaken: 3 }, angle: (i - 1) * .22, offY: -30 + i * 30, onHit: (t, p) => hexIt(p.owner, t) }); sfx('hxCast', 0); }); } } });
  const F6 = mk({ name: 'Cauldron Surge', desc: 'Coven Mother: the cauldron boils over and a wave of poison rolls across the floor.', pose: 'slam', s: 16, a: 1, r: 26, cd: 5, ai: { min: 100, max: 1100, use: 'zone' }, ev: { 3: () => sfx('hxBubble'), 16: f => { Combat.addHazard({ kind: 'hxSurge', owner: f, side: f.side, x: f.x + f.facing * 50, dir: f.facing, life: 120, hit: new Set(), move: F6 }); sfx('hxBubble', 0, 10); Cam.shake = 5; } } });
  const F2 = mk({ name: 'Thorn Prison', desc: 'Coven Mother: a ring of living thorns around the foe for 3s; they cannot walk out of it.', pose: 'cast_up', s: 16, a: 1, r: 24, cd: 7, ai: { min: 100, max: 900, use: 'zone' }, ev: { 16: f => { const t = f.opp; if (!t) return; Combat.addHazard({ kind: 'hxThorns', owner: f, side: f.side, x: clamp(t.x, 140, Arena.stage.width - 140), tgt: t, life: 180 }); sfx('hxCast'); } } });
  const F4 = mk({ name: 'Polymorph', desc: 'Coven Mother: swaps places and turns the foe into a frog for 1.4s: stunned, confused, and croaking.', pose: 'cast', s: 14, a: 1, r: 28, cd: 9, ai: { min: 150, max: 800, use: 'trap' }, ev: { 14: f => { const t = f.opp; if (!t) return; Combat.swap(f, { confuse: 2, dmg: 30 }); t.status.stun = Math.max(t.status.stun || 0, 1.4); hexIt(f, t, 2); Game.popWorld(t.x, t.y - t.h - 40, 'RIBBIT', '#7aff6a', 24); sfx('hxToad'); } } });
  const FJ = Mv.shot({ name: 'Broom Barrage', desc: 'Coven Mother: a pass over the foe, dropping six potions.', proj: { speed: 700, angle: 1.3, spread: 1.0, count: 6, g: 900, r: 11, dmg: 36, kind: 'bomb', color: '#7aff6a', explode: 60, status: { poison: 2 } }, ev: { 2: () => sfx('hxCackle') } }); FJ.air = true;
  const FU = PxKit.ult({ id: 'hex_fult', name: "COVEN'S TRIBUNAL", desc: 'Coven Mother: three witches pass sentence. A verdict of green fire and thorns. Blockable. Must connect.', pose: 'cast_up', s: 54, dmg: 1280, color: '#9a5aff',
    cutscene: (a, t) => PxKit.cineUlt(a, t, { name: "COVEN'S TRIBUNAL", dur: 8.6, tc: [1.0, 4.6], tf: 5.4, c1: '#7aff6a', c2: '#c8a0ff', c3: '#100620', motif: 'pillar', pose: ['idle', 'cast_up', 'cast_up', 'victory'], actorForm: true, cap1: 'Three of us. One verdict.', cap2: 'Guilty, dear.', title: "COVEN'S TRIBUNAL", sub: 'SO IT IS CURSED', size: 94,
      cues: [[0, () => sfx('hxCackle')], [1.4, () => sfx('hxTribunal')], [5.4, () => { sfx('hxBind'); sfx('hxCackle', .2); sfx('boom'); }]],
      bg: (x, t, k) => PxKit.sky(x, t, { top: '#08020e', bot: '#240c40', moon: { x: .5, y: .22, r: 90, col: '#d8c0ff' }, stars: '#c8a0ff', mount: '#100620', embers: '#7aff6a', fog: 'rgba(122,255,106,0.08)' }, k) }) });
  FU.ev = PxKit.trackEv(FU, { at: 54, r: 160, color: '#7aff6a', start: f => { f.say('Order!', 80); sfx('hxTribunal'); }, fire: (f, x) => { for (const e of Combat.targets(f.side)) if (Math.abs(e.x - x) < 200) { hexIt(f, e, 3); e.status.burn = 4; } Combat.addHazard({ kind: 'aurPillar', owner: f, side: f.side, x, r: 160, life: 40, color: '#7aff6a', giant: true }); Cam.shake = 20; sfx('hxBind'); sfx('boom'); } });
  PxKit.formKit(def, { moves: { '5S': F5, '6S': F6, '2S': F2, '4S': F4, 'jS': FJ }, ult: FU, desc: 'Permanent. Floats, curses stack harder. New moveset: Triple Hex, Cauldron Surge, Thorn Prison, Polymorph, Broom Barrage, and the ultimate COVEN\'S TRIBUNAL.' });

  def.ult.ult.cutscene = (a, t) => PxKit.cineUlt(a, t, { name: 'WITCHING HOUR', dur: 8.0, tc: [1.0, 4.0], tf: 4.8, c1: '#9a5aff', c2: '#c8f0a0', c3: '#100620', motif: 'pillar', pose: ['idle', 'cast_up', 'cast_up', 'victory'], cap1: 'The clock strikes thirteen.', cap2: 'Nobody told you?', title: 'WITCHING HOUR', sub: 'MIDNIGHT, TWICE', size: 96,
    cues: [[0, () => sfx('hxBubble')], [1.4, () => sfx('hxTribunal')], [4.8, () => { sfx('hxBind'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#08020e', bot: '#240c40', moon: { x: .5, y: .22, r: 100, col: '#e0d0ff' }, stars: '#c8a0ff', mount: '#100620', embers: '#9a5aff' }, k) });
  def.transformCutscene = f => PxKit.cineForm(f, { name: 'COVEN MOTHER', dur: 6.6, tc: [1.0, 3.6], tf: 3.9, c1: '#9a5aff', c2: '#7aff6a', c3: '#100620', motif: 'rise', pose: ['idle', 'cast_up', 'victory'], lift: 40, cap1: 'One witch is a rumor.', cap2: 'Three is a coven.', title: 'COVEN MOTHER', sub: 'HEX', size: 100,
    cues: [[0, () => sfx('hxBubble')], [1.4, () => sfx('hxTribunal')], [3.9, () => { sfx('hxBind'); sfx('hxCackle'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#08020e', bot: '#240c40', moon: { x: .5, y: .22, r: 90, col: '#e0d0ff' }, stars: '#c8a0ff', mount: '#100620' }, k) });
})();
