// ============================================================
//  MOONKAI — SPECTRE, the Unquiet. Pixel remake + a real kit.
//
//  HAUNTING (mark on the foe, max 3)  every special adds a haunting. At 3 the poltergeist STRIKES: a rain of furniture, 90 damage,
//                                     and the foe is shaken (stunned briefly).
//  INTANGIBLE (passive)  dashing makes him intangible to projectiles (as before).
//  POLTERGEIST   SPECTRAL VOLLEY (5S) five ecto bullets through walls, PHASE SLASH (6S) passes through twice, DEEP POSSESSION (2S) swaps
//                bodies for a moment, POLTERGEIST WAVE (4S) a table, a chair, a piano, HAUNT PLUNGE (jS).  DEAD OF NIGHT (form ult).
// ============================================================
(() => {
  const sfx = PxKit.sfx, def = charById('spectre');
  Object.assign(Sfx, {
    spWail(d = 0, dur = 1.4) { this.voice({ f: 700, to: 340, dur, vol: .12, type: 'sawtooth', lp: 2200, n: 3, det: 70, delay: d, wet: .95 }); this.nsweep({ f0: 1800, f1: 400, dur, vol: .08, q: 3, delay: d, wet: .9 }); },
    spPhase(d = 0) { this.nsweep({ f0: 5000, f1: 500, dur: .25, vol: .14, delay: d, wet: .7 }); this.voice({ f: 800, to: 200, dur: .25, vol: .08, type: 'sine', delay: d, wet: .8 }); },
    spCrash(d = 0) { this.impact(.8, d); this.fm({ f: 300, ratio: 3.3, index: 250, dur: .4, vol: .12, delay: d, wet: .3 }); this.crackle({ dur: .3, vol: .1, delay: d, lo: 300, hi: 4000 }); },
    spChains(d = 0) { for (let i = 0; i < 5; i++) this.fm({ f: 900 + i * 130, ratio: 5.1, index: 140, dur: .08, vol: .07, delay: d + i * .07, wet: .5 }); },
    spMidnight(d = 0) { for (let i = 0; i < 12; i++) this.fm({ f: 520, ratio: 2, index: 40, dur: 1.2, vol: .12, delay: d + i * .6, wet: .95 }); this.chord({ notes: [87, 104, 131], dur: 6, vol: .14, type: 'sine', delay: d, wet: .95 }); },
  });
  PxModel.install(def, {});
  const haunt = (a, t, n = 1) => { if (!t || t.state === 'ko') return; Combat.mark(t, a, 'haunt', n, { max: 3, dur: 9, color: '#aac0ff', label: 'HAUNT', onMax: tt => { delete tt.marks.haunt; Game.popWorld(tt.x, tt.y - tt.h - 40, 'POLTERGEIST', '#aac0ff', 26); sfx('spCrash'); Combat.resolveHit(tt, a, H_({ dmg: 90, guard: 'mid', hs: 20, kb: [0, -300], launch: true, stun: .6, sfx: 'h' }), { proj: true, fromX: tt.x }); for (let i = 0; i < 6; i++) Game.fx.burst(tt.x + rand(-50, 50), -130 + rand(-30, 30), 6, { color: ['#aac0ff', '#fff', '#6a5a4a'], size: 8, speed: 300, life: .5 }); Cam.shake = 10; } }); };
  Rw2.merge(def, { passive: ['Intangible', 'Dashing makes him intangible to projectiles. Every special adds a HAUNT (max 3); at 3 the poltergeist strikes for 90 and stuns.'], onHit: (a, t) => { if (a.move && a.move.kind === 'special') haunt(a, t); } });
  Combat.hz.spProp = function (h) { const f = h.owner; if (!f) return false; h.x += h.dir * 9; h.y = (h.y || -150) + Math.sin(h.t * .3) * 2; for (const e of Combat.targets(f.side)) if (Math.abs(e.x - h.x) < 50 && e.y > -200 && !h.hit.has(e)) { h.hit.add(e); Combat.resolveHit(e, f, H_({ dmg: h.dmg || 54, guard: 'mid', hs: 16, kb: [260 * h.dir, -280], launch: true, sfx: 'h' }), { proj: true, fromX: h.x, move: h.move }); haunt(f, e); sfx('spCrash'); } return h.t < h.life && h.x > -60 && h.x < Arena.stage.width + 60; };
  Combat.drawHz.spProp = (c, h) => { c.save(); c.translate(h.x, h.y || -130); c.rotate(h.t * .1 * h.dir); c.globalAlpha = .9; c.fillStyle = ['#6a5a4a', '#8a6a4a', '#4a4a5a'][h.kind2 || 0]; c.strokeStyle = '#aac0ff'; c.lineWidth = 2; if (h.kind2 === 1) { c.fillRect(-14, -14, 28, 28); c.strokeRect(-14, -14, 28, 28); } else if (h.kind2 === 2) { c.fillRect(-26, -10, 52, 20); c.strokeRect(-26, -10, 52, 20); c.fillStyle = '#e8e8f0'; for (let i = -4; i < 4; i++) c.fillRect(i * 6, -10, 3, 10); } else { c.fillRect(-20, -4, 40, 8); c.fillRect(-18, 4, 5, 18); c.fillRect(13, 4, 5, 18); c.strokeRect(-20, -4, 40, 8); } c.globalCompositeOperation = 'lighter'; glowCircle(c, 0, 0, 40, 'rgba(170,192,255,0.3)', 'rgba(0,0,0,0)'); c.restore(); };

  const F5 = Mv.shot({ name: 'Spectral Volley', desc: 'Poltergeist: five ecto bullets that pass straight through walls and haunt on hit.', proj: { speed: 1100, r: 9, dmg: 30, count: 5, spread: .5, kind: 'orb', color: '#aac0ff', core: '#fff', pierce: true, noWall: true, life: 1.2, onHit: (t, p) => haunt(p.owner, t) }, ev: { 3: () => sfx('spWail', 0, .6), 12: () => sfx('spPhase') } });
  const F6 = mk({ name: 'Phase Slash', desc: 'Poltergeist: passes through the foe twice, cutting on both passes, and ends back where he began.', pose: 'dash', s: 5, a: 26, r: 18, inv: [1, 32], ai: { min: 100, max: 800, use: 'approach' }, ev: { 5: f => { const t = f.opp, x0 = f.x; if (!t) return; f.x = clamp(t.x + f.facing * 90, 40, Arena.stage.width - 40); f.facing *= -1; sfx('spPhase'); Combat.strikeZone(f, { x: Math.min(x0, f.x) - 20, y: -140, w: Math.abs(f.x - x0) + 40, h: 140 }, { dmg: 44, guard: 'mid', hs: 12, kb: [80, -100], sfx: 'm' }, { move: F6 }); f.vtx = x0; }, 20: f => { const t = f.opp; if (!t) return; const x0 = f.x; f.x = clamp(f.vtx ?? f.x, 40, Arena.stage.width - 40); f.facing *= -1; sfx('spPhase'); Combat.strikeZone(f, { x: Math.min(x0, f.x) - 20, y: -140, w: Math.abs(f.x - x0) + 40, h: 140 }, { dmg: 70, guard: 'mid', hs: 18, kb: [300 * f.facing, -480], launch: true, sfx: 'h' }, { move: F6 }); haunt(f, t); } } });
  const F2 = mk({ name: 'Deep Possession', desc: 'Poltergeist: seizes the foe\'s body: swaps places, they are stunned and confused for a moment, and take two HAUNTS.', pose: 'cast', s: 14, a: 1, r: 26, cd: 8, ai: { min: 100, max: 700, use: 'trap' }, ev: { 14: f => { const t = f.opp; if (!t || Math.abs(t.x - f.x) > 700) return; Combat.swap(f, { confuse: 2, dmg: 40 }); t.status.stun = Math.max(t.status.stun || 0, .9); haunt(f, t, 2); sfx('spWail'); sfx('spChains'); } } });
  const F4 = mk({ name: 'Poltergeist Wave', desc: 'Poltergeist: a table, a chair and a piano fly across the stage, one after another.', pose: 'cast_up', s: 16, a: 1, r: 26, cd: 5, ai: { min: 100, max: 1200, use: 'zone' }, ev: { 16: f => { for (let i = 0; i < 3; i++) Game.later(i * .22, () => { Combat.addHazard({ kind: 'spProp', owner: f, side: f.side, x: f.x + f.facing * 50, y: -90 - i * 40, dir: f.facing, kind2: i, dmg: 50 + i * 12, life: 120, hit: new Set(), move: F4 }); sfx('spCrash'); }); sfx('spWail'); } } });
  const FJ = Mv.dive({ name: 'Haunt Plunge', desc: 'Poltergeist: dives through the floor and bursts up under the foe.', vx: 600, vy: 1500, hit: { dmg: 90, gb: true }, ev: { 1: () => sfx('spPhase') }, onHit: (a, t) => haunt(a, t) });
  const FU = PxKit.ult({ id: 'spectre_fult', name: 'DEAD OF NIGHT', desc: 'Poltergeist: the clocks all stop at midnight. The whole house comes for the guest. Blockable. Must connect.', pose: 'cast_up', s: 48, dmg: 1280, color: '#aac0ff',
    cutscene: (a, t) => PxKit.cineUlt(a, t, { name: 'DEAD OF NIGHT', dur: 8.6, tc: [1.0, 4.6], tf: 5.4, c1: '#aac0ff', c2: '#ffffff', c3: '#06081a', motif: 'barrage', pose: ['idle', 'cast_up', 'cast_up', 'victory'], actorForm: true, cap1: 'Twelve strokes.', cap2: 'The house is awake.', title: 'DEAD OF NIGHT', sub: 'MIDNIGHT', size: 100,
      cues: [[0, () => sfx('spMidnight')], [1.4, () => sfx('spWail', 0, 2)], [5.4, () => { sfx('spCrash'); sfx('spCrash', .15); sfx('spChains'); sfx('boom'); }]],
      bg: (x, t, k) => PxKit.sky(x, t, { top: '#02030e', bot: '#1a2248', moon: { x: .5, y: .22, r: 90, col: '#d8e0ff' }, ruins: '#080a1c', fog: 'rgba(170,192,255,0.12)', stars: '#aac0ff' }, k) }) });
  FU.ev = PxKit.zoneEv(FU, { at: 48, w: 900, h: 340, back: 400, start: f => { f.say('Boo.', 90); sfx('spWail', 0, 2); }, fire: f => { for (let i = 0; i < 8; i++) Game.later(i * .06, () => { const x = clamp(f.x + f.facing * (60 + i * 100), 30, Arena.stage.width - 30); Combat.explode(x, -80, 70, f, 0, '#aac0ff'); sfx('spCrash'); }); const t = f.opp; if (t) haunt(f, t, 3); Cam.shake = 20; sfx('boom'); } });
  PxKit.formKit(def, { moves: { '5S': F5, '6S': F6, '2S': F2, '4S': F4, 'jS': FJ }, ult: FU, desc: 'Permanent. Fully ethereal. New moveset: Spectral Volley, Phase Slash, Deep Possession, Poltergeist Wave, Haunt Plunge, and the ultimate DEAD OF NIGHT.' });

  def.ult.ult.cutscene = (a, t) => PxKit.cineUlt(a, t, { name: 'THE HAUNTING', dur: 8.0, tc: [1.0, 4.0], tf: 4.8, c1: '#aac0ff', c2: '#ffffff', c3: '#06081a', motif: 'rift', pose: ['idle', 'cast', 'dash', 'victory'], cap1: 'Welcome to the house.', cap2: 'You are staying.', title: 'THE HAUNTING', sub: 'THE OTHER SIDE', size: 96,
    cues: [[0, () => sfx('spWail', 0, 2)], [1.4, () => sfx('spChains')], [4.8, () => { sfx('spPhase'); sfx('spCrash'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#02030e', bot: '#161c40', moon: { x: .7, y: .22, r: 80, col: '#d8e0ff' }, ruins: '#080a1c', fog: 'rgba(170,192,255,0.1)' }, k) });
  def.transformCutscene = f => PxKit.cineForm(f, { name: 'POLTERGEIST', dur: 6.4, tc: [1.0, 3.4], tf: 3.7, c1: '#aac0ff', c2: '#ffffff', c3: '#06081a', motif: 'implode', pose: ['idle', 'cast_up', 'victory'], lift: 50, cap1: 'Nothing holds me anymore.', cap2: 'Not even the floor.', title: 'POLTERGEIST', sub: 'SPECTRE', size: 100,
    cues: [[0, () => sfx('spWail', 0, 2)], [1.4, () => sfx('spChains')], [3.7, () => { sfx('spCrash'); sfx('spWail', 0, 1.4); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#02030e', bot: '#161c40', moon: { x: .5, y: .22, r: 80, col: '#d8e0ff' }, fog: 'rgba(170,192,255,0.12)', stars: '#aac0ff' }, k) });
})();
