// ============================================================
//  MOONKAI — MADAME ROSE, the Crimson Countess. Pixel remake + COUNTESS UNBOUND moveset.
//  (BLOOD, The Waltz, Masquerade and Crimson Waltz stay as they were.)
//  COUNTESS UNBOUND   BAT TEMPEST (5S) a spiralling swarm, CRIMSON MIST (6S) three steps through the mist, KISS OF DEATH: ETERNAL (2S) a
//                     longer drain, BLOOD FOUNTAIN (4S) a pool that erupts, SWOOP FEAST (jS).   DANSE ROUGE (form ult).
// ============================================================
(() => {
  const sfx = PxKit.sfx, def = charById('rose');
  Object.assign(Sfx, {
    rsBats(d = 0, n = 10) { for (let i = 0; i < n; i++) this.nsweep({ f0: 2500 + (i % 4) * 400, f1: 6000, dur: .08, vol: .07, type: 'bandpass', q: 2, delay: d + i * .05, wet: .4 }); },
    rsMist(d = 0) { this.nsweep({ f0: 1800, f1: 300, dur: .4, vol: .14, delay: d, wet: .7 }); this.voice({ f: 330, to: 110, dur: .4, vol: .08, delay: d, wet: .7 }); },
    rsDrink(d = 0, dur = .9) { this.nsweep({ f0: 200, f1: 1800, dur, vol: .16, q: 2, delay: d, wet: .5 }); this.voice({ f: 90, to: 160, dur, vol: .1, delay: d }); },
    rsOrgan(d = 0, dur = 3) { this.chord({ notes: [131, 156, 196, 262], dur, vol: .22, type: 'sawtooth', lp: 900, delay: d, wet: .9, det: 12 }); this.run({ notes: [523, 622, 784, 622, 523], step: .3, dur: 1.6, vol: .08, bell: true, delay: d + .4, wet: .9 }); },
    rsWaltz(d = 0) { for (let i = 0; i < 6; i++) { this.sub({ f: 110, to: 60, dur: .15, vol: i % 3 === 0 ? .3 : .12, delay: d + i * .33 }); } this.rsOrgan(d, 2.4); },
    rsBurst(d = 0) { this.impact(.8, d); this.nsweep({ f0: 600, f1: 3000, dur: .5, vol: .16, delay: d, wet: .5 }); this.rsBats(d, 8); },
  });
  PxKit.pixelize(def, { win: [-260, -340, 560, 400] });
  Combat.hz.rsFountain = function (h) { const f = h.owner; if (!f) return false; if (h.t === h.at) for (const e of Combat.targets(f.side)) if (Math.abs(e.x - h.x) < h.r && e.y > -240) { Combat.resolveHit(e, f, H_({ dmg: 96, guard: 'mid', hs: 24, kb: [0, -840], launch: true, status: { bleed: 3 }, sfx: 'h' }), { proj: true, fromX: h.x, move: h.move }); rsBlood(f, 20); Combat.healSelf(f, 24); sfx('rsBurst'); } return h.t < h.life; };
  Combat.drawHz.rsFountain = (c, h) => { const arm = h.t < h.at, k = arm ? h.t / h.at : 1 - (h.t - h.at) / (h.life - h.at); c.save(); if (arm) { c.fillStyle = `rgba(160,10,40,${.4 + .4 * k})`; c.beginPath(); c.ellipse(h.x, -3, h.r * (.4 + .6 * k), 8, 0, 0, 7); c.fill(); } else { c.globalCompositeOperation = 'lighter'; for (let i = 0; i < 36; i++) { const y = -((i * 37 + h.t * 22) % 420), w = h.r * .5 * (1 - Math.abs(y) / 480) * k; c.fillStyle = i % 3 ? 'rgba(220,20,50,.9)' : 'rgba(255,120,140,.9)'; c.fillRect(Math.round((h.x + Math.sin(i * 2.1) * w) / 3) * 3, Math.round(y / 3) * 3, 8, 8); } glowCircle(c, h.x, -120, h.r, `rgba(220,20,50,${.3 * k})`, 'rgba(0,0,0,0)'); } c.restore(); };
  Combat.hz.rsTempest = function (h) { const f = h.owner; if (!f || f.state === 'ko') return false; h.x = f.x; if (h.t % 8 === 3) for (const e of Combat.targets(f.side)) if (Math.abs(e.x - h.x) < 240 && e.y > -200) { Combat.resolveHit(e, f, H_({ dmg: 20, guard: 'mid', hs: 8, kb: [Math.sign(e.x - h.x || 1) * 100, -80], sfx: 'm', status: { bleed: 1 } }), { proj: true, fromX: h.x }); rsBlood(f, 2); } return h.t < h.life; };
  Combat.drawHz.rsTempest = (c, h) => { c.save(); c.fillStyle = '#1a0008'; for (let i = 0; i < 22; i++) { const a = h.t * .22 + i * .29, r = 50 + (i % 5) * 36, x = h.x + Math.cos(a) * r, y = -90 + Math.sin(a * 1.3) * 60; c.beginPath(); c.moveTo(x, y); c.lineTo(x - 8, y - 5 + Math.sin(h.t + i) * 3); c.lineTo(x - 3, y + 1); c.lineTo(x + 3, y + 1); c.lineTo(x + 8, y - 5 + Math.sin(h.t + i) * 3); c.closePath(); c.fill(); } c.restore(); };

  const F5 = mk({ name: 'Bat Tempest', desc: 'Countess Unbound: a spiralling swarm around her for 2s: it bites everyone in reach, and feeds BLOOD.', pose: 'cast_up', s: 14, a: 1, r: 24, cd: 5, ai: { min: 0, max: 300, use: 'combo' }, ev: { 3: () => sfx('rsBats'), 14: f => { Combat.addHazard({ kind: 'rsTempest', owner: f, side: f.side, x: f.x, life: 120 }); sfx('rsBats', 0, 18); } } });
  const F6 = mk({ name: 'Crimson Mist', desc: 'Countess Unbound: dissolves into mist and reappears three times around the foe, biting each time.', pose: 'heavy', s: 6, a: 24, r: 18, inv: [1, 30], ai: { min: 100, max: 900, use: 'approach' }, ev: { 6: f => { sfx('rsMist'); Rw2.blink(f, { n: 3, gap: 8, dmg: 34, last: 76, color: '#c01030', sfx: () => sfx('rsMist'), move: F6 }); } } });
  const F2 = Object.assign(Mv.grab({ name: 'Kiss of Death: Eternal', desc: 'Countess Unbound: a longer, deeper drain. Drinks ALL stored BLOOD as a heal (x3).', range: 70, s: 8, grabData: { anim: 'drain', dmg: 220, frames: 56 }, ev: { 3: () => sfx('rsDrink') } }), { onHit: a => { const n = a.gauge || 0; if (n > 0) { Combat.healSelf(a, Math.round(n * 3 + 60)); a.gauge = 0; } sfx('rsDrink'); } });
  const F4 = mk({ name: 'Blood Fountain', desc: 'Countess Unbound: a pool of blood under the foe, then a fountain. Spends up to 40 BLOOD to grow wider.', pose: 'cast_up', s: 16, a: 1, r: 24, cd: 6, ai: { min: 100, max: 1000, use: 'zone' }, ev: { 16: f => { const t = f.opp; if (!t) return; const spend = Math.min(40, f.gauge || 0); f.gauge = (f.gauge || 0) - spend; Combat.addHazard({ kind: 'rsFountain', owner: f, side: f.side, x: clamp(t.x, 80, Arena.stage.width - 80), r: 80 + spend * 1.5, life: 60, at: 28, move: F4 }); sfx('rsDrink'); } } });
  const FJ = Mv.dive({ name: 'Swoop Feast', desc: 'Countess Unbound: a bat-wing dive that bites on arrival and drinks a little.', vx: 700, vy: 1500, hit: { dmg: 92, gb: true, status: { bleed: 3 } }, ev: { 1: () => sfx('rsBats') }, onHit: a => { Combat.healSelf(a, 40); rsBlood(a, 14); sfx('rsDrink'); } });
  const FU = PxKit.ult({ id: 'rose_fult', name: 'DANSE ROUGE', desc: 'Countess Unbound: the ballroom doors open on a thousand dancers. They all want a turn. Blockable. Must connect.', pose: 'cast_up', s: 54, dmg: 1280, color: '#c01030',
    cutscene: (a, t) => PxKit.cineUlt(a, t, { name: 'DANSE ROUGE', dur: 8.8, tc: [1.0, 4.8], tf: 5.6, c1: '#c01030', c2: '#ffd0d8', c3: '#14040a', motif: 'barrage', pose: ['idle', 'cast_up', 'cast_up', 'victory'], actorForm: true, cap1: 'The orchestra has been waiting.', cap2: 'You will lead. Badly.', title: 'DANSE ROUGE', sub: 'ONE, TWO, THREE', size: 104,
      cues: [[0, () => sfx('rsOrgan', 0, 3)], [1.4, () => sfx('rsWaltz')], [5.6, () => { sfx('rsBurst'); sfx('rsBats', .1, 20); sfx('boom'); }]],
      bg: (x, t, k) => { PxKit.sky(x, t, { top: '#14040a', bot: '#5a0a1e', pillars: '#2a0810', rays: '#ffd0d8', embers: '#ff4a6a' }, k); x.save(); x.fillStyle = `rgba(255,208,216,${.1 + .3 * k})`; x.beginPath(); x.moveTo(W * .5, H); x.lineTo(W * .15, H * .2); x.lineTo(W * .85, H * .2); x.fill(); x.restore(); } }) });
  FU.ev = PxKit.zoneEv(FU, { at: 54, w: 900, h: 340, back: 400, start: f => { f.say('A dance.', 90); sfx('rsWaltz'); }, fire: f => { Combat.addHazard({ kind: 'rsTempest', owner: f, side: f.side, x: f.x, life: 90 }); for (let i = -3; i <= 3; i++) Combat.addHazard({ kind: 'rsFountain', owner: f, side: f.side, x: clamp(f.x + f.facing * i * 130 + f.facing * 260, 60, Arena.stage.width - 60), r: 70, life: 40, at: 10 + Math.abs(i) * 4, move: FU }); Cam.shake = 20; sfx('rsBurst'); sfx('boom'); } });
  PxKit.formKit(def, { moves: { '5S': F5, '6S': F6, '2S': F2, '4S': F4, 'jS': FJ }, ult: FU, desc: 'Permanent. Bat wings and flight, 10% lifesteal, doubled beat window, double BLOOD stored. New moveset: Bat Tempest, Crimson Mist, Kiss of Death: Eternal, Blood Fountain, Swoop Feast, and the ultimate DANSE ROUGE.' });

  def.ult.ult.cutscene = (a, t) => PxKit.cineUlt(a, t, { name: 'CRIMSON WALTZ', dur: 8.2, tc: [1.0, 4.2], tf: 5.0, c1: '#c01030', c2: '#ffd0d8', c3: '#14040a', motif: 'shockwave', pose: ['idle', 'cast_up', 'cast', 'victory'], cap1: 'May I have this dance?', cap2: 'You may not refuse.', title: 'CRIMSON WALTZ', sub: 'THE DANCE BEGINS', size: 96,
    cues: [[0, () => sfx('rsOrgan', 0, 2.4)], [1.4, () => sfx('rsWaltz')], [5.0, () => { sfx('rsBurst'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#14040a', bot: '#4a0a1a', pillars: '#2a0810', rays: '#ffd0d8', embers: '#ff4a6a' }, k) });
  def.transformCutscene = f => PxKit.cineForm(f, { name: 'COUNTESS UNBOUND', dur: 6.6, tc: [1.0, 3.6], tf: 3.9, c1: '#c01030', c2: '#ffd0d8', c3: '#14040a', motif: 'rise', pose: ['idle', 'cast_up', 'victory'], lift: 40, cap1: 'The ball never ends.', cap2: 'It only changes partners.', title: 'COUNTESS UNBOUND', sub: 'MADAME ROSE', size: 94,
    cues: [[0, () => sfx('rsOrgan', 0, 2.4)], [1.4, () => sfx('rsBats', 0, 14)], [3.9, () => { sfx('rsBurst'); sfx('rsOrgan', 0, 2); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#14040a', bot: '#5a0a1e', pillars: '#2a0810', rays: '#ffd0d8', embers: '#ff4a6a' }, k) });
})();
