// ============================================================
//  MOONKAI — PROF. QUANTA, the Observer. Pixel remake + a real kit.
//
//  ENTANGLE (mark on the foe, max 3)  every orb that lands entangles the foe. At 3 the wavefunction COLLAPSES: they are thrown to a
//                                      random point on the stage, confused for 1.5s, and take 60.
//  SUPERPOSITION (passive)  her projectiles sometimes split in two (as before).
//  SUPERPOSITION FORM  PROBABILITY CLOUD (5S) seven orbs at random angles, TUNNEL THROUGH (6S) she tunnels through the foe, striking,
//                      WORMHOLE (2S) a pair of linked portals that pull, SCHRODINGER STEP (4S) swap places with her shadow,
//                      PARTICLE STORM (jS).   UNCERTAINTY PRINCIPLE (form ult).
// ============================================================
(() => {
  const sfx = PxKit.sfx, def = charById('quanta');
  Object.assign(Sfx, {
    quBlip(d = 0, p = 1) { this.fm({ f: 740 * p, ratio: 1.5, index: 90, dur: .3, vol: .12, delay: d, wet: .7 }); },
    quWarp(d = 0) { this.voice({ f: 200, to: 1800, dur: .25, vol: .12, type: 'sine', delay: d, wet: .6 }); this.voice({ f: 1800, to: 200, dur: .25, vol: .1, type: 'sine', delay: d + .25, wet: .6 }); },
    quCollapse(d = 0) { this.sub({ f: 90, to: 30, dur: .6, vol: .4, delay: d }); this.crackle({ dur: .3, vol: .1, delay: d, lo: 600, hi: 8000 }); this.quBlip(d + .05, .6); },
    quHum(d = 0, dur = 2) { this.voice({ f: 220, to: 233, dur, vol: .16, type: 'sine', delay: d, wet: .9 }); this.voice({ f: 330, to: 349, dur, vol: .1, type: 'triangle', n: 3, det: 20, delay: d, wet: .9 }); },
    quHeis(d = 0) { for (let i = 0; i < 8; i++) this.quBlip(d + i * .09, 1 + (i % 4) * .2); this.quCollapse(d + .8); },
    quGate(d = 0) { this.nsweep({ f0: 300, f1: 3000, dur: .5, vol: .14, q: 2, delay: d, wet: .7 }); this.quBlip(d + .3, 1.3); },
  });
  PxModel.install(def, { post(c, v, P, s, m) { if (v.transformed) { const t = v.anim || 0; c.save(); c.globalAlpha = .4; c.globalCompositeOperation = 'lighter'; c.fillStyle = '#6ad8ff'; c.fillRect(P.sh[0] + 20, P.sh[1] - 10, 8, 50); c.fillRect(P.sh[0] - 28, P.sh[1] - 10, 8, 50); c.restore(); } } });
  const ent = (a, t, n = 1) => { if (!t || t.state === 'ko') return; Combat.mark(t, a, 'entangle', n, { max: 3, dur: 9, color: '#6ad8ff', label: 'ENTANGLED', onMax: tt => { delete tt.marks.entangle; tt.x = clamp(rand(120, Arena.stage.width - 120), 60, Arena.stage.width - 60); tt.status.confuse = Math.max(tt.status.confuse || 0, 1.5); Combat.resolveHit(tt, a, H_({ dmg: 60, guard: 'mid', hs: 12, kb: [0, -200], launch: true, sfx: 'h' }), { proj: true, fromX: tt.x }); Game.popWorld(tt.x, tt.y - tt.h - 40, 'COLLAPSE', '#6ad8ff', 26); Game.fx.burst(tt.x, -80, 24, { color: ['#6ad8ff', '#fff'], size: 8, speed: 300, life: .4, glow: true }); sfx('quCollapse'); Cam.shake = 8; } }); };
  Rw2.merge(def, { passive: ['Superposition', 'Her projectiles sometimes split in two. Every orb that lands ENTANGLES the foe (max 3): at 3 the wavefunction collapses and they are flung across the stage, confused.'], onHit: (a, t) => { if (a.move && a.move.kind === 'special') ent(a, t); } });
  Combat.hz.quGate = function (h) { const f = h.owner; if (!f) return false; for (const e of Combat.targets(f.side)) { const d = h.x - e.x; if (Math.abs(d) < h.r && e.y > -160) { e.x += Math.sign(d) * Math.min(Math.abs(d), 3.5); if (Math.abs(d) < 26 && !h.used) { h.used = true; e.x = clamp(h.x2, 40, Arena.stage.width - 40); Combat.resolveHit(e, f, H_({ dmg: 62, guard: 'mid', hs: 14, kb: [200 * f.facing, -320], launch: true, sfx: 'h' }), { proj: true, fromX: h.x }); ent(f, e); sfx('quWarp'); } } } return h.t < h.life; };
  Combat.drawHz.quGate = (c, h) => { const k = Math.min(1, h.t / 8, (h.life - h.t) / 12); c.save(); c.globalAlpha = k; c.globalCompositeOperation = 'lighter'; for (const [x, col] of [[h.x, '#6ad8ff'], [h.x2, '#ff9aff']]) { for (let r = 0; r < 3; r++) { c.strokeStyle = col; c.lineWidth = 3 - r * .7; c.beginPath(); c.ellipse(x, -70, 22 - r * 5, 60 - r * 10, 0, 0, 7); c.stroke(); } glowCircle(c, x, -70, 60, hexA(col, .22), 'rgba(0,0,0,0)'); } c.restore(); };

  const F5 = mk({ name: 'Probability Cloud', desc: 'Superposition: seven orbs in a cloud at random angles, each ENTANGLING on a hit.', pose: 'cast', s: 12, a: 1, r: 22, cd: 2, ai: { min: 100, max: 1300, use: 'zone' }, ev: { 3: () => sfx('quHum', 0, .8), 12: f => { for (let i = 0; i < 7; i++) Game.later(i * .04, () => { Combat.fireShots(f, { speed: 640 + rand(-120, 160), angle: rand(-.5, .5), r: 10, dmg: 34, kind: 'orb', color: i % 2 ? '#6ad8ff' : '#ff9aff', core: '#fff', life: 1.5, onHit: (t, p) => ent(p.owner, t) }); sfx('quBlip', 0, 1 + i * .08); }); } } });
  const F6 = mk({ name: 'Tunnel Through', desc: 'Superposition: she tunnels through the foe and out the other side, striking as she passes.', pose: 'dash', s: 5, a: 12, r: 18, inv: [1, 18], ai: { min: 100, max: 700, use: 'approach' }, ev: { 5: f => { const t = f.opp; if (!t) return; const x0 = f.x; f.x = clamp(t.x + f.facing * 100, 40, Arena.stage.width - 40); sfx('quWarp'); Combat.strikeZone(f, { x: Math.min(x0, f.x) - 20, y: -140, w: Math.abs(f.x - x0) + 40, h: 140 }, { dmg: 70, guard: 'mid', hs: 16, kb: [100, -320], launch: true, sfx: 'h' }, { move: F6 }); ent(f, t); f.facing *= -1; } } });
  const F2 = mk({ name: 'Wormhole', desc: 'Superposition: a pair of linked portals. The foe is pulled into the first and thrown out of the second.', pose: 'cast_up', s: 16, a: 1, r: 24, cd: 7, ai: { min: 100, max: 1000, use: 'zone' }, ev: { 16: f => { const t = f.opp; if (!t) return; Combat.addHazard({ kind: 'quGate', owner: f, side: f.side, x: clamp(t.x, 100, Arena.stage.width - 100), x2: clamp(f.x - f.facing * 120, 60, Arena.stage.width - 60), r: 150, life: 150 }); sfx('quGate'); } } });
  const F4 = mk({ name: 'Schrodinger Step', desc: 'Superposition: swaps places with her shadow copy: she is both where she was and where she is.', pose: 'cast', s: 8, a: 6, r: 14, inv: [1, 14], hit: { dmg: 48, box: [0, -100, 70, 90], kb: [200, -200] }, ai: { min: 150, max: 1100, use: 'approach' }, ev: { 7: f => { const t = f.opp; if (!t) return; Game.fx.burst(f.x, -80, 14, { color: ['#6ad8ff', '#fff'], size: 8, speed: 240, life: .4, glow: true }); Combat.teleport(f, 'behind'); sfx('quWarp'); ent(f, t); } } });
  const FJ = Mv.shot({ name: 'Particle Storm', desc: 'Superposition: a downpour of orbs, half of them in the wrong place.', proj: { speed: 900, angle: 1.0, spread: 1.4, count: 10, r: 8, dmg: 26, kind: 'orb', color: '#6ad8ff', core: '#fff', life: 1.1, onHit: (t, p) => ent(p.owner, t) }, ev: { 2: () => sfx('quBlip') } }); FJ.air = true;
  const FU = PxKit.ult({ id: 'quanta_fult', name: 'UNCERTAINTY PRINCIPLE', desc: 'Superposition: she cannot know where the foe is and where they are going at once, so neither can they. A rain of every possible hit. Blockable. Must connect.', pose: 'cast', s: 48, dmg: 1280, color: '#6ad8ff',
    cutscene: (a, t) => PxKit.cineUlt(a, t, { name: 'UNCERTAINTY PRINCIPLE', dur: 8.4, tc: [1.0, 4.4], tf: 5.2, c1: '#6ad8ff', c2: '#ff9aff', c3: '#04102a', motif: 'rift', pose: ['idle', 'cast', 'cast', 'victory'], actorForm: true, cap1: 'To observe is to change.', cap2: 'So I observed you. Closely.', title: 'UNCERTAINTY PRINCIPLE', sub: 'THE WAVE COLLAPSES', size: 86,
      cues: [[0, () => sfx('quHum', 0, 3)], [1.4, () => sfx('quHeis')], [5.2, () => { sfx('quCollapse'); sfx('quHeis', .1); sfx('boom'); }]],
      bg: (x, t, k) => { PxKit.sky(x, t, { top: '#03091e', bot: '#1c2a6a', stars: '#9ae0ff', grid: 'rgba(106,216,255,.2)' }, k); x.save(); x.globalCompositeOperation = 'lighter'; for (let i = 0; i < 40; i++) { const an = i * 2.4 + t * (1 + k * 3), R = 40 + (i * 21) % 380; x.fillStyle = i % 2 ? 'rgba(106,216,255,.7)' : 'rgba(255,154,255,.7)'; x.fillRect(W / 2 + Math.cos(an) * R * 1.5, H * .34 + Math.sin(an) * R * .5, 8, 8); } x.restore(); } }) });
  FU.ev = PxKit.zoneEv(FU, { at: 48, w: 1000, h: 340, back: 400, start: f => { f.say('Observing...', 90); sfx('quHum', 0, 2); }, fire: f => { for (let i = 0; i < 10; i++) Game.later(i * .05, () => { const t = f.opp; if (t) { const xx = clamp(t.x + rand(-200, 200), 30, Arena.stage.width - 30); Combat.explode(xx, -60 + rand(-40, 40), 70, f, 0, i % 2 ? '#6ad8ff' : '#ff9aff'); } }); const t = f.opp; if (t) ent(f, t, 3); Cam.shake = 20; sfx('quCollapse'); sfx('boom'); } });
  PxKit.formKit(def, { moves: { '5S': F5, '6S': F6, '2S': F2, '4S': F4, 'jS': FJ }, ult: FU, desc: 'TIMED (10s). Exists twice: a shadow copy mirrors every attack. New moveset: Probability Cloud, Tunnel Through, Wormhole, Schrodinger Step, Particle Storm, and the ultimate UNCERTAINTY PRINCIPLE.' });

  def.ult.ult.cutscene = (a, t) => PxKit.cineUlt(a, t, { name: 'WAVEFUNCTION COLLAPSE', dur: 8.0, tc: [1.0, 4.0], tf: 4.8, c1: '#6ad8ff', c2: '#ffffff', c3: '#04102a', motif: 'beam', pose: ['idle', 'cast', 'cast', 'victory'], cap1: 'A particle is everywhere...', cap2: '...until someone looks.', title: 'WAVEFUNCTION COLLAPSE', sub: 'OBSERVED', size: 84,
    cues: [[0, () => sfx('quHum', 0, 2.4)], [1.4, () => sfx('quWarp')], [4.8, () => { sfx('quCollapse'); sfx('quHeis'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#03091e', bot: '#1c2a6a', stars: '#9ae0ff', grid: 'rgba(106,216,255,.2)' }, k) });
  def.transformCutscene = f => PxKit.cineForm(f, { name: 'SUPERPOSITION', dur: 6.4, tc: [1.0, 3.4], tf: 3.7, c1: '#6ad8ff', c2: '#ff9aff', c3: '#04102a', motif: 'implode', pose: ['idle', 'cast', 'victory'], lift: 24, cap1: 'Here and also there.', cap2: 'Statistically, both are correct.', title: 'SUPERPOSITION', sub: 'PROF. QUANTA', size: 92,
    cues: [[0, () => sfx('quHum', 0, 2.4)], [1.4, () => sfx('quHeis')], [3.7, () => { sfx('quCollapse'); sfx('quGate'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#03091e', bot: '#1c2a6a', stars: '#9ae0ff', grid: 'rgba(106,216,255,.2)' }, k) });
})();
