// ============================================================
//  MOONKAI — OMEGA, the Final Protocol. Pixel remake + OMEGA PROTOCOL moveset.
//  (ANALYSIS, SOLUTION FOUND, Adaptation, Drone and Deletion stay as they were.)
//  OMEGA PROTOCOL   PLASMA BARRAGE (5S) nine bolts in an aimed fan, THRUSTER RAID (6S) two passes through the foe, TARGET LOCK (2S) paints
//                   the foe and feeds ANALYSIS, DRONE SQUADRON (4S) three drones at once, ORBITAL RAIN (jS).
//                   TERMINATION PROTOCOL (form ult)   every satellite he has ever owned fires.
// ============================================================
(() => {
  const sfx = PxKit.sfx, def = charById('omega');
  Object.assign(Sfx, {
    omPlasma(d = 0) { this.nsweep({ f0: 3500, f1: 400, dur: .14, vol: .22, delay: d }); this.fm({ f: 180, ratio: 5, index: 300, dur: .14, vol: .1, delay: d }); },
    omServo(d = 0) { this.voice({ f: 140, to: 280, dur: .3, vol: .1, type: 'sawtooth', lp: 1200, delay: d }); this.nsweep({ f0: 600, f1: 2200, dur: .3, vol: .06, delay: d }); },
    omLock(d = 0) { for (let i = 0; i < 3; i++) this.fm({ f: 1800, ratio: 1, index: 0, dur: .07, vol: .1, type: 'square', delay: d + i * .12 }); this.fm({ f: 2400, ratio: 1, index: 0, dur: .3, vol: .1, type: 'square', delay: d + .4 }); },
    omRaid(d = 0) { this.nsweep({ f0: 800, f1: 4500, dur: .3, vol: .22, delay: d }); this.voice({ f: 100, to: 400, dur: .3, vol: .16, type: 'sawtooth', lp: 900, delay: d }); },
    omVoice(d = 0, dur = 2) { this.voice({ f: 82, to: 80, dur, vol: .28, type: 'sawtooth', lp: 500, n: 3, det: 12, delay: d, wet: .5 }); this.chord({ notes: [82, 123, 165], dur, vol: .14, type: 'square', lp: 700, delay: d, wet: .6 }); },
    omDelete(d = 0) { this.riser(1.6, .24, d, 80, 3000); this.impact(1, d + 1.6); this.crackle({ dur: .6, vol: .12, delay: d + 1.6, lo: 400, hi: 9000 }); this.sub({ f: 70, to: 24, dur: 1.2, vol: .5, delay: d + 1.6 }); },
  });
  PxKit.pixelize(def, { win: [-240, -340, 520, 400] });
  const F5 = mk({ name: 'Plasma Barrage', desc: 'Omega Protocol: nine bolts in an aimed fan; the middle three are heavier. ANALYSIS +6.', pose: 'cast', s: 10, a: 12, r: 18, ai: { min: 100, max: 1300, use: 'zone' }, ev: { 10: f => { Combat.fireShots(f, { speed: 1200, r: 8, dmg: 24, count: 6, spread: .6, kind: 'bolt', color: '#ff2a2a', core: '#fff', life: 1, ultConnect: false }); Combat.fireShots(f, { speed: 1400, r: 12, dmg: 40, count: 3, spread: .2, kind: 'bolt', color: '#ff6a2a', core: '#fff', life: 1 }); sfx('omPlasma'); sfx('omPlasma', .06); omAnalyze(f, 6); } } });
  const F6 = mk({ name: 'Thruster Raid', desc: 'Omega Protocol: blasts through the foe, turns on the thrusters, and passes through again from the other side.', pose: 'dash', s: 5, a: 22, r: 18, inv: [1, 26], ai: { min: 100, max: 800, use: 'approach' }, ev: { 5: f => { const t = f.opp; if (!t) return; const x0 = f.x; f.x = clamp(t.x + f.facing * 110, 40, Arena.stage.width - 40); sfx('omRaid'); Combat.strikeZone(f, { x: Math.min(x0, f.x) - 20, y: -150, w: Math.abs(f.x - x0) + 40, h: 150 }, { dmg: 58, guard: 'mid', hs: 14, kb: [100, -200], sfx: 'm' }, { move: F6 }); f.facing *= -1; }, 18: f => { const t = f.opp; if (!t) return; const x0 = f.x; f.x = clamp(t.x + f.facing * 110, 40, Arena.stage.width - 40); sfx('omRaid'); Combat.strikeZone(f, { x: Math.min(x0, f.x) - 20, y: -150, w: Math.abs(f.x - x0) + 40, h: 150 }, { dmg: 80, guard: 'mid', hs: 20, kb: [400 * f.facing, -480], launch: true, sfx: 'h' }, { move: F6 }); omAnalyze(f, 10); } } });
  const F2 = mk({ name: 'Target Lock', desc: 'Omega Protocol: paints the foe for 3s. Every hit on a painted foe feeds ANALYSIS by 8.', pose: 'cast', s: 14, a: 1, r: 22, cd: 6, ai: { min: 150, max: 1200, use: 'zone' }, ev: { 3: () => sfx('omLock'), 14: f => { const t = f.opp; if (!t) return; Combat.mark(t, f, 'locked', 1, { max: 1, dur: 3, color: '#ff2a2a', label: 'LOCKED' }); omAnalyze(f, 20); sfx('omLock'); } } });
  const F4 = mk({ name: 'Drone Squadron', desc: 'Omega Protocol: three drones deploy at once, each firing three bolts before it self-destructs.', pose: 'cast_up', s: 14, a: 1, r: 22, cd: 7, ai: { min: 150, max: 1200, use: 'trap' }, ev: { 14: f => { const t = f.opp; if (!t) return; for (let i = 0; i < 3; i++) Game.later(i * .25, () => { Combat.place(f, { kind: 'turret', at: 'front', dx: 80 + i * 80, life: 3, hp: 40, shotDmg: 22, limit: 6, color: '#ff2a2a' }); sfx('omServo'); }); } } });
  const FJ = Mv.shot({ name: 'Orbital Rain', desc: 'Omega Protocol: missiles and bolts rain down in two staggered volleys.', proj: { speed: 800, angle: 1.1, spread: 1.2, count: 8, r: 9, dmg: 32, kind: 'missile', color: '#ff2a2a', explode: 50, life: 1.3 }, ev: { 2: () => sfx('omServo') } }); FJ.air = true;
  const FU = PxKit.ult({ id: 'omega_fult', name: 'TERMINATION PROTOCOL', desc: 'Omega Protocol: every satellite he has ever owned fires at once. Blockable. Must connect.', pose: 'cast_up', s: 52, dmg: 1320, color: '#ff2a2a',
    cutscene: (a, t) => PxKit.cineUlt(a, t, { name: 'TERMINATION PROTOCOL', dur: 8.6, tc: [1.0, 4.6], tf: 5.4, c1: '#ff2a2a', c2: '#ffffff', c3: '#100000', motif: 'pillar', pose: ['idle', 'cast_up', 'cast_up', 'victory'], actorForm: true, cap1: 'SOLUTION FOUND.', cap2: 'EXECUTE.', title: 'TERMINATION PROTOCOL', sub: 'NO FURTHER INPUT', size: 86,
      cues: [[0, () => sfx('omVoice', 0, 2.4)], [1.4, () => sfx('omLock', 0)], [5.4, () => { sfx('omDelete'); sfx('boom'); }]],
      bg: (x, t, k) => { PxKit.sky(x, t, { top: '#080000', bot: '#3a0808', stars: '#ff6a6a', grid: 'rgba(255,42,42,.25)' }, k); x.save(); x.globalCompositeOperation = 'lighter'; x.strokeStyle = `rgba(255,42,42,${.3 + .6 * k})`; x.lineWidth = 3; for (let i = 0; i < 5; i++) { const xx = W * (.2 + i * .15); x.beginPath(); x.moveTo(xx, 0); x.lineTo(W * .5 + (xx - W * .5) * (1 - k * .6), H * .8); x.stroke(); } x.restore(); } }) });
  FU.ev = PxKit.trackEv(FU, { at: 52, r: 160, color: '#ff2a2a', start: f => { f.say('SOLUTION FOUND.', 90); sfx('omVoice', 0, 1.6); sfx('omLock'); }, fire: (f, x) => { for (let i = -3; i <= 3; i++) Rw2.pillar(f, x + i * 90, { r: 46, life: 4 + Math.abs(i) * 3, color: '#ff2a2a', dmg: 0, giant: true, shake: 4 }); Cam.shake = 24; sfx('omDelete'); sfx('boom'); } });
  PxKit.formKit(def, { moves: { '5S': F5, '6S': F6, '2S': F2, '4S': F4, 'jS': FJ }, ult: FU, desc: 'TIMED (10s). Overclocked: faster, stronger, super armor, ANALYSIS fills twice as fast. New moveset: Plasma Barrage, Thruster Raid, Target Lock, Drone Squadron, Orbital Rain, and the ultimate TERMINATION PROTOCOL.' });

  def.ult.ult.cutscene = (a, t) => PxKit.cineUlt(a, t, { name: 'DELETION', dur: 8.0, tc: [1.0, 4.0], tf: 4.8, c1: '#ff2a2a', c2: '#ffffff', c3: '#100000', motif: 'pillar', pose: ['idle', 'cast_up', 'cast_up', 'victory'], cap1: 'TARGET ACQUIRED.', cap2: 'DELETING.', title: 'DELETION', sub: 'FILE NOT FOUND', size: 104,
    cues: [[0, () => sfx('omVoice')], [1.4, () => sfx('omLock')], [4.8, () => { sfx('omDelete'); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#080000', bot: '#300606', stars: '#ff6a6a', grid: 'rgba(255,42,42,.2)', city: '#140404', lit: .2 }, k) });
  def.transformCutscene = f => PxKit.cineForm(f, { name: 'OMEGA PROTOCOL', dur: 6.4, tc: [1.0, 3.4], tf: 3.7, c1: '#ff2a2a', c2: '#ffffff', c3: '#100000', motif: 'converge', shape: 'rect', pose: ['idle', 'cast', 'victory'], cap1: 'LIMITERS: OFF.', cap2: 'THIS IS NOT A DRILL.', title: 'OMEGA PROTOCOL', sub: 'OMEGA', size: 92,
    cues: [[0, () => sfx('omVoice', 0, 2)], [1.4, () => sfx('omLock')], [3.7, () => { sfx('omRaid'); sfx('omVoice', 0, 1.4); sfx('boom'); }]],
    bg: (x, t, k) => PxKit.sky(x, t, { top: '#080000', bot: '#3a0808', stars: '#ff6a6a', grid: 'rgba(255,42,42,.25)' }, k) });
})();
