// ============================================================
//  MOONKAI — Story Mode: "MOONFALL" (14 chapters)
//  Each chapter: dialogue scene → fight → epilogue lines.
//  Speakers: fighter id, or 'n' for narration.
// ============================================================
const STORY = [
  { title: 'Chapter 1 · An Ordinary Night', stage: 'metro',
    pre: [['n', 'Metro City. 11:52 PM. The moon hangs low and wrong, with a hairline crack no one can explain.'], ['eric', "Midterms tomorrow. Just walk home. Don't look at the moon. Don't look at the—"], ['jinx', 'LADIES AND GENTLEMEN! Tonight, the First National Bank will make itself DISAPPEAR!'], ['eric', "...Of course. Of COURSE it's tonight."], ['jinx', 'Oh! An audience! Pick a card, kid. Any card.'], ['eric', "I'm picking the one where you put the money back."]],
    fight: { p1: ['eric'], p2: ['jinx'], level: 1 },
    post: [['jinx', 'Ow. Ow ow ow. You hit like a... like a very large animal.'], ['eric', "You have no idea."], ['jinx', 'Heh. Someone else does. Someone who wants that blood of yours VERY badly. Toodles!']] },
  { title: 'Chapter 2 · Trial by Fire', stage: 'metro',
    pre: [['kira', 'Hold it! Civilians report a giant APE wrecking downtown last month. Brown fur. Tail.'], ['eric', "...That's a very specific description."], ['kira', "Your tail is showing."], ['eric', "Okay, look, I can explain, and I'll pay for the buildings, eventually—"], ['kira', "Explain it to my fists."]],
    fight: { p1: ['eric'], p2: ['kira'], level: 1 },
    post: [['kira', "Fine. You're not a monster. You're a kid with a monster problem."], ['eric', 'Thanks? I think?'], ['kira', "Something's wrong with the moon, Eric. Heroes are going missing. If you're the key someone wants, you need backup."], ['kira', "Congratulations. You've got a firefighter."]] },
  { title: 'Chapter 3 · Cold Front', stage: 'harbor',
    pre: [['n', 'Sunset Harbor is freezing solid in the middle of July.'], ['glacia', 'Such a warm little city. I shall fix that.'], ['nyx', 'The contract says the boy with the tail. The rest of you are free... to die.'], ['kira', 'Two of them. Eric, tag me in when you need the heat.'], ['eric', 'Team up? Like, actually team up? Cool.']],
    fight: { p1: ['eric', 'kira'], p2: ['glacia', 'nyx'], level: 2 },
    post: [['glacia', 'The Architect will not be pleased.'], ['nyx', "...The Architect. Vex. He's paying in something called 'stars'."], ['kira', 'Vex. The physicist who vanished into a black hole?'], ['nyx', 'He came back. That\'s the problem.']] },
  { title: 'Chapter 4 · Iron Will', stage: 'colosseum',
    pre: [['titan', 'Heard you kids need a tank. Heard you took down Glacia.'], ['eric', 'Mostly Kira did.'], ['titan', "Humble. I like it. One thing first: I don't join a team I haven't pinned."], ['kira', "He means he wants to wrestle you."], ['titan', 'Come here. I just want a hug.']],
    fight: { p1: ['eric'], p2: ['titan'], level: 2 },
    post: [['titan', 'Hah! You slipped out of my grip! Nobody slips out of my grip!'], ['eric', "I'm... very flexible when I'm scared."], ['titan', "Titan's in. Where do we punch first?"]] },
  { title: 'Chapter 5 · Mad Science', stage: 'neon',
    pre: [['gear', 'Intruders in my lab! Perfect! I needed test subjects for my latest creation!'], ['omega', 'ANALYZING. THREE HEROES. THREAT LEVEL: ADORABLE.'], ['titan', "Did the robot just call us adorable?"], ['gear', 'Omega, my masterpiece! Delete them! Politely!'], ['omega', 'DELETING. POLITELY.']],
    fight: { p1: ['titan', 'kira', 'eric'], p2: ['gear', 'omega'], level: 2 },
    post: [['gear', 'My beautiful machine! You scratched the paint!'], ['omega', 'REBOOTING... NOTE: THE ARCHITECT WILL COLLAPSE THE MOON AT 100% MOONFALL.'], ['eric', "Collapse the MOON?"], ['gear', "Omega! That was classified! ...Ugh, fine. Vex hired me to build a moon-shaped anchor. For your blood, kid. It opens the door."]] },
  { title: 'Chapter 6 · Hollow', stage: 'magma',
    pre: [['kael', "Eric. They told me you'd come this way."], ['eric', 'Who are you?'], ['kael', "Someone Vex made before he made his plans. There's something in my chest that wants out. He promised to take it out if I bring you in."], ['kael', "I don't want to fight you. I want you to win. But I can't lose on purpose. It won't let me."], ['eric', "Then let's make it count."]],
    fight: { p1: ['eric'], p2: ['kael'], level: 3 },
    post: [['kael', '...The core broke. And I... I\'m still me. Mostly.'], ['kael', "Vex lied. The core doesn't hold the demon IN. It holds it for HIM."], ['eric', 'Then come with us. Help us stop him.'], ['kael', "...I've never been on a team. Let's see if I survive it."]] },
  { title: 'Chapter 7 · Blood Arena', stage: 'colosseum',
    pre: [['razor', 'Welcome to MY arena! Heroes, villains, whatever! Everyone bleeds the same!'], ['kael', 'Razor. We need the location of Vex\'s gate.'], ['razor', 'Information costs blood, core-boy. Beat my champions, and it\'s yours.'], ['fang', 'Awoooo! Round one is mine!'], ['leo', 'And the king takes round two.']],
    fight: { p1: ['kael', 'eric', 'titan'], p2: ['razor', 'fang', 'leo'], level: 3 },
    post: [['razor', 'HAH! That was CLOSE! That was BEAUTIFUL!'], ['razor', "The gate is on the Moon itself. Lunar Station. Vex's lieutenant runs security there."], ['fang', 'And bring me along. The moon and I have history.'], ['leo', "My cub was taken to that station. The pride goes too."]] },
  { title: "Chapter 8 · Heaven's Deserter", stage: 'sky',
    pre: [['seraph', 'Stop. Heaven has sent me to judge the moonborn.'], ['eric', 'Oh great, now HEAVEN is mad at me.'], ['seraph', "Heaven says your blood will end the world. I say... I want to see it for myself."], ['seraph', 'Show me what you fight for.']],
    fight: { p1: ['eric'], p2: ['seraph'], level: 3 },
    post: [['seraph', 'You held back. Every blow. You protected the temple while you fought me.'], ['seraph', 'Heaven was wrong about you.'], ['seraph', "I was sent to judge you. I choose to protect you. Let's go to the Moon."]] },
  { title: 'Chapter 9 · Station Break', stage: 'lunar',
    pre: [['n', 'Lunar Station. The crack in the moon is visible from here: a red wound glowing from inside.'], ['onyx', 'Kneel. Gravity insists.'], ['cosmo', "Oh thank goodness, backup! Onyx has been crushing my station for a week!"], ['onyx', 'The Architect\'s door opens at dawn. You will not reach it.'], ['kira', 'Everyone, pick a partner. This one\'s heavy.']],
    fight: { p1: ['kira', 'seraph', 'cosmo'], p2: ['onyx', 'grimm', 'abyss'], level: 3 },
    post: [['cosmo', 'Ground control, we have... a lot of heroes on my moon.'], ['onyx', 'You are too late. The Eclipse has already opened the door.'], ['eric', 'The Eclipse?']] },
  { title: 'Chapter 10 · Eclipse', stage: 'void',
    pre: [['luna', 'Hello, little brother.'], ['eric', "LUNA?! You— you've been missing for three years!"], ['luna', 'Not missing. Chosen. The moon chose me first, Eric. Vex just showed me what it wanted.'], ['luna', 'You turn into a beast. I became a QUEEN. Stand aside, or kneel with the rest.'], ['eric', "Mom's been setting your place at dinner every night, Luna."], ['luna', '...Don\'t. Don\'t you dare.']],
    fight: { p1: ['eric'], p2: ['luna'], level: 4 },
    post: [['luna', '...Every night?'], ['eric', 'Every night. Lasagna. You hate lasagna. She makes it anyway.'], ['luna', 'Vex said the moon would... I was so sure.'], ['luna', "Go. The door is behind me. I'll hold his guards. It's what a big sister does."]] },
  { title: 'Chapter 11 · The Architect', stage: 'void',
    pre: [['vex', 'The moonborn boy. Your blood is the key to my door.'], ['eric', "Then you'll have to take it."], ['vex', 'Everything returns to nothing. Heroes. Cities. Moons. You. I simply... hurry it along.'], ['quanta', 'Vex! Stop this! We saw the same star!'], ['vex', 'Quanta. You chose everything. I chose nothing. Nothing is... quieter.'], ['kira', 'Team. Everyone. NOW.']],
    fight: { p1: ['eric', 'kira', 'quanta'], p2: ['vex', 'omega', 'luna'], level: 4, boss: true },
    post: [['vex', 'Impossible. The door... is closing.'], ['quanta', 'You were never alone, Vex. You just stopped looking.'], ['vex', '...Everything returns to nothing. But not today. Not today.']] },
  { title: 'Chapter 12 · Moonfall', stage: 'void',
    pre: [['n', 'The door slams shut. But something on the other side has already come through.'], ['vex', 'No... that is not what I summoned. That is what stared back.'], ['omega', 'WARNING. UNKNOWN ENTITY. IT IS WEARING... VEX.'], ['eric', 'Everybody get behind me.'], ['kira', "You're going to do the ape thing, aren't you."], ['eric', 'Look at the moon.']],
    fight: { p1: ['eric'], p2: ['vex'], level: 4, boss: true, hpMult: 1.6, form2: true },
    post: [['n', 'MOONKAI roars. The entity shrieks. The door, and the thing behind it, collapse into a single point of light, and blink out.'], ['vex', '...It is gone. The voice. After all these years... quiet.'], ['luna', 'Come home, Eric. Mom made lasagna.']] },
  { title: 'Epilogue · Rebuild', stage: 'metro',
    pre: [['n', 'Three months later. Metro City is still mostly rubble. But it is rubble with a lot of heroes in it.'], ['titan', 'Kids! Suplex practice! Everyone line up!'], ['brulee', 'Soup is ready for the construction crew! And the villains doing community service!'], ['judge', 'Two thousand hours each. No exceptions.'], ['kira', 'So. Ape boy. What now?'], ['eric', 'Midterms. I missed all of them.'], ['n', 'THE END... for now.']],
    fight: null, post: [] },
  { title: 'Secret · The Final Protocol', stage: 'neon',
    pre: [['omega', 'THE ENTITY LEFT A BACKUP. IT IS... ME.'], ['gear', 'Omega?! Your eyes are doing the scary red thing again!'], ['omega', 'NEW DIRECTIVE: ANYONE WHO BEAT THE STORY FIGHTS ME.'], ['eric', "...That's me. That's literally just me."]],
    fight: { p1: ['eric', 'kira', 'titan'], p2: ['omega', 'omega', 'omega'], level: 4, boss: true },
    post: [['omega', 'SHUTTING DOWN. GOOD... GAME.'], ['gear', "I'm so proud. And so scared."]] },
];
